// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelService.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createApi } from '@reduxjs/toolkit/query/react'
import { TenantSchemaRegistry } from '@thorapi/model/TenantSchemaRegistry'
import customBaseQuery from '../customBaseQuery'; // Import the custom base query

type TenantSchemaRegistryResponse = TenantSchemaRegistry[]
type TenantSchemaRegistryPagedQueryArg = {
  page: number
  size?: number
  example?: Partial<TenantSchemaRegistry>
  /**
   * Cache discriminator only. Do not send this to ThorAPI; callers pass the
   * authenticated principal id/username so RBAC-filtered pages cannot be
   * reused across login boundaries by RTK Query.
   */
  authSessionKey?: string
}

type TenantSchemaRegistryListQueryArg = {
  example?: Partial<TenantSchemaRegistry>
  /**
   * Cache discriminator only. Do not send this to ThorAPI.
   */
  authSessionKey?: string
}

const toTenantSchemaRegistryList = (result: unknown): TenantSchemaRegistryResponse => {
  if (Array.isArray(result)) {
    return result as TenantSchemaRegistryResponse
  }

  const candidate = (result as any)?.content ?? (result as any)?.items ?? (result as any)?.results ?? (result as any)?.data
  return Array.isArray(candidate) ? (candidate as TenantSchemaRegistryResponse) : []
}

export const TenantSchemaRegistryService = createApi({
  reducerPath: 'TenantSchemaRegistry', // This should remain unique
  baseQuery: customBaseQuery,
  tagTypes: ['TenantSchemaRegistry'],
  endpoints: (build) => ({
    // 1) Paged Query Endpoint
    // Standardized pagination: page (0-based), size (page size)
    getTenantSchemaRegistrysPaged: build.query<TenantSchemaRegistryResponse, TenantSchemaRegistryPagedQueryArg>({
      query: ({ page, size = 20, example }) => {
        const q: string[] = [`page=${page}`, `size=${size}`];
        if (example) q.push(`example=${encodeURIComponent(JSON.stringify(example))}`);
        return `TenantSchemaRegistry?${q.join('&')}`;
      },
      providesTags: (result, error, { page }) => {
        const rows = toTenantSchemaRegistryList(result)
        return [
          ...rows
            .filter((row) => row?.id != null)
            .map(({ id }) => ({ type: 'TenantSchemaRegistry' as const, id })),
          { type: 'TenantSchemaRegistry', id: `PAGE_${page}` },
          { type: 'TenantSchemaRegistry', id: 'PARTIAL-LIST' },
        ]
      },
    }),

    // 2) Simple "get all" Query (optional)
    getTenantSchemaRegistrys: build.query<TenantSchemaRegistryResponse, TenantSchemaRegistryListQueryArg | void>({
      query: (arg) => {
        if (arg && (arg as any).example) {
          const ex = (arg as any).example;
          return `TenantSchemaRegistry?example=${encodeURIComponent(JSON.stringify(ex))}`;
        }
        return `TenantSchemaRegistry`;
      },
      providesTags: (result) => {
        const rows = toTenantSchemaRegistryList(result)
        return [
          ...rows
            .filter((row) => row?.id != null)
            .map(({ id }) => ({ type: 'TenantSchemaRegistry' as const, id })),
          { type: 'TenantSchemaRegistry', id: 'LIST' },
          { type: 'TenantSchemaRegistry', id: 'PARTIAL-LIST' },
        ]
      },
    }),

    // 3) Create
    addTenantSchemaRegistry: build.mutation<TenantSchemaRegistry, Partial<TenantSchemaRegistry>>({
      query: (body) => ({
        url: `TenantSchemaRegistry`,
        method: 'POST',
        body,
      }),
      invalidatesTags: [
        { type: 'TenantSchemaRegistry', id: 'LIST' },
        { type: 'TenantSchemaRegistry', id: 'PARTIAL-LIST' },
      ],
    }),

    // 4) Get single by ID
    getTenantSchemaRegistry: build.query<TenantSchemaRegistry, string>({
      query: (id) => `TenantSchemaRegistry/${id}`,
      providesTags: (result, error, id) => [{ type: 'TenantSchemaRegistry', id }],
    }),

    // 5) Update
    updateTenantSchemaRegistry: build.mutation<TenantSchemaRegistry, Pick<TenantSchemaRegistry, 'id'> & Partial<TenantSchemaRegistry>>({
      query: ({ id, ...patch }) => ({
        url: `TenantSchemaRegistry/${id}`,
        method: 'PUT',
        body: patch,
      }),
      invalidatesTags: (result, error, { id }: Pick<TenantSchemaRegistry, 'id'>) => [
        { type: 'TenantSchemaRegistry', id },
        { type: 'TenantSchemaRegistry', id: 'LIST' },
        { type: 'TenantSchemaRegistry', id: 'PARTIAL-LIST' },
      ],
    }),

    // 6) Delete
    deleteTenantSchemaRegistry: build.mutation<{ success: boolean; id: string }, number>({
      query(id) {
        return {
          url: `TenantSchemaRegistry/${id}`,
          method: 'DELETE',
        }
      },
      invalidatesTags: (result, error, id) => [
        { type: 'TenantSchemaRegistry', id },
        { type: 'TenantSchemaRegistry', id: 'LIST' },
        { type: 'TenantSchemaRegistry', id: 'PARTIAL-LIST' },
      ],
    }),

    // 7) Cascade / soft-delete (marks trashed, cascades children)
    deleteTenantSchemaRegistryCascade: build.mutation<{ success: boolean; id: string }, { id: string; cascade?: boolean; trash?: boolean }>({
      query({ id, cascade = true, trash = true }) {
        const params = [`cascade=${cascade}`, `trash=${trash}`].join('&');
        return {
          url: `TenantSchemaRegistry/${id}?${params}`,
          method: 'DELETE',
        }
      },
      invalidatesTags: (result, error, { id }) => [
        { type: 'TenantSchemaRegistry', id },
        { type: 'TenantSchemaRegistry', id: 'LIST' },
        { type: 'TenantSchemaRegistry', id: 'PARTIAL-LIST' },
      ],
    }),
  }),
})

// Notice we now also export `useLazyGetTenantSchemaRegistrysPagedQuery`
export const {
  useGetTenantSchemaRegistrysPagedQuery,     // immediate fetch
  useLazyGetTenantSchemaRegistrysPagedQuery, // lazy fetch
  useGetTenantSchemaRegistryQuery,
  useGetTenantSchemaRegistrysQuery,
  useAddTenantSchemaRegistryMutation,
  useUpdateTenantSchemaRegistryMutation,
  useDeleteTenantSchemaRegistryMutation,
  useDeleteTenantSchemaRegistryCascadeMutation,
} = TenantSchemaRegistryService
