// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelService.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createApi } from "@reduxjs/toolkit/query/react";
import { TrustObjectKeyEnvelope } from "@thorapi/model/TrustObjectKeyEnvelope";
import customBaseQuery from "../customBaseQuery"; // Import the custom base query

type TrustObjectKeyEnvelopeResponse = TrustObjectKeyEnvelope[];

const toTrustObjectKeyEnvelopeList = (
  result: unknown,
): TrustObjectKeyEnvelopeResponse => {
  if (Array.isArray(result)) {
    return result as TrustObjectKeyEnvelopeResponse;
  }

  const candidate =
    (result as any)?.content ??
    (result as any)?.items ??
    (result as any)?.results ??
    (result as any)?.data;
  return Array.isArray(candidate)
    ? (candidate as TrustObjectKeyEnvelopeResponse)
    : [];
};

export const TrustObjectKeyEnvelopeService = createApi({
  reducerPath: "TrustObjectKeyEnvelope", // This should remain unique
  baseQuery: customBaseQuery,
  tagTypes: ["TrustObjectKeyEnvelope"],
  endpoints: (build) => ({
    // 1) Paged Query Endpoint
    // Standardized pagination: page (0-based), size (page size)
    getTrustObjectKeyEnvelopesPaged: build.query<
      TrustObjectKeyEnvelopeResponse,
      { page: number; size?: number; example?: Partial<TrustObjectKeyEnvelope> }
    >({
      query: ({ page, size = 20, example }) => {
        const q: string[] = [`page=${page}`, `size=${size}`];
        if (example)
          q.push(`example=${encodeURIComponent(JSON.stringify(example))}`);
        return `TrustObjectKeyEnvelope?${q.join("&")}`;
      },
      providesTags: (result, error, { page }) => {
        const rows = toTrustObjectKeyEnvelopeList(result);
        return [
          ...rows
            .filter((row) => row?.id != null)
            .map(({ id }) => ({ type: "TrustObjectKeyEnvelope" as const, id })),
          { type: "TrustObjectKeyEnvelope", id: `PAGE_${page}` },
        ];
      },
    }),

    // 2) Simple "get all" Query (optional)
    getTrustObjectKeyEnvelopes: build.query<
      TrustObjectKeyEnvelopeResponse,
      { example?: Partial<TrustObjectKeyEnvelope> } | void
    >({
      query: (arg) => {
        if (arg && (arg as any).example) {
          const ex = (arg as any).example;
          return `TrustObjectKeyEnvelope?example=${encodeURIComponent(JSON.stringify(ex))}`;
        }
        return `TrustObjectKeyEnvelope`;
      },
      providesTags: (result) => {
        const rows = toTrustObjectKeyEnvelopeList(result);
        return [
          ...rows
            .filter((row) => row?.id != null)
            .map(({ id }) => ({ type: "TrustObjectKeyEnvelope" as const, id })),
          { type: "TrustObjectKeyEnvelope", id: "LIST" },
        ];
      },
    }),

    // 3) Create
    addTrustObjectKeyEnvelope: build.mutation<
      TrustObjectKeyEnvelope,
      Partial<TrustObjectKeyEnvelope>
    >({
      query: (body) => ({
        url: `TrustObjectKeyEnvelope`,
        method: "POST",
        body,
      }),
      invalidatesTags: [{ type: "TrustObjectKeyEnvelope", id: "LIST" }],
    }),

    // 4) Get single by ID
    getTrustObjectKeyEnvelope: build.query<TrustObjectKeyEnvelope, string>({
      query: (id) => `TrustObjectKeyEnvelope/${id}`,
      providesTags: (result, error, id) => [
        { type: "TrustObjectKeyEnvelope", id },
      ],
    }),

    // 5) Update
    updateTrustObjectKeyEnvelope: build.mutation<
      void,
      Pick<TrustObjectKeyEnvelope, "id"> & Partial<TrustObjectKeyEnvelope>
    >({
      query: ({ id, ...patch }) => ({
        url: `TrustObjectKeyEnvelope/${id}`,
        method: "PUT",
        body: patch,
      }),
      async onQueryStarted({ id, ...patch }, { dispatch, queryFulfilled }) {
        if (id) {
          const patchResult = dispatch(
            TrustObjectKeyEnvelopeService.util.updateQueryData(
              "getTrustObjectKeyEnvelope",
              id,
              (draft) => {
                Object.assign(draft, patch);
              },
            ),
          );
          try {
            await queryFulfilled;
          } catch {
            patchResult.undo();
          }
        }
      },
      invalidatesTags: (
        result,
        error,
        { id }: Pick<TrustObjectKeyEnvelope, "id">,
      ) => [
        { type: "TrustObjectKeyEnvelope", id },
        { type: "TrustObjectKeyEnvelope", id: "LIST" },
      ],
    }),

    // 6) Delete
    deleteTrustObjectKeyEnvelope: build.mutation<
      { success: boolean; id: string },
      number
    >({
      query(id) {
        return {
          url: `TrustObjectKeyEnvelope/${id}`,
          method: "DELETE",
        };
      },
      invalidatesTags: (result, error, id) => [
        { type: "TrustObjectKeyEnvelope", id },
      ],
    }),

    // 7) Cascade / soft-delete (marks trashed, cascades children)
    deleteTrustObjectKeyEnvelopeCascade: build.mutation<
      { success: boolean; id: string },
      { id: string; cascade?: boolean; trash?: boolean }
    >({
      query({ id, cascade = true, trash = true }) {
        const params = [`cascade=${cascade}`, `trash=${trash}`].join("&");
        return {
          url: `TrustObjectKeyEnvelope/${id}?${params}`,
          method: "DELETE",
        };
      },
      invalidatesTags: (result, error, { id }) => [
        { type: "TrustObjectKeyEnvelope", id },
        { type: "TrustObjectKeyEnvelope", id: "LIST" },
      ],
    }),
  }),
});

// Notice we now also export `useLazyGetTrustObjectKeyEnvelopesPagedQuery`
export const {
  useGetTrustObjectKeyEnvelopesPagedQuery, // immediate fetch
  useLazyGetTrustObjectKeyEnvelopesPagedQuery, // lazy fetch
  useGetTrustObjectKeyEnvelopeQuery,
  useGetTrustObjectKeyEnvelopesQuery,
  useAddTrustObjectKeyEnvelopeMutation,
  useUpdateTrustObjectKeyEnvelopeMutation,
  useDeleteTrustObjectKeyEnvelopeMutation,
  useDeleteTrustObjectKeyEnvelopeCascadeMutation,
} = TrustObjectKeyEnvelopeService;
