/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi

Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelChart.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description: StartTrustExecutionResponse

  @author John McMahon ~ github: SpaceGhost69 | twitter: @TechnoCharms
  @see https://valkyrlabs.com/docs

*/
import React, { useState, useEffect, useRef } from "react";
import { DataObject, StartTrustExecutionResponse } from "@thorapi/model";
import {
  useGetStartTrustExecutionResponsesQuery,
  useAddStartTrustExecutionResponseMutation,
  useUpdateStartTrustExecutionResponseMutation,
} from "../../services/StartTrustExecutionResponseService";
import TimeSeriesChart from "@valkyr/component-library/Charts/TimeSeriesChart";
import LoadingSpinner from "@valkyr/component-library/LoadingSpinner";

const fieldSkipList = [
  "keyHash",
  "workflowStateId",
  "createdDate",
  "lastAccessedById",
  "lastAccessedDate",
  "lastModifiedDate",
  "lastModifiedById",
];

const StartTrustExecutionResponseChart: React.FC = () => {
  const { data: initialData = [], isLoading } =
    useGetStartTrustExecutionResponsesQuery();

  const [data, setData] = useState<StartTrustExecutionResponse[]>([]); // Array to hold table data
  const [chartData, setChartData] = useState<
    Partial<StartTrustExecutionResponse>
  >({});

  const [showAllFields, setShowAllFields] = useState(false);

  useEffect(() => {
    if (initialData) {
      setData(initialData);
    }
  }, [initialData]);

  const handleInputChange = (field: string, value: any) => {
    setChartData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const renderValue = (value: any) => {
    if (value === null || value === undefined) {
      return "";
    }
    if (typeof value === "object") {
      return JSON.stringify(value, null, 2);
    }
    return value;
  };

  return (
    <>
      {isLoading ? (
        <LoadingSpinner />
      ) : (
        <TimeSeriesChart
          data={data.flatMap((starttrustexecutionresponse: DataObject) => [
            starttrustexecutionresponse,
          ])}
        />
      )}
    </>
  );
};

export default StartTrustExecutionResponseChart;
