// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelService.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createApi } from '@reduxjs/toolkit/query/react'
import { Mcp } from '@thorapi/model/Mcp'
import customBaseQuery from '../customBaseQuery'; // Import the custom base query

type McpResponse = Mcp[]
type McpPagedQueryArg = {
  page: number
  size?: number
  example?: Partial<Mcp>
  /**
   * Cache discriminator only. Do not send this to ThorAPI; callers pass the
   * authenticated principal id/username so RBAC-filtered pages cannot be
   * reused across login boundaries by RTK Query.
   */
  authSessionKey?: string
}

type McpListQueryArg = {
  example?: Partial<Mcp>
  /**
   * Cache discriminator only. Do not send this to ThorAPI.
   */
  authSessionKey?: string
}

const toMcpList = (result: unknown): McpResponse => {
  if (Array.isArray(result)) {
    return result as McpResponse
  }

  const candidate = (result as any)?.content ?? (result as any)?.items ?? (result as any)?.results ?? (result as any)?.data
  return Array.isArray(candidate) ? (candidate as McpResponse) : []
}

export const McpService = createApi({
  reducerPath: 'Mcp', // This should remain unique
  baseQuery: customBaseQuery,
  tagTypes: ['Mcp'],
  endpoints: (build) => ({
    // 1) Paged Query Endpoint
    // Standardized pagination: page (0-based), size (page size)
    getMcpsPaged: build.query<McpResponse, McpPagedQueryArg>({
      query: ({ page, size = 20, example }) => {
        const q: string[] = [`page=${page}`, `size=${size}`];
        if (example) q.push(`example=${encodeURIComponent(JSON.stringify(example))}`);
        return `Mcp?${q.join('&')}`;
      },
      providesTags: (result, error, { page }) => {
        const rows = toMcpList(result)
        return [
          ...rows
            .filter((row) => row?.id != null)
            .map(({ id }) => ({ type: 'Mcp' as const, id })),
          { type: 'Mcp', id: `PAGE_${page}` },
          { type: 'Mcp', id: 'PARTIAL-LIST' },
        ]
      },
    }),

    // 2) Simple "get all" Query (optional)
    getMcps: build.query<McpResponse, McpListQueryArg | void>({
      query: (arg) => {
        if (arg && (arg as any).example) {
          const ex = (arg as any).example;
          return `Mcp?example=${encodeURIComponent(JSON.stringify(ex))}`;
        }
        return `Mcp`;
      },
      providesTags: (result) => {
        const rows = toMcpList(result)
        return [
          ...rows
            .filter((row) => row?.id != null)
            .map(({ id }) => ({ type: 'Mcp' as const, id })),
          { type: 'Mcp', id: 'LIST' },
          { type: 'Mcp', id: 'PARTIAL-LIST' },
        ]
      },
    }),

    // 3) Create
    addMcp: build.mutation<Mcp, Partial<Mcp>>({
      query: (body) => ({
        url: `Mcp`,
        method: 'POST',
        body,
      }),
      invalidatesTags: [
        { type: 'Mcp', id: 'LIST' },
        { type: 'Mcp', id: 'PARTIAL-LIST' },
      ],
    }),

    // 4) Get single by ID
    getMcp: build.query<Mcp, string>({
      query: (id) => `Mcp/${id}`,
      providesTags: (result, error, id) => [{ type: 'Mcp', id }],
    }),

    // 5) Update
    updateMcp: build.mutation<Mcp, Pick<Mcp, 'id'> & Partial<Mcp>>({
      query: ({ id, ...patch }) => ({
        url: `Mcp/${id}`,
        method: 'PUT',
        body: patch,
      }),
      invalidatesTags: (result, error, { id }: Pick<Mcp, 'id'>) => [
        { type: 'Mcp', id },
        { type: 'Mcp', id: 'LIST' },
        { type: 'Mcp', id: 'PARTIAL-LIST' },
      ],
    }),

    // 6) Delete
    deleteMcp: build.mutation<{ success: boolean; id: string }, number>({
      query(id) {
        return {
          url: `Mcp/${id}`,
          method: 'DELETE',
        }
      },
      invalidatesTags: (result, error, id) => [
        { type: 'Mcp', id },
        { type: 'Mcp', id: 'LIST' },
        { type: 'Mcp', id: 'PARTIAL-LIST' },
      ],
    }),

    // 7) Cascade / soft-delete (marks trashed, cascades children)
    deleteMcpCascade: build.mutation<{ success: boolean; id: string }, { id: string; cascade?: boolean; trash?: boolean }>({
      query({ id, cascade = true, trash = true }) {
        const params = [`cascade=${cascade}`, `trash=${trash}`].join('&');
        return {
          url: `Mcp/${id}?${params}`,
          method: 'DELETE',
        }
      },
      invalidatesTags: (result, error, { id }) => [
        { type: 'Mcp', id },
        { type: 'Mcp', id: 'LIST' },
        { type: 'Mcp', id: 'PARTIAL-LIST' },
      ],
    }),
  }),
})

// Notice we now also export `useLazyGetMcpsPagedQuery`
export const {
  useGetMcpsPagedQuery,     // immediate fetch
  useLazyGetMcpsPagedQuery, // lazy fetch
  useGetMcpQuery,
  useGetMcpsQuery,
  useAddMcpMutation,
  useUpdateMcpMutation,
  useDeleteMcpMutation,
  useDeleteMcpCascadeMutation,
} = McpService
