// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelService.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createApi } from "@reduxjs/toolkit/query/react";
import customBaseQuery from "../customBaseQuery"; // Import the custom base query
export const RequestPasswordResetResponseService = createApi({
  reducerPath: "RequestPasswordResetResponse", // This should remain unique
  baseQuery: customBaseQuery,
  tagTypes: ["RequestPasswordResetResponse"],
  endpoints: (build) => ({
    // 1) Paged Query Endpoint
    // Standardized pagination: page (0-based), size (page size)
    getRequestPasswordResetResponsesPaged: build.query({
      query: ({ page, size = 20, example }) => {
        const q = [`page=${page}`, `size=${size}`];
        if (example)
          q.push(`example=${encodeURIComponent(JSON.stringify(example))}`);
        return `RequestPasswordResetResponse?${q.join("&")}`;
      },
      providesTags: (result, error, { page }) =>
        result
          ? [
              ...result.map(({ id }) => ({
                type: "RequestPasswordResetResponse",
                id,
              })),
              { type: "RequestPasswordResetResponse", id: `PAGE_${page}` },
            ]
          : [],
    }),
    // 2) Simple "get all" Query (optional)
    getRequestPasswordResetResponses: build.query({
      query: (arg) => {
        if (arg && arg.example) {
          const ex = arg.example;
          return `RequestPasswordResetResponse?example=${encodeURIComponent(JSON.stringify(ex))}`;
        }
        return `RequestPasswordResetResponse`;
      },
      providesTags: (result) =>
        result
          ? [
              ...result.map(({ id }) => ({
                type: "RequestPasswordResetResponse",
                id,
              })),
              { type: "RequestPasswordResetResponse", id: "LIST" },
            ]
          : [{ type: "RequestPasswordResetResponse", id: "LIST" }],
    }),
    // 3) Create
    addRequestPasswordResetResponse: build.mutation({
      query: (body) => ({
        url: `RequestPasswordResetResponse`,
        method: "POST",
        body,
      }),
      invalidatesTags: [{ type: "RequestPasswordResetResponse", id: "LIST" }],
    }),
    // 4) Get single by ID
    getRequestPasswordResetResponse: build.query({
      query: (id) => `RequestPasswordResetResponse/${id}`,
      providesTags: (result, error, id) => [
        { type: "RequestPasswordResetResponse", id },
      ],
    }),
    // 5) Update
    updateRequestPasswordResetResponse: build.mutation({
      query: ({ id, ...patch }) => ({
        url: `RequestPasswordResetResponse/${id}`,
        method: "PUT",
        body: patch,
      }),
      async onQueryStarted({ id, ...patch }, { dispatch, queryFulfilled }) {
        if (id) {
          const patchResult = dispatch(
            RequestPasswordResetResponseService.util.updateQueryData(
              "getRequestPasswordResetResponse",
              id,
              (draft) => {
                Object.assign(draft, patch);
              },
            ),
          );
          try {
            await queryFulfilled;
          } catch {
            patchResult.undo();
          }
        }
      },
      invalidatesTags: (result, error, { id }) => [
        { type: "RequestPasswordResetResponse", id },
        { type: "RequestPasswordResetResponse", id: "LIST" },
      ],
    }),
    // 6) Delete
    deleteRequestPasswordResetResponse: build.mutation({
      query(id) {
        return {
          url: `RequestPasswordResetResponse/${id}`,
          method: "DELETE",
        };
      },
      invalidatesTags: (result, error, id) => [
        { type: "RequestPasswordResetResponse", id },
      ],
    }),
    // 7) Cascade / soft-delete (marks trashed, cascades children)
    deleteRequestPasswordResetResponseCascade: build.mutation({
      query({ id, cascade = true, trash = true }) {
        const params = [`cascade=${cascade}`, `trash=${trash}`].join("&");
        return {
          url: `RequestPasswordResetResponse/${id}?${params}`,
          method: "DELETE",
        };
      },
      invalidatesTags: (result, error, { id }) => [
        { type: "RequestPasswordResetResponse", id },
        { type: "RequestPasswordResetResponse", id: "LIST" },
      ],
    }),
  }),
});
// Notice we now also export `useLazyGetRequestPasswordResetResponsesPagedQuery`
export const {
  useGetRequestPasswordResetResponsesPagedQuery, // immediate fetch
  useLazyGetRequestPasswordResetResponsesPagedQuery, // lazy fetch
  useGetRequestPasswordResetResponseQuery,
  useGetRequestPasswordResetResponsesQuery,
  useAddRequestPasswordResetResponseMutation,
  useUpdateRequestPasswordResetResponseMutation,
  useDeleteRequestPasswordResetResponseMutation,
  useDeleteRequestPasswordResetResponseCascadeMutation,
} = RequestPasswordResetResponseService;
//# sourceMappingURL=RequestPasswordResetResponseService.js.map
