import { ErrorMessage, Field, Formik, FormikHelpers, FormikValues } from 'formik';
import React, { useState } from 'react';
import {
  Form as BSForm,
  Accordion,
  Col,
  Nav,
  Row,
  Spinner
} from 'react-bootstrap';
import { FaCheckCircle, FaCogs, FaRegPlusSquare, FaUserShield } from 'react-icons/fa';
import CoolButton from '../../../../components/CoolButton';
import * as Yup from 'yup';
import PermissionDialog from '../../../../components/PermissionDialog';
import { AclGrantRequest, PermissionType } from '../../types/AclTypes';


import {
  AclObjectIdentity,
} from '../../../model';

import { useAddAclObjectIdentityMutation } from '../../services/AclObjectIdentityService';

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-08-12T20:30:33.554374-07:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
ACL_OBJECT_IDENTITY stores information for each unique domain object instance in the system. Columns include the ID, a foreign key to the ACL_CLASS table, a unique identifier so we know the ACL_CLASS instance for which we provide information, the parent, a foreign key to the ACL_SID table to represent the owner of the domain object instance, and whether we allow ACL entries to inherit from any parent ACL. We have a single row for every domain object instance for which we store ACL permissions.
*/

/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */

/* -----------------------------------------------------
   YUP VALIDATION SCHEMA
   (Skip read-only fields and container types)
-------------------------------------------------------- */
const validationSchema = Yup.object().shape({
    
        objectIdClass: Yup.string()
          
          
          ,
    
        objectIdIdentity: Yup.string()
          
          
          ,
    
        parentObjectId: Yup.string()
          
          
          ,
    
        ownerSid: Yup.string()
          
          
          ,
    
        entriesInheriting: Yup.number()
          
          
          ,
    
        aclClassId: Yup.string()
          
          
          ,
    
        id: Yup.string()
          
          
          ,
    
        ownerId: Yup.string()
          
          
          ,
    
        createdDate: Yup.date()
          
          
          ,
    
        keyHash: Yup.string()
          
          
          ,
    
        lastAccessedById: Yup.string()
          
          
          ,
    
        lastAccessedDate: Yup.date()
          
          
          ,
    
        lastModifiedById: Yup.string()
          
          
          ,
    
        lastModifiedDate: Yup.date()
          
          
          ,
});

/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const AclObjectIdentityForm: React.FC = () => {
  const [addAclObjectIdentity, addAclObjectIdentityResult] = useAddAclObjectIdentityMutation();
  
  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState<string | null>(null);

  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: 'current_user', // This should come from authentication context
    permissions: {
      isOwner: true, // This should be determined by checking object ownership
      isAdmin: true, // This should come from user roles
      canGrantPermissions: true,
      permissions: [PermissionType.READ, PermissionType.WRITE, PermissionType.CREATE, PermissionType.DELETE, PermissionType.ADMINISTRATION],
    },
  };

  /* INITIAL VALUES - skip read-only fields */
  const initialValues: Partial<AclObjectIdentity> = {
          

            objectIdClass: 'com.valkyrlabs.model.Principal',





          

            objectIdIdentity: 'null',





          

            parentObjectId: 'null',





          

            ownerSid: 'null',





          



            entriesInheriting: 0,



          

            aclClassId: 'null',





          

            id: 'e6736618-fbb6-4710-b71f-49cf96087db3',





          

            ownerId: '6da5c574-ac4a-46dc-945c-29fcbbc628aa',





          






          

            keyHash: 'null',





          

            lastAccessedById: '3c9eb52b-266d-4d3e-a734-adb5cf1eb2f4',





          






          

            lastModifiedById: 'dde2b448-c563-4f7f-b829-777cbbf09f97',





          






  };

  // Permission Management Handlers
  const handleManagePermissions = (objectId: string) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };

  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };

  const handlePermissionsSave = (grants: AclGrantRequest[]) => {
    console.log('Permissions saved for new AclObjectIdentity:', grants);
    // Optionally show success message or redirect
  };

  /* SUBMIT HANDLER */
  const handleSubmit = async (values: FormikValues, { setSubmitting }: FormikHelpers<AclObjectIdentity>) => {
    try {
      console.log("AclObjectIdentity form values:", values);
      const result = await addAclObjectIdentity(values).unwrap();
      
      // If object was created successfully and has an ID, offer to set permissions
      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `AclObjectIdentity created successfully! Would you like to set permissions for this object?`
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      
      setSubmitting(false);
    } catch (error) {
      console.error('Failed to create AclObjectIdentity:', error);
      setSubmitting(false);
    }
  };

  return (
    <div>
      <Formik
        validateOnBlur={true}
        initialValues={initialValues as AclObjectIdentity}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({
          isSubmitting,
          isValid,
          errors,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit
        }) => (
          <form onSubmit={handleSubmit} className="form">
            <Accordion defaultActiveKey="1">
              {/* Debug/Dev Accordion */}
              <Accordion.Item eventKey="0">
                <Accordion.Header>
                  <FaCogs size={36} />
                </Accordion.Header>
                <Accordion.Body>
                  errors: {JSON.stringify(errors)}
                  <br />
                  touched: {JSON.stringify(touched)}
                  <br />
                  addAclObjectIdentityResult: {JSON.stringify(addAclObjectIdentityResult)}
                </Accordion.Body>
              </Accordion.Item>

              {/* Editable Fields (NON-read-only) */}
              <Accordion.Item eventKey="1">
                <Accordion.Header>
                  <FaRegPlusSquare size={36} /> Add New AclObjectIdentity
                </Accordion.Header>
                <Accordion.Body>
                    
                    <label htmlFor="objectIdClass" className="nice-form-control">
                      <b>
                        Object Id Class:
                        {touched.objectIdClass &&
                         !errors.objectIdClass && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="objectIdClass"
                            type="text"
                            className={
                              errors.objectIdClass
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="objectIdClass"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="objectIdIdentity" className="nice-form-control">
                      <b>
                        Object Id Identity:
                        {touched.objectIdIdentity &&
                         !errors.objectIdIdentity && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="objectIdIdentity"
                            type="text"
                            className={
                              errors.objectIdIdentity
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="objectIdIdentity"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="parentObjectId" className="nice-form-control">
                      <b>
                        Parent Object Id:
                        {touched.parentObjectId &&
                         !errors.parentObjectId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="parentObjectId"
                            type="text"
                            className={
                              errors.parentObjectId
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="parentObjectId"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="ownerSid" className="nice-form-control">
                      <b>
                        Owner Sid:
                        {touched.ownerSid &&
                         !errors.ownerSid && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="ownerSid"
                            type="text"
                            className={
                              errors.ownerSid
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="ownerSid"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="entriesInheriting" className="nice-form-control">
                      <b>
                        Entries Inheriting:
                        {touched.entriesInheriting &&
                         !errors.entriesInheriting && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>




                          {/* INTEGER FIELD */}
                          <Field
                            name="entriesInheriting"
                            type="text"
                            className={
                              errors.entriesInheriting
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />





                      <ErrorMessage
                        className="error"
                        name="entriesInheriting"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="aclClassId" className="nice-form-control">
                      <b>
                        Acl Class Id:
                        {touched.aclClassId &&
                         !errors.aclClassId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="aclClassId"
                            type="text"
                            className={
                              errors.aclClassId
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="aclClassId"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="id" className="nice-form-control">
                      <b>
                        Id:
                        {touched.id &&
                         !errors.id && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="id"
                            type="text"
                            className={
                              errors.id
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="id"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="ownerId" className="nice-form-control">
                      <b>
                        Owner Id:
                        {touched.ownerId &&
                         !errors.ownerId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="ownerId"
                            type="text"
                            className={
                              errors.ownerId
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="ownerId"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="createdDate" className="nice-form-control">
                      <b>
                        Created Date:
                        {touched.createdDate &&
                         !errors.createdDate && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>









                      <ErrorMessage
                        className="error"
                        name="createdDate"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="keyHash" className="nice-form-control">
                      <b>
                        Key Hash:
                        {touched.keyHash &&
                         !errors.keyHash && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="keyHash"
                            type="text"
                            className={
                              errors.keyHash
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="keyHash"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="lastAccessedById" className="nice-form-control">
                      <b>
                        Last Accessed By Id:
                        {touched.lastAccessedById &&
                         !errors.lastAccessedById && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="lastAccessedById"
                            type="text"
                            className={
                              errors.lastAccessedById
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="lastAccessedById"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="lastAccessedDate" className="nice-form-control">
                      <b>
                        Last Accessed Date:
                        {touched.lastAccessedDate &&
                         !errors.lastAccessedDate && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>









                      <ErrorMessage
                        className="error"
                        name="lastAccessedDate"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="lastModifiedById" className="nice-form-control">
                      <b>
                        Last Modified By Id:
                        {touched.lastModifiedById &&
                         !errors.lastModifiedById && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* TEXT FIELD */}
                          <Field
                            name="lastModifiedById"
                            type="text"
                            className={
                              errors.lastModifiedById
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="lastModifiedById"
                        component="span"
                      />
                    </label>
                    <br />
                    
                    <label htmlFor="lastModifiedDate" className="nice-form-control">
                      <b>
                        Last Modified Date:
                        {touched.lastModifiedDate &&
                         !errors.lastModifiedDate && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>









                      <ErrorMessage
                        className="error"
                        name="lastModifiedDate"
                        component="span"
                      />
                    </label>
                    <br />

                  {/* SUBMIT BUTTON */}
                  <CoolButton
                    variant={touched && isValid ? (isSubmitting ? 'disabled' : 'success') : 'warning'}
                    type="submit"
                  >
                    {isSubmitting && (
                      <Spinner
                        style={ { float: 'left' } }
                        as="span"
                        animation="grow"
                        variant="light"
                        aria-hidden="true"
                      />
                    )}
                    <FaCheckCircle size={30} /> Create New AclObjectIdentity
                  </CoolButton>
                </Accordion.Body>
              </Accordion.Item>

              {/* Read-Only System Fields */}
              <Accordion.Item eventKey="2">
                <Accordion.Header>System Fields (Read Only)</Accordion.Header>
                <Accordion.Body>
                  <Row>
                  </Row>
                </Accordion.Body>
              </Accordion.Item>
            </Accordion>
          </form>
        )}
      </Formik>

      {/* Permission Management Dialog */}
      {createdObjectId && (
        <PermissionDialog
          objectType="com.valkyrlabs.model.AclObjectIdentity"
          objectId={createdObjectId}
          isVisible={showPermissionDialog}
          onClose={handlePermissionDialogClose}
          onSave={handlePermissionsSave}
          currentUser={currentUser}
        />
      )}
    </div>
  );
};



/* Export the generated form */
export default AclObjectIdentityForm;

