import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { ErrorMessage, Field, Formik, } from "formik";
import { useState } from "react";
import { Form as BSForm, Accordion } from "react-bootstrap";
import LoadingSpinner from "@valkyr/component-library/LoadingSpinner";
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from "react-icons/fa";
import CoolButton from "@valkyr/component-library/CoolButton";
import * as Yup from "yup";
import { SmartField } from "@valkyr/component-library/ForeignKey/SmartField";
import { PermissionDialog } from "@valkyr/component-library/PermissionDialog";
import { PermissionType, } from "@valkyr/component-library/PermissionDialog/types";
import { useAddAgentBillingMutation } from "../../services/AgentBillingService";
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-11-16T09:57:41.565555-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
Billing configuration and tracking for an agent.
*/
/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */
const ChargingModelValidation = () => {
    return ["PER_INSTANCE", "USAGE_BASED", "FLAT_RATE"];
};
const BillingStatusValidation = () => {
    return ["ACTIVE", "SUSPENDED", "ARCHIVED"];
};
/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema) => schema.transform((val, orig) => orig === "" || orig === null ? undefined : val);
const validationSchema = Yup.object().shape({
    agentId: Yup.string(),
    organizationId: Yup.string(),
    instantiationCost: asNumber(Yup.number().typeError("instantiationCost must be a number")),
    totalCharges: asNumber(Yup.number().typeError("totalCharges must be a number")),
    chargingModel: Yup.mixed().oneOf(ChargingModelValidation(), "Invalid value for chargingModel"),
    billingStatus: Yup.mixed().oneOf(BillingStatusValidation(), "Invalid value for billingStatus"),
    lastChargeDate: Yup.date()
        .transform((value, originalValue) => {
        if (!originalValue) {
            return value;
        }
        const parsed = new Date(originalValue);
        return Number.isNaN(parsed.getTime()) ? value : parsed;
    })
        .typeError("lastChargeDate must be a valid date"),
    quotaAgents: asNumber(Yup.number().integer().typeError("quotaAgents must be a number")),
    activeAgentCount: asNumber(Yup.number().integer().typeError("activeAgentCount must be a number")),
    id: Yup.string(),
    ownerId: Yup.string(),
    createdDate: Yup.date()
        .transform((value, originalValue) => {
        if (!originalValue) {
            return value;
        }
        const parsed = new Date(originalValue);
        return Number.isNaN(parsed.getTime()) ? value : parsed;
    })
        .typeError("createdDate must be a valid date"),
    keyHash: Yup.string(),
    lastAccessedById: Yup.string(),
    lastAccessedDate: Yup.date()
        .transform((value, originalValue) => {
        if (!originalValue) {
            return value;
        }
        const parsed = new Date(originalValue);
        return Number.isNaN(parsed.getTime()) ? value : parsed;
    })
        .typeError("lastAccessedDate must be a valid date"),
    lastModifiedById: Yup.string(),
    lastModifiedDate: Yup.date()
        .transform((value, originalValue) => {
        if (!originalValue) {
            return value;
        }
        const parsed = new Date(originalValue);
        return Number.isNaN(parsed.getTime()) ? value : parsed;
    })
        .typeError("lastModifiedDate must be a valid date"),
});
/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const AgentBillingForm = () => {
    const [addAgentBilling, addAgentBillingResult] = useAddAgentBillingMutation();
    // Permission Management State
    const [showPermissionDialog, setShowPermissionDialog] = useState(false);
    const [createdObjectId, setCreatedObjectId] = useState(null);
    // Mock current user - in real implementation, this would come from auth context
    const currentUser = {
        username: "current_user",
        permissions: {
            isOwner: true,
            isAdmin: true,
            canGrantPermissions: true,
            permissions: [
                PermissionType.READ,
                PermissionType.WRITE,
                PermissionType.CREATE,
                PermissionType.DELETE,
                PermissionType.ADMINISTRATION,
            ],
        },
    };
    /* -----------------------------------------------------
       INITIAL VALUES - only NON read-only fields
    -------------------------------------------------------- */
    const initialValues = {
        agentId: "",
        organizationId: "",
        instantiationCost: 0,
        totalCharges: 0,
        chargingModel: undefined,
        billingStatus: undefined,
        lastChargeDate: new Date(),
        quotaAgents: 0,
        activeAgentCount: 0,
        id: "",
        ownerId: "",
        createdDate: new Date(),
        keyHash: "",
        lastAccessedById: "",
        lastAccessedDate: new Date(),
        lastModifiedById: "",
        lastModifiedDate: new Date(),
    };
    // Permission Management Handlers
    const handleManagePermissions = (objectId) => {
        setCreatedObjectId(objectId);
        setShowPermissionDialog(true);
    };
    const handlePermissionDialogClose = () => {
        setShowPermissionDialog(false);
        setCreatedObjectId(null);
    };
    const handlePermissionsSave = (grants) => {
        console.log("Permissions saved for new AgentBilling:", grants);
    };
    /* SUBMIT HANDLER */
    const handleSubmit = async (values, { setSubmitting }) => {
        try {
            console.log("AgentBilling form values:", values);
            // NOTE: depending on your generated endpoint, you may need { body: values }
            const result = await addAgentBilling(values).unwrap();
            if (result && result.id && currentUser.permissions.canGrantPermissions) {
                const shouldSetPermissions = window.confirm(`AgentBilling created successfully! Would you like to set permissions for this object?`);
                if (shouldSetPermissions) {
                    handleManagePermissions(result.id);
                }
            }
            setSubmitting(false);
        }
        catch (error) {
            console.error("Failed to create AgentBilling:", error);
            setSubmitting(false);
        }
    };
    return (_jsxs("div", { children: [_jsx(Formik, { validateOnBlur: true, initialValues: initialValues, validationSchema: validationSchema, onSubmit: handleSubmit, children: ({ isSubmitting, isValid, errors, values, setFieldValue, touched, setFieldTouched, handleSubmit, }) => (_jsx("form", { onSubmit: handleSubmit, className: "form", children: _jsxs(Accordion, { defaultActiveKey: "1", children: [_jsxs(Accordion.Item, { eventKey: "1", children: [_jsxs(Accordion.Header, { children: [_jsx(FaRegPlusSquare, { size: 28 }), " \u00A0 Add New AgentBilling"] }), _jsxs(Accordion.Body, { children: [_jsxs("label", { htmlFor: "agentId", className: "nice-form-control", children: [_jsxs("b", { children: ["Agent Id:", touched.agentId && !errors.agentId && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "agentId", value: values?.agentId, placeholder: "Agent Id", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "agentId", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "organizationId", className: "nice-form-control", children: [_jsxs("b", { children: ["Organization Id:", touched.organizationId && !errors.organizationId && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "organizationId", value: values?.organizationId, placeholder: "Organization Id", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "organizationId", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "instantiationCost", className: "nice-form-control", children: [_jsxs("b", { children: ["Instantiation Cost:", touched.instantiationCost &&
                                                                !errors.instantiationCost && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "instantiationCost", type: "number", step: "any", value: values.instantiationCost || "", onChange: (e) => {
                                                            setFieldTouched("instantiationCost", true);
                                                            const v = e.target.value;
                                                            setFieldValue("instantiationCost", v === "" ? undefined : Number(v));
                                                        }, className: errors.instantiationCost
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "instantiationCost", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "totalCharges", className: "nice-form-control", children: [_jsxs("b", { children: ["Total Charges:", touched.totalCharges && !errors.totalCharges && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "totalCharges", type: "number", step: "any", value: values.totalCharges || "", onChange: (e) => {
                                                            setFieldTouched("totalCharges", true);
                                                            const v = e.target.value;
                                                            setFieldValue("totalCharges", v === "" ? undefined : Number(v));
                                                        }, className: errors.totalCharges
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "totalCharges", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "chargingModel", className: "nice-form-control", children: [_jsxs("b", { children: ["Charging Model:", touched.chargingModel && !errors.chargingModel && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsxs(BSForm.Select, { name: "chargingModel", value: values.chargingModel || "", className: errors.chargingModel
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control", onChange: (e) => {
                                                            setFieldTouched("chargingModel", true);
                                                            setFieldValue("chargingModel", e.target.value || undefined);
                                                        }, children: [_jsx("option", { value: "", label: "Select Charging Model" }), _jsx(ChargingModelLookup, {})] }), _jsx(ErrorMessage, { className: "error", name: "chargingModel", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "billingStatus", className: "nice-form-control", children: [_jsxs("b", { children: ["Billing Status:", touched.billingStatus && !errors.billingStatus && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsxs(BSForm.Select, { name: "billingStatus", value: values.billingStatus || "", className: errors.billingStatus
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control", onChange: (e) => {
                                                            setFieldTouched("billingStatus", true);
                                                            setFieldValue("billingStatus", e.target.value || undefined);
                                                        }, children: [_jsx("option", { value: "", label: "Select Billing Status" }), _jsx(BillingStatusLookup, {})] }), _jsx(ErrorMessage, { className: "error", name: "billingStatus", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "lastChargeDate", className: "nice-form-control", children: [_jsxs("b", { children: ["Last Charge Date:", touched.lastChargeDate && !errors.lastChargeDate && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "lastChargeDate", type: "datetime-local", value: values.lastChargeDate
                                                            ? new Date(values.lastChargeDate)
                                                                .toISOString()
                                                                .slice(0, 16)
                                                            : "", onChange: (e) => {
                                                            setFieldTouched("lastChargeDate", true);
                                                            const v = e.target.value;
                                                            setFieldValue("lastChargeDate", v ? new Date(v).toISOString() : "");
                                                        }, className: errors.lastChargeDate
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "lastChargeDate", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "quotaAgents", className: "nice-form-control", children: [_jsxs("b", { children: ["Quota Agents:", touched.quotaAgents && !errors.quotaAgents && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "quotaAgents", type: "number", value: values.quotaAgents || "", onChange: (e) => {
                                                            setFieldTouched("quotaAgents", true);
                                                            const v = e.target.value;
                                                            setFieldValue("quotaAgents", v === "" ? undefined : Number(v));
                                                        }, className: errors.quotaAgents
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "quotaAgents", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "activeAgentCount", className: "nice-form-control", children: [_jsxs("b", { children: ["Active Agent Count:", touched.activeAgentCount && !errors.activeAgentCount && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "activeAgentCount", type: "number", value: values.activeAgentCount || "", onChange: (e) => {
                                                            setFieldTouched("activeAgentCount", true);
                                                            const v = e.target.value;
                                                            setFieldValue("activeAgentCount", v === "" ? undefined : Number(v));
                                                        }, className: errors.activeAgentCount
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "activeAgentCount", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "id", className: "nice-form-control", children: [_jsxs("b", { children: ["Id:", touched.id && !errors.id && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "id", value: values?.id, placeholder: "Id", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "id", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "ownerId", className: "nice-form-control", children: [_jsxs("b", { children: ["Owner Id:", touched.ownerId && !errors.ownerId && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "ownerId", value: values?.ownerId, placeholder: "Owner Id", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "ownerId", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "createdDate", className: "nice-form-control", children: [_jsxs("b", { children: ["Created Date:", touched.createdDate && !errors.createdDate && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "createdDate", type: "datetime-local", value: values.createdDate
                                                            ? new Date(values.createdDate)
                                                                .toISOString()
                                                                .slice(0, 16)
                                                            : "", onChange: (e) => {
                                                            setFieldTouched("createdDate", true);
                                                            const v = e.target.value;
                                                            setFieldValue("createdDate", v ? new Date(v).toISOString() : "");
                                                        }, className: errors.createdDate
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "createdDate", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "keyHash", className: "nice-form-control", children: [_jsxs("b", { children: ["Key Hash:", touched.keyHash && !errors.keyHash && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "keyHash", value: values?.keyHash, placeholder: "Key Hash", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "keyHash", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "lastAccessedById", className: "nice-form-control", children: [_jsxs("b", { children: ["Last Accessed By Id:", touched.lastAccessedById && !errors.lastAccessedById && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "lastAccessedById", value: values?.lastAccessedById, placeholder: "Last Accessed By Id", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "lastAccessedById", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "lastAccessedDate", className: "nice-form-control", children: [_jsxs("b", { children: ["Last Accessed Date:", touched.lastAccessedDate && !errors.lastAccessedDate && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "lastAccessedDate", type: "datetime-local", value: values.lastAccessedDate
                                                            ? new Date(values.lastAccessedDate)
                                                                .toISOString()
                                                                .slice(0, 16)
                                                            : "", onChange: (e) => {
                                                            setFieldTouched("lastAccessedDate", true);
                                                            const v = e.target.value;
                                                            setFieldValue("lastAccessedDate", v ? new Date(v).toISOString() : "");
                                                        }, className: errors.lastAccessedDate
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "lastAccessedDate", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "lastModifiedById", className: "nice-form-control", children: [_jsxs("b", { children: ["Last Modified By Id:", touched.lastModifiedById && !errors.lastModifiedById && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(SmartField, { name: "lastModifiedById", value: values?.lastModifiedById, placeholder: "Last Modified By Id", setFieldValue: setFieldValue, setFieldTouched: setFieldTouched }), _jsx(ErrorMessage, { className: "error", name: "lastModifiedById", component: "span" })] }), _jsx("br", {}), _jsxs("label", { htmlFor: "lastModifiedDate", className: "nice-form-control", children: [_jsxs("b", { children: ["Last Modified Date:", touched.lastModifiedDate && !errors.lastModifiedDate && (_jsxs("span", { className: "okCheck", children: [_jsx(FaCheckCircle, {}), " looks good!"] }))] }), _jsx(Field, { name: "lastModifiedDate", type: "datetime-local", value: values.lastModifiedDate
                                                            ? new Date(values.lastModifiedDate)
                                                                .toISOString()
                                                                .slice(0, 16)
                                                            : "", onChange: (e) => {
                                                            setFieldTouched("lastModifiedDate", true);
                                                            const v = e.target.value;
                                                            setFieldValue("lastModifiedDate", v ? new Date(v).toISOString() : "");
                                                        }, className: errors.lastModifiedDate
                                                            ? "form-control field-error"
                                                            : "nice-form-control form-control" }), _jsx(ErrorMessage, { className: "error", name: "lastModifiedDate", component: "span" })] }), _jsx("br", {}), _jsxs(CoolButton, { variant: isValid
                                                    ? isSubmitting
                                                        ? "disabled"
                                                        : "success"
                                                    : "warning", type: "submit", disabled: !isValid || isSubmitting, children: [isSubmitting && (_jsx("span", { style: { float: "left", minHeight: 0 }, children: _jsx(LoadingSpinner, { label: "", size: 18 }) })), _jsx(FaCheckCircle, { size: 28 }), " Create New AgentBilling"] }), addAgentBillingResult.error && (_jsx("div", { className: "error", style: { marginTop: 12 }, children: JSON.stringify("data" in addAgentBillingResult.error
                                                    ? addAgentBillingResult.error.data
                                                    : addAgentBillingResult.error) }))] })] }), _jsxs(Accordion.Item, { eventKey: "0", children: [_jsxs(Accordion.Header, { children: [_jsx(FaCogs, { size: 28 }), " \u00A0Server Messages"] }), _jsxs(Accordion.Body, { children: ["errors: ", JSON.stringify(errors), _jsx("br", {}), "addAgentBillingResult: ", JSON.stringify(addAgentBillingResult)] })] })] }) })) }), createdObjectId && (_jsx(PermissionDialog, { objectType: "com.valkyrlabs.model.AgentBilling", objectId: createdObjectId, isVisible: showPermissionDialog, onClose: handlePermissionDialogClose, onSave: handlePermissionsSave, currentUser: currentUser }))] }));
};
/*
lowercase chargingmodellookup
uppercase CHARGINGMODELLOOKUP
snakecase charging_model_lookup
pascalcase ChargingModelLookup
camelcase chargingModelLookup
kebabcase charging-model-lookup
*/
const ChargingModelLookup = () => {
    return (_jsxs(_Fragment, { children: [_jsx("option", { value: "PER_INSTANCE", label: "Per Instance" }), _jsx("option", { value: "USAGE_BASED", label: "Usage Based" }), _jsx("option", { value: "FLAT_RATE", label: "Flat Rate" })] }));
};
/*
lowercase billingstatuslookup
uppercase BILLINGSTATUSLOOKUP
snakecase billing_status_lookup
pascalcase BillingStatusLookup
camelcase billingStatusLookup
kebabcase billing-status-lookup
*/
const BillingStatusLookup = () => {
    return (_jsxs(_Fragment, { children: [_jsx("option", { value: "ACTIVE", label: "Active" }), _jsx("option", { value: "SUSPENDED", label: "Suspended" }), _jsx("option", { value: "ARCHIVED", label: "Archived" })] }));
};
/* Export the generated form */
export default AgentBillingForm;
//# sourceMappingURL=AgentBillingForm.js.map