// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import {
  ErrorMessage,
  Field,
  Formik,
  FormikHelpers,
  FormikValues,
} from "formik";
import React, { useState } from "react";
import {
  Form as BSForm,
  Accordion,
  Col,
  Row,
  Spinner,
  Alert,
} from "react-bootstrap";
import LoadingSpinner from "@valkyr/component-library/LoadingSpinner";
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from "react-icons/fa";
import CoolButton from "@valkyr/component-library/CoolButton";
import * as Yup from "yup";
import { SmartField } from "@valkyr/component-library/ForeignKey/SmartField";

import { PermissionDialog } from "@valkyr/component-library/PermissionDialog";
import {
  AclGrantRequest,
  PermissionType,
} from "@valkyr/component-library/PermissionDialog/types";

import {
  McpTool,
  McpToolCategoryEnum,
  McpToolInvocationStyleEnum,
} from "@thor/model";

import { useAddMcpToolMutation } from "../../services/McpToolService";

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
McpTool
*/

/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */
const CategoryValidation = () => {
  return [
    "cloud_platform",
    "devops",
    "security",
    "observability",
    "data_engineering",
    "ai_assistant",
    "productivity",
    "customization",
  ];
};
const InvocationStyleValidation = () => {
  return ["single_call", "conversational", "streaming", "background"];
};

/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema: Yup.NumberSchema) =>
  schema.transform((val, orig) =>
    orig === "" || orig === null ? undefined : val,
  );

const validationSchema = Yup.object().shape({
  name: Yup.string().required("name is required."),
  mcpServerId: Yup.string(),
  slug: Yup.string(),
  description: Yup.string(),
  category: Yup.mixed().oneOf(
    CategoryValidation(),
    "Invalid value for category",
  ),
  capabilities: Yup.string(),
  invocationStyle: Yup.mixed().oneOf(
    InvocationStyleValidation(),
    "Invalid value for invocationStyle",
  ),
  streamingSupported: Yup.boolean(),
  autoApprove: Yup.boolean(),
  defaultAutoApprove: Yup.boolean(),
  docsUrl: Yup.string(),
  inputSchema: Yup.string(),
  trashed: Yup.boolean(),
});

/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const McpToolForm: React.FC = () => {
  const [addMcpTool, addMcpToolResult] = useAddMcpToolMutation();
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState<string | null>(null);

  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: "current_user",
    permissions: {
      isOwner: true,
      isAdmin: true,
      canGrantPermissions: true,
      permissions: [
        PermissionType.READ,
        PermissionType.WRITE,
        PermissionType.CREATE,
        PermissionType.DELETE,
        PermissionType.ADMINISTRATION,
      ],
    },
  };

  /* -----------------------------------------------------
     INITIAL VALUES - only NON read-only fields
  -------------------------------------------------------- */
  const initialValues: Partial<McpTool> = {
    name: "",
    mcpServerId: "",
    slug: "",
    description: "",
    category: undefined,
    capabilities: "",
    invocationStyle: undefined,
    streamingSupported: false,
    autoApprove: false,
    defaultAutoApprove: false,
    docsUrl: "",
    inputSchema: "",
    trashed: false,
  };

  // Permission Management Handlers
  const handleManagePermissions = (objectId: string) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };

  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };

  const handlePermissionsSave = (grants: AclGrantRequest[]) => {
    console.log("Permissions saved for new McpTool:", grants);
  };

  /* SUBMIT HANDLER */
  const handleSubmit = async (
    values: FormikValues,
    { setSubmitting }: FormikHelpers<McpTool>,
  ) => {
    try {
      setSuccessMessage(null);
      setErrorMessage(null);
      console.log("McpTool form values:", values);

      // NOTE: depending on your generated endpoint, you may need { body: values }
      const result = await addMcpTool(values as any).unwrap();

      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `McpTool created successfully! Would you like to set permissions for this object?`,
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      setSuccessMessage("Saved successfully.");
    } catch (error) {
      console.error("Failed to create McpTool:", error);
      setErrorMessage("Failed to save. Please try again.");
    }
    setSubmitting(false);
  };

  return (
    <div>
      <Formik
        validateOnBlur={true}
        initialValues={initialValues as McpTool}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({
          isSubmitting,
          isValid,
          errors,
          values,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit,
        }) => {
          const isSaving = isSubmitting || addMcpToolResult.isLoading;
          return (
            <form onSubmit={handleSubmit} className="form">
              <Accordion defaultActiveKey="1">
                {/* Editable Fields (NON read-only) */}
                <Accordion.Item eventKey="1">
                  <Accordion.Header>
                    <FaRegPlusSquare size={28} /> &nbsp; Add New McpTool
                  </Accordion.Header>
                  <Accordion.Body>
                    <label htmlFor="name" className="nice-form-control">
                      <b>
                        Name:
                        {touched.name && !errors.name && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="name"
                        value={values?.name}
                        placeholder="Name"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="name"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="mcpServerId" className="nice-form-control">
                      <b>
                        Mcp Server Id:
                        {touched.mcpServerId && !errors.mcpServerId && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="mcpServerId"
                        value={values?.mcpServerId}
                        placeholder="Mcp Server Id"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="mcpServerId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="slug" className="nice-form-control">
                      <b>
                        Slug:
                        {touched.slug && !errors.slug && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="slug"
                        value={values?.slug}
                        placeholder="Slug"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="slug"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="description" className="nice-form-control">
                      <b>
                        Description:
                        {touched.description && !errors.description && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="description"
                        value={values?.description}
                        placeholder="Description"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="description"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="category" className="nice-form-control">
                      <b>
                        Category:
                        {touched.category && !errors.category && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* ENUM DROPDOWN */}
                      <BSForm.Select
                        name="category"
                        value={values.category || ""}
                        className={
                          errors.category
                            ? "form-control field-error"
                            : "nice-form-control form-control"
                        }
                        onChange={(e) => {
                          setFieldTouched("category", true);
                          setFieldValue(
                            "category",
                            e.target.value || undefined,
                          );
                        }}
                      >
                        <option value="" label="Select Category" />
                        <CategoryLookup />
                      </BSForm.Select>

                      <ErrorMessage
                        className="error"
                        name="category"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="capabilities" className="nice-form-control">
                      <b>
                        Capabilities:
                        {touched.capabilities && !errors.capabilities && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="capabilities"
                        value={values?.capabilities}
                        placeholder="Capabilities"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="capabilities"
                        component="span"
                      />
                    </label>
                    <br />
                    <label
                      htmlFor="invocationStyle"
                      className="nice-form-control"
                    >
                      <b>
                        Invocation Style:
                        {touched.invocationStyle && !errors.invocationStyle && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* ENUM DROPDOWN */}
                      <BSForm.Select
                        name="invocationStyle"
                        value={values.invocationStyle || ""}
                        className={
                          errors.invocationStyle
                            ? "form-control field-error"
                            : "nice-form-control form-control"
                        }
                        onChange={(e) => {
                          setFieldTouched("invocationStyle", true);
                          setFieldValue(
                            "invocationStyle",
                            e.target.value || undefined,
                          );
                        }}
                      >
                        <option value="" label="Select Invocation Style" />
                        <InvocationStyleLookup />
                      </BSForm.Select>

                      <ErrorMessage
                        className="error"
                        name="invocationStyle"
                        component="span"
                      />
                    </label>
                    <br />
                    <label
                      htmlFor="streamingSupported"
                      className="nice-form-control"
                    >
                      <b>
                        Streaming Supported:
                        {touched.streamingSupported &&
                          !errors.streamingSupported && (
                            <span className="okCheck">
                              <FaCheckCircle /> looks good!
                            </span>
                          )}
                      </b>

                      {/* CHECKBOX FIELD */}
                      <BSForm.Check
                        id="streamingSupported"
                        name="streamingSupported"
                        checked={values.streamingSupported || false}
                        onChange={(e) => {
                          setFieldTouched("streamingSupported", true);
                          setFieldValue("streamingSupported", e.target.checked);
                        }}
                        isInvalid={!!errors.streamingSupported}
                        className={errors.streamingSupported ? "error" : ""}
                      />

                      <ErrorMessage
                        className="error"
                        name="streamingSupported"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="autoApprove" className="nice-form-control">
                      <b>
                        Auto Approve:
                        {touched.autoApprove && !errors.autoApprove && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* CHECKBOX FIELD */}
                      <BSForm.Check
                        id="autoApprove"
                        name="autoApprove"
                        checked={values.autoApprove || false}
                        onChange={(e) => {
                          setFieldTouched("autoApprove", true);
                          setFieldValue("autoApprove", e.target.checked);
                        }}
                        isInvalid={!!errors.autoApprove}
                        className={errors.autoApprove ? "error" : ""}
                      />

                      <ErrorMessage
                        className="error"
                        name="autoApprove"
                        component="span"
                      />
                    </label>
                    <br />
                    <label
                      htmlFor="defaultAutoApprove"
                      className="nice-form-control"
                    >
                      <b>
                        Default Auto Approve:
                        {touched.defaultAutoApprove &&
                          !errors.defaultAutoApprove && (
                            <span className="okCheck">
                              <FaCheckCircle /> looks good!
                            </span>
                          )}
                      </b>

                      {/* CHECKBOX FIELD */}
                      <BSForm.Check
                        id="defaultAutoApprove"
                        name="defaultAutoApprove"
                        checked={values.defaultAutoApprove || false}
                        onChange={(e) => {
                          setFieldTouched("defaultAutoApprove", true);
                          setFieldValue("defaultAutoApprove", e.target.checked);
                        }}
                        isInvalid={!!errors.defaultAutoApprove}
                        className={errors.defaultAutoApprove ? "error" : ""}
                      />

                      <ErrorMessage
                        className="error"
                        name="defaultAutoApprove"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="docsUrl" className="nice-form-control">
                      <b>
                        Docs Url:
                        {touched.docsUrl && !errors.docsUrl && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="docsUrl"
                        value={values?.docsUrl}
                        placeholder="Docs Url"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="docsUrl"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="inputSchema" className="nice-form-control">
                      <b>
                        Input Schema:
                        {touched.inputSchema && !errors.inputSchema && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                      <SmartField
                        name="inputSchema"
                        value={values?.inputSchema}
                        placeholder="Input Schema"
                        setFieldValue={setFieldValue}
                        setFieldTouched={setFieldTouched}
                      />

                      <ErrorMessage
                        className="error"
                        name="inputSchema"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="trashed" className="nice-form-control">
                      <b>
                        Trashed:
                        {touched.trashed && !errors.trashed && (
                          <span className="okCheck">
                            <FaCheckCircle /> looks good!
                          </span>
                        )}
                      </b>

                      {/* CHECKBOX FIELD */}
                      <BSForm.Check
                        id="trashed"
                        name="trashed"
                        checked={values.trashed || false}
                        onChange={(e) => {
                          setFieldTouched("trashed", true);
                          setFieldValue("trashed", e.target.checked);
                        }}
                        isInvalid={!!errors.trashed}
                        className={errors.trashed ? "error" : ""}
                      />

                      <ErrorMessage
                        className="error"
                        name="trashed"
                        component="span"
                      />
                    </label>
                    <br />

                    {/* SUBMIT BUTTON */}
                    <CoolButton
                      variant={
                        isValid
                          ? isSaving
                            ? "disabled"
                            : "success"
                          : "warning"
                      }
                      type="submit"
                      disabled={!isValid || isSaving}
                    >
                      {isSaving && (
                        <span style={{ float: "left", minHeight: 0 }}>
                          <LoadingSpinner label="" size={18} />
                        </span>
                      )}
                      <FaCheckCircle size={28} /> Create New McpTool
                    </CoolButton>

                    {(addMcpToolResult.isError || errorMessage) && (
                      <Alert variant="danger" className="mt-3">
                        {errorMessage ||
                          JSON.stringify(
                            "data" in (addMcpToolResult as any).error
                              ? (addMcpToolResult as any).error.data
                              : (addMcpToolResult as any).error,
                          )}
                      </Alert>
                    )}

                    {(addMcpToolResult.isSuccess || successMessage) && (
                      <Alert variant="success" className="mt-3">
                        {successMessage || "Saved successfully."}
                      </Alert>
                    )}
                  </Accordion.Body>
                </Accordion.Item>

                {/* Debug/Dev Accordion */}
                <Accordion.Item eventKey="0">
                  <Accordion.Header>
                    <FaCogs size={28} /> &nbsp;Server Messages
                  </Accordion.Header>
                  <Accordion.Body>
                    errors: {JSON.stringify(errors)}
                    <br />
                    addMcpToolResult: {JSON.stringify(addMcpToolResult)}
                  </Accordion.Body>
                </Accordion.Item>
              </Accordion>
            </form>
          );
        }}
      </Formik>

      {/* Permission Management Dialog */}
      {createdObjectId && (
        <PermissionDialog
          objectType="com.valkyrlabs.model.McpTool"
          objectId={createdObjectId}
          isVisible={showPermissionDialog}
          onClose={handlePermissionDialogClose}
          onSave={handlePermissionsSave}
          currentUser={currentUser}
        />
      )}
    </div>
  );
};

/*
lowercase categorylookup
uppercase CATEGORYLOOKUP
snakecase category_lookup
pascalcase CategoryLookup
camelcase categoryLookup
kebabcase category-lookup
*/

const CategoryLookup = () => {
  return (
    <>
      <option value="cloud_platform" label="Cloud Platform" />
      <option value="devops" label="Devops" />
      <option value="security" label="Security" />
      <option value="observability" label="Observability" />
      <option value="data_engineering" label="Data Engineering" />
      <option value="ai_assistant" label="Ai Assistant" />
      <option value="productivity" label="Productivity" />
      <option value="customization" label="Customization" />
    </>
  );
};

/*
lowercase invocationstylelookup
uppercase INVOCATIONSTYLELOOKUP
snakecase invocation_style_lookup
pascalcase InvocationStyleLookup
camelcase invocationStyleLookup
kebabcase invocation-style-lookup
*/

const InvocationStyleLookup = () => {
  return (
    <>
      <option value="single_call" label="Single Call" />
      <option value="conversational" label="Conversational" />
      <option value="streaming" label="Streaming" />
      <option value="background" label="Background" />
    </>
  );
};

/* Export the generated form */
export default McpToolForm;
