import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { ErrorMessage, Field, Formik } from "formik";
import { useState } from "react";
import { Form as BSForm, Accordion, Alert } from "react-bootstrap";
import LoadingSpinner from "@valkyr/component-library/LoadingSpinner";
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from "react-icons/fa";
import CoolButton from "@valkyr/component-library/CoolButton";
import * as Yup from "yup";
import { SmartField } from "@valkyr/component-library/ForeignKey/SmartField";
import { PermissionDialog } from "@valkyr/component-library/PermissionDialog";
import { PermissionType } from "@valkyr/component-library/PermissionDialog/types";
import { useAddTwoFactorSecretMutation } from "../../services/TwoFactorSecretService";
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
TOTP-based 2FA secret linked to a Principal. Store securely encrypted.
*/
/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */
const AlgorithmValidation = () => {
  return ["HmacSHA1", "HmacSHA256", "HmacSHA512"];
};
/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema) =>
  schema.transform((val, orig) =>
    orig === "" || orig === null ? undefined : val,
  );
const validationSchema = Yup.object().shape({
  principalId: Yup.string().required("principalId is required."),
  secretKey: Yup.string().required("secretKey is required."),
  algorithm: Yup.mixed()
    .oneOf(AlgorithmValidation(), "Invalid value for algorithm")
    .required("algorithm is required."),
  digits: asNumber(
    Yup.number().integer().typeError("digits must be a number"),
  ).required("digits is required."),
  period: asNumber(
    Yup.number().integer().typeError("period must be a number"),
  ).required("period is required."),
  enabled: Yup.boolean(),
  trashed: Yup.boolean(),
});
/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const TwoFactorSecretForm = () => {
  const [addTwoFactorSecret, addTwoFactorSecretResult] =
    useAddTwoFactorSecretMutation();
  const [successMessage, setSuccessMessage] = useState(null);
  const [errorMessage, setErrorMessage] = useState(null);
  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState(null);
  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: "current_user",
    permissions: {
      isOwner: true,
      isAdmin: true,
      canGrantPermissions: true,
      permissions: [
        PermissionType.READ,
        PermissionType.WRITE,
        PermissionType.CREATE,
        PermissionType.DELETE,
        PermissionType.ADMINISTRATION,
      ],
    },
  };
  /* -----------------------------------------------------
       INITIAL VALUES - only NON read-only fields
    -------------------------------------------------------- */
  const initialValues = {
    principalId: "",
    secretKey: "",
    algorithm: undefined,
    digits: 0,
    period: 0,
    enabled: false,
    trashed: false,
  };
  // Permission Management Handlers
  const handleManagePermissions = (objectId) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };
  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };
  const handlePermissionsSave = (grants) => {
    console.log("Permissions saved for new TwoFactorSecret:", grants);
  };
  /* SUBMIT HANDLER */
  const handleSubmit = async (values, { setSubmitting }) => {
    try {
      setSuccessMessage(null);
      setErrorMessage(null);
      console.log("TwoFactorSecret form values:", values);
      // NOTE: depending on your generated endpoint, you may need { body: values }
      const result = await addTwoFactorSecret(values).unwrap();
      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `TwoFactorSecret created successfully! Would you like to set permissions for this object?`,
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      setSuccessMessage("Saved successfully.");
    } catch (error) {
      console.error("Failed to create TwoFactorSecret:", error);
      setErrorMessage("Failed to save. Please try again.");
    }
    setSubmitting(false);
  };
  return _jsxs("div", {
    children: [
      _jsx(Formik, {
        validateOnBlur: true,
        initialValues: initialValues,
        validationSchema: validationSchema,
        onSubmit: handleSubmit,
        children: ({
          isSubmitting,
          isValid,
          errors,
          values,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit,
        }) => {
          const isSaving = isSubmitting || addTwoFactorSecretResult.isLoading;
          return _jsx("form", {
            onSubmit: handleSubmit,
            className: "form",
            children: _jsxs(Accordion, {
              defaultActiveKey: "1",
              children: [
                _jsxs(Accordion.Item, {
                  eventKey: "1",
                  children: [
                    _jsxs(Accordion.Header, {
                      children: [
                        _jsx(FaRegPlusSquare, { size: 28 }),
                        " \u00A0 Add New TwoFactorSecret",
                      ],
                    }),
                    _jsxs(Accordion.Body, {
                      children: [
                        _jsxs("label", {
                          htmlFor: "principalId",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Principal Id:",
                                touched.principalId &&
                                  !errors.principalId &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsx(SmartField, {
                              name: "principalId",
                              value: values?.principalId,
                              placeholder: "Principal Id",
                              setFieldValue: setFieldValue,
                              setFieldTouched: setFieldTouched,
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "principalId",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs("label", {
                          htmlFor: "secretKey",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Secret Key:",
                                touched.secretKey &&
                                  !errors.secretKey &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsx(SmartField, {
                              name: "secretKey",
                              value: values?.secretKey,
                              placeholder: "Secret Key",
                              setFieldValue: setFieldValue,
                              setFieldTouched: setFieldTouched,
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "secretKey",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs("label", {
                          htmlFor: "algorithm",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Algorithm:",
                                touched.algorithm &&
                                  !errors.algorithm &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsxs(BSForm.Select, {
                              name: "algorithm",
                              value: values.algorithm || "",
                              className: errors.algorithm
                                ? "form-control field-error"
                                : "nice-form-control form-control",
                              onChange: (e) => {
                                setFieldTouched("algorithm", true);
                                setFieldValue(
                                  "algorithm",
                                  e.target.value || undefined,
                                );
                              },
                              children: [
                                _jsx("option", {
                                  value: "",
                                  label: "Select Algorithm",
                                }),
                                _jsx(AlgorithmLookup, {}),
                              ],
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "algorithm",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs("label", {
                          htmlFor: "digits",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Digits:",
                                touched.digits &&
                                  !errors.digits &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsx(Field, {
                              name: "digits",
                              type: "number",
                              value: values.digits || "",
                              onChange: (e) => {
                                setFieldTouched("digits", true);
                                const v = e.target.value;
                                setFieldValue(
                                  "digits",
                                  v === "" ? undefined : Number(v),
                                );
                              },
                              className: errors.digits
                                ? "form-control field-error"
                                : "nice-form-control form-control",
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "digits",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs("label", {
                          htmlFor: "period",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Period:",
                                touched.period &&
                                  !errors.period &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsx(Field, {
                              name: "period",
                              type: "number",
                              value: values.period || "",
                              onChange: (e) => {
                                setFieldTouched("period", true);
                                const v = e.target.value;
                                setFieldValue(
                                  "period",
                                  v === "" ? undefined : Number(v),
                                );
                              },
                              className: errors.period
                                ? "form-control field-error"
                                : "nice-form-control form-control",
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "period",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs("label", {
                          htmlFor: "enabled",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Enabled:",
                                touched.enabled &&
                                  !errors.enabled &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsx(BSForm.Check, {
                              id: "enabled",
                              name: "enabled",
                              checked: values.enabled || false,
                              onChange: (e) => {
                                setFieldTouched("enabled", true);
                                setFieldValue("enabled", e.target.checked);
                              },
                              isInvalid: !!errors.enabled,
                              className: errors.enabled ? "error" : "",
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "enabled",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs("label", {
                          htmlFor: "trashed",
                          className: "nice-form-control",
                          children: [
                            _jsxs("b", {
                              children: [
                                "Trashed:",
                                touched.trashed &&
                                  !errors.trashed &&
                                  _jsxs("span", {
                                    className: "okCheck",
                                    children: [
                                      _jsx(FaCheckCircle, {}),
                                      " looks good!",
                                    ],
                                  }),
                              ],
                            }),
                            _jsx(BSForm.Check, {
                              id: "trashed",
                              name: "trashed",
                              checked: values.trashed || false,
                              onChange: (e) => {
                                setFieldTouched("trashed", true);
                                setFieldValue("trashed", e.target.checked);
                              },
                              isInvalid: !!errors.trashed,
                              className: errors.trashed ? "error" : "",
                            }),
                            _jsx(ErrorMessage, {
                              className: "error",
                              name: "trashed",
                              component: "span",
                            }),
                          ],
                        }),
                        _jsx("br", {}),
                        _jsxs(CoolButton, {
                          variant: isValid
                            ? isSaving
                              ? "disabled"
                              : "success"
                            : "warning",
                          type: "submit",
                          disabled: !isValid || isSaving,
                          children: [
                            isSaving &&
                              _jsx("span", {
                                style: { float: "left", minHeight: 0 },
                                children: _jsx(LoadingSpinner, {
                                  label: "",
                                  size: 18,
                                }),
                              }),
                            _jsx(FaCheckCircle, { size: 28 }),
                            " Create New TwoFactorSecret",
                          ],
                        }),
                        (addTwoFactorSecretResult.isError || errorMessage) &&
                          _jsx(Alert, {
                            variant: "danger",
                            className: "mt-3",
                            children:
                              errorMessage ||
                              JSON.stringify(
                                "data" in addTwoFactorSecretResult.error
                                  ? addTwoFactorSecretResult.error.data
                                  : addTwoFactorSecretResult.error,
                              ),
                          }),
                        (addTwoFactorSecretResult.isSuccess ||
                          successMessage) &&
                          _jsx(Alert, {
                            variant: "success",
                            className: "mt-3",
                            children: successMessage || "Saved successfully.",
                          }),
                      ],
                    }),
                  ],
                }),
                _jsxs(Accordion.Item, {
                  eventKey: "0",
                  children: [
                    _jsxs(Accordion.Header, {
                      children: [
                        _jsx(FaCogs, { size: 28 }),
                        " \u00A0Server Messages",
                      ],
                    }),
                    _jsxs(Accordion.Body, {
                      children: [
                        "errors: ",
                        JSON.stringify(errors),
                        _jsx("br", {}),
                        "addTwoFactorSecretResult:",
                        " ",
                        JSON.stringify(addTwoFactorSecretResult),
                      ],
                    }),
                  ],
                }),
              ],
            }),
          });
        },
      }),
      createdObjectId &&
        _jsx(PermissionDialog, {
          objectType: "com.valkyrlabs.model.TwoFactorSecret",
          objectId: createdObjectId,
          isVisible: showPermissionDialog,
          onClose: handlePermissionDialogClose,
          onSave: handlePermissionsSave,
          currentUser: currentUser,
        }),
    ],
  });
};
/*
lowercase algorithmlookup
uppercase ALGORITHMLOOKUP
snakecase algorithm_lookup
pascalcase AlgorithmLookup
camelcase algorithmLookup
kebabcase algorithm-lookup
*/
const AlgorithmLookup = () => {
  return _jsxs(_Fragment, {
    children: [
      _jsx("option", { value: "HmacSHA1", label: "Hmac Sha 1" }),
      _jsx("option", { value: "HmacSHA256", label: "Hmac Sha 256" }),
      _jsx("option", { value: "HmacSHA512", label: "Hmac Sha 512" }),
    ],
  });
};
/* Export the generated form */
export default TwoFactorSecretForm;
//# sourceMappingURL=TwoFactorSecretForm.js.map
