/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-10-30T14:43:21.527935-07:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/apiRest.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/





import {

    ADD_CELL_REQUEST,
    FETCH_CELL_REQUEST,
    LIST_CELL_REQUEST,
    UPDATE_CELL_REQUEST,
    DELETE_CELL_REQUEST,

    addCellFailure,
    addCellSuccess,

    fetchCellFailure,
    fetchCellSuccess,
    
    listCellFailure,
    listCellSuccess,

    updateCellFailure,
    updateCellSuccess,
    
    deleteCellFailure,
    deleteCellSuccess,
    
} from '../actions/CellApiAction';

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com

Powered by Swagger Codegen: http://swagger.io

Generator version: (7.5.0)

Template file: typescript-redux-query/apiREST.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description: Cell
*/



export const CellMiddleware = ({ dispatch }) => (next) => async (action) => {
    console.log("Cell MIDDLEWARE: " + JSON.stringify(action) )
    next(action);

    switch (action.type) {
        default:
            break;
    }
};

