import type { ValorTaskBridgePayload } from "@shared/BuildMode";

export const digitalProductProBuildModePayload: ValorTaskBridgePayload = {
  taskId: "valor-task-digital-product-pro-001",
  source: "Mock",
  primaryLine: "Train the agent. Generate the app. Ship the system.",
  appBundle: {
    id: "app-bundle-digital-product-pro",
    name: "Digital Product Pro",
    version: "0.1.0",
    productLine: "Creator commerce",
    intent:
      "Sell a private digital product with checkout, fulfillment, receipts, and a customer download flow.",
    sourceSessionId: "sagechat-session-dpp-001",
    createdAt: "2026-06-21T20:15:00.000Z",
    receiptIds: ["receipt-generation-dpp-001"],
    componentBundleIds: [
      "component-bundle-storefront",
      "component-bundle-admin",
    ],
    execModuleIds: ["execmodule-digital-product-fulfillment"],
    artifacts: [
      {
        path: "apps/digital-product-pro/app-bundle.json",
        kind: "config",
        checksum: "sha256:bundle-fixture",
      },
      {
        path: "apps/digital-product-pro/src/pages/Checkout.tsx",
        kind: "editable",
      },
      {
        path: "apps/digital-product-pro/openapi/digital-product.yaml",
        kind: "editable",
      },
      {
        path: "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
        kind: "generated",
      },
      {
        path: "apps/digital-product-pro/assets/cover.png",
        kind: "asset",
      },
    ],
  },
  scope: {
    tenantId: "tenant-valkyr-demo",
    principalId: "principal-valhalla-operator",
    projectId: "project-digital-product-pro",
    workspaceRoot: "/workspace/apps/digital-product-pro",
    roles: ["Owner", "BuildOperator", "WorkflowEngineer"],
    policyRefs: [
      "policy:valhalla-build-mode",
      "policy:generated-thorapi-readonly",
      "policy:approval-required-destructive",
    ],
    ignoredPathPatterns: ["secrets/"],
  },
  componentBundles: [
    {
      id: "component-bundle-storefront",
      name: "Storefront + checkout",
      framework: "React",
      generatedBy: "Aurora",
      status: "ready",
      entrypoints: ["src/pages/ProductLanding.tsx", "src/pages/Checkout.tsx"],
      editablePaths: [
        "src/pages/Checkout.tsx",
        "src/components/ProductHero.tsx",
      ],
      generatedPaths: ["thorapi/redux/ProductService.tsx"],
      receiptIds: ["receipt-generation-dpp-001"],
    },
    {
      id: "component-bundle-admin",
      name: "Fulfillment console",
      framework: "React",
      generatedBy: "ThorAPI",
      status: "needs-review",
      entrypoints: ["src/pages/AdminFulfillment.tsx"],
      editablePaths: ["src/pages/AdminFulfillment.tsx"],
      generatedPaths: ["thorapi/model/DigitalProduct.ts"],
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
  ],
  execModules: [
    {
      id: "execmodule-digital-product-fulfillment",
      name: "digitalProduct.fulfillPurchase",
      version: "1.0.0",
      capability: "Issue a private download entitlement after a paid purchase.",
      inputSchemaRef: "schemas/digitalProduct.fulfillPurchase.input.json",
      outputSchemaRef: "schemas/digitalProduct.fulfillPurchase.output.json",
      owner: "Workflow Engineer",
      safetyLevel: "approval-required",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
  ],
  grayMatterContextPack: {
    id: "gm-context-pack-dpp-001",
    compiledAt: "2026-06-21T20:16:00.000Z",
    source: "GrayMatter retrieval receipts + App Gallery intent",
    policy: "answer-confidently",
    answerPolicy: "answer-confidently",
    retrievalStatus: "ready",
    invariantPreflightStatus: "passed",
    retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
    retrievalTraceId: "gm-trace-dpp-context-001",
    preflightReceiptId: "graymatter-preflight-dpp-001",
    memoryEntryIds: [
      "memory-entry-valhalla-prd",
      "memory-entry-rbac-invariant",
    ],
    sourceRefs: [
      "graymatter://MemoryEntry/memory-entry-valhalla-prd",
      "graymatter://MemoryEntry/memory-entry-rbac-invariant",
      "valkyr://app-gallery/sagechat-session-dpp-001",
    ],
    majorTaskRefs: [
      "cmd-compile-graymatter-context",
      "cmd-inspect-generated-artifact",
      "cmd-generate-app-bundle-diff",
      "plan-safe-edits",
      "plan-tests",
      "cmd-open-generated-preview",
      "cmd-browser-verify",
      "cmd-mcp-private-workflow-server-inspect",
      "cmd-workflow-workflow-mcp-dpp-fulfillment",
    ],
    summary:
      "Use GrayMatter as primary durable context, preserve RBAC boundaries, and keep ThorAPI generated surfaces deterministic.",
  },
  receipts: [
    {
      id: "receipt-context-dpp-001",
      kind: "context",
      title: "Compiled GrayMatter context pack",
      status: "succeeded",
      createdAt: "2026-06-21T20:16:00.000Z",
      actor: "Supervisor",
      targetRef: "gm-context-pack-dpp-001",
      summary: "Context pack compiled with invariant preflight coverage.",
    },
    {
      id: "receipt-workflow-dpp-001",
      kind: "workflow",
      title: "Prepared fulfillment workflow binding",
      status: "approved",
      createdAt: "2026-06-21T20:17:00.000Z",
      actor: "Workflow Engineer",
      targetRef: "workflow:digitalProduct.fulfillPurchase",
      summary: "Private MCP workflow tool is ready and requires approval.",
    },
    {
      id: "receipt-generation-dpp-001",
      kind: "generation",
      title: "Generated Digital Product Pro app bundle",
      status: "succeeded",
      createdAt: "2026-06-21T20:18:20.000Z",
      actor: "App Gallery",
      targetRef: "app-bundle-digital-product-pro",
      summary:
        "Generated app bundle manifest and artifact list from the SageChat session.",
    },
    {
      id: "graymatter-preflight-dpp-001",
      kind: "context",
      title: "GrayMatter invariant preflight",
      status: "succeeded",
      createdAt: "2026-06-21T20:16:30.000Z",
      actor: "GrayMatter",
      targetRef: "gm-context-pack-dpp-001",
      summary:
        "Invariant, methodology, RBAC, generated-code, and ValkyrAI context checks passed before major Build Mode tasks.",
    },
    {
      id: "receipt-checkpoint-dpp-001",
      kind: "checkpoint",
      title: "Created pre-edit rollback checkpoint",
      status: "succeeded",
      createdAt: "2026-06-21T20:18:00.000Z",
      actor: "Checkpoint Manager",
      targetRef: "checkpoint-pre-edit-dpp",
      summary: "Shadow-git checkpoint recorded before Build Mode code changes.",
    },
    {
      id: "receipt-prompt-bundle-dpp-001",
      kind: "context",
      title: "Loaded Valhalla prompt bundle",
      status: "succeeded",
      createdAt: "2026-06-21T20:18:15.000Z",
      actor: "Prompt Router",
      targetRef: "prompt-bundle-valhalla-001",
      summary:
        "Loaded locked Valkyr prompt sections for controlled Build Mode execution.",
    },
    {
      id: "receipt-prompt-bundle-security-001",
      kind: "context",
      title: "Loaded Security Auditor prompt bundle",
      status: "succeeded",
      createdAt: "2026-06-21T20:18:20.000Z",
      actor: "Prompt Router",
      targetRef: "prompt-bundle-security-001",
      summary:
        "Loaded review-required security prompt sections for RBAC, credential, and receipt audit passes.",
    },
    {
      id: "receipt-credit-estimate-dpp-001",
      kind: "credit_usage",
      title: "Estimated hosted infrastructure usage",
      status: "succeeded",
      createdAt: "2026-06-21T20:18:00.000Z",
      actor: "Credit Router",
      targetRef: "credit-estimate-dpp-001",
      summary:
        "Estimate includes provider route and hosted infrastructure usage.",
    },
    {
      id: "receipt-connector-gmail-thread-001",
      kind: "connector_data",
      title: "Authorized Gmail connector read",
      status: "succeeded",
      createdAt: "2026-06-21T20:18:45.000Z",
      actor: "Connector Broker",
      targetRef: "gmail:thread:digital-product-order",
      summary:
        "Authorized connector receipt for order-support email context without exposing message contents.",
    },
    {
      id: "receipt-connector-calendar-launch-001",
      kind: "connector_data",
      title: "Authorized Calendar connector read",
      status: "succeeded",
      createdAt: "2026-06-21T20:19:00.000Z",
      actor: "Connector Broker",
      targetRef: "google-calendar:events:digital-product-launch-window",
      summary:
        "Authorized connector receipt for launch-window calendar context without exposing event bodies.",
    },
    {
      id: "receipt-connector-tasks-launch-001",
      kind: "connector_data",
      title: "Authorized Tasks connector read",
      status: "succeeded",
      createdAt: "2026-06-21T20:19:15.000Z",
      actor: "Connector Broker",
      targetRef: "google-tasks:list:digital-product-launch",
      summary:
        "Authorized connector receipt for launch task checklist context without exposing task bodies.",
    },
  ],
  creditEstimate: {
    id: "credit-estimate-dpp-001",
    currency: "ValkyrCredits",
    estimatedCredits: 42,
    estimatedHostedInfrastructureCredits: 9,
    providerRoute: "valkyr-credits",
    receiptIds: ["receipt-credit-estimate-dpp-001"],
    assumptions: [
      "One context compile, one app diff, and one browser verification pass.",
      "Hosted infrastructure credits apply even when a BYO provider key is selected.",
    ],
  },
  creditUsageReceipts: [
    {
      id: "credit-usage-dpp-001",
      estimateId: "credit-estimate-dpp-001",
      commandId: "bootstrap-credit-estimate",
      capabilityId: "graymatter.context",
      providerRoute: "valkyr-credits",
      commandStatus: "succeeded",
      actualCredits: 0,
      providerCredits: 0,
      hostedInfrastructureCredits: 0,
      createdAt: "2026-06-21T20:18:30.000Z",
    },
  ],
  providerCredentials: [
    {
      id: "credential-ref-openai-user",
      route: "bring-your-own-key",
      displayName: "Use my API key",
      tenantScoped: true,
      secretAvailable: true,
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "credential-ref-valkyr-credits",
      route: "valkyr-credits",
      displayName: "Use Valkyr credits",
      tenantScoped: true,
      secretAvailable: false,
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "credential-ref-local",
      route: "local-model",
      displayName: "Use local model",
      tenantScoped: false,
      secretAvailable: false,
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "credential-ref-enterprise",
      route: "enterprise-proxy",
      displayName: "Use enterprise proxy",
      tenantScoped: true,
      secretAvailable: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
  ],
  selectedProviderRoute: "valkyr-credits",
  promptProfiles: [
    {
      id: "prompt-profile-valhalla",
      name: "Valhalla Build Operator",
      description: "Controlled Train -> Generate -> Ship execution loop.",
      modelFamily: "frontier",
      promptBundleRef: "prompt-bundle-valhalla-001",
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
    },
    {
      id: "prompt-profile-security-auditor",
      name: "Security Auditor",
      description:
        "RBAC, secret isolation, approval thresholds, and receipt review.",
      modelFamily: "frontier",
      promptBundleRef: "prompt-bundle-security-001",
      receiptIds: ["receipt-prompt-bundle-security-001"],
    },
  ],
  selectedPromptProfileId: "prompt-profile-valhalla",
  promptBundles: [
    {
      id: "prompt-bundle-valhalla-001",
      name: "Valhalla Build Mode Prompt Bundle",
      version: "2026.06.21",
      source: "Valkyr",
      loadedAt: "2026-06-21T20:18:15.000Z",
      policy: "locked",
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
      sections: [
        {
          id: "prompt-section-supervisor",
          title: "Supervisor doctrine",
          purpose: "Keep Train -> Generate -> Ship execution aligned.",
          sourceRef: "valkyr://prompts/valhalla/supervisor",
          checksum: "sha256:valhalla-supervisor-fixture",
        },
        {
          id: "prompt-section-toolchain",
          title: "Toolchain doctrine",
          purpose: "Use deterministic Valkyr tools before model improvisation.",
          sourceRef: "valkyr://prompts/valhalla/toolchain",
          checksum: "sha256:valhalla-toolchain-fixture",
        },
        {
          id: "prompt-section-guardrails",
          title: "Guardrail doctrine",
          purpose:
            "Preserve approvals, RBAC, credentials, receipts, and generated-code boundaries.",
          sourceRef: "valkyr://prompts/valhalla/guardrails",
          checksum: "sha256:valhalla-guardrails-fixture",
        },
      ],
    },
    {
      id: "prompt-bundle-security-001",
      name: "Security Audit Prompt Bundle",
      version: "2026.06.21",
      source: "Valkyr",
      loadedAt: "2026-06-21T20:18:15.000Z",
      policy: "review-required",
      receiptIds: ["receipt-prompt-bundle-security-001"],
      sections: [
        {
          id: "prompt-section-security-review",
          title: "Security review doctrine",
          purpose:
            "Review RBAC, approval thresholds, secret isolation, and receipt coverage.",
          sourceRef: "valkyr://prompts/security/review",
          checksum: "sha256:security-review-fixture",
        },
      ],
    },
  ],
  selectedPromptBundleId: "prompt-bundle-valhalla-001",
  mcpServers: [
    {
      id: "mcp-server-private-valkyr-workflows",
      name: "private-valkyr-workflows",
      transport: "workflow",
      status: "connected",
      scope: "tenant",
      toolIds: ["mcp-tool-digital-product-fulfill-purchase"],
      receiptIds: [
        "receipt-workflow-dpp-001",
        "build-command-receipt-mcp-server-inspect",
      ],
    },
  ],
  mcpTools: [
    {
      id: "mcp-tool-digital-product-fulfill-purchase",
      serverId: "mcp-server-private-valkyr-workflows",
      name: "digitalProduct.fulfillPurchase",
      capabilityId: "workflow.execute",
      status: "requires-approval",
      execModuleId: "execmodule-digital-product-fulfillment",
      workflowRef: "workflow:digital-product-fulfillment",
      inputSchemaRef: "schemas/digitalProduct.fulfillPurchase.input.json",
      outputSchemaRef: "schemas/digitalProduct.fulfillPurchase.output.json",
      approvalRequired: true,
      receiptIds: [
        "receipt-workflow-dpp-001",
        "build-command-receipt-mcp-server-inspect",
      ],
    },
  ],
  connectorBindings: [
    {
      id: "connector-binding-gmail-order-thread",
      connectorId: "gmail",
      connectorName: "Gmail",
      status: "authorized",
      dataClasses: ["email.thread"],
      allowedActions: ["read", "search", "get"],
      commandIds: ["cmd-connector-gmail-thread"],
      scopeRef: "tenant-valkyr-demo/principal-valhalla-operator",
      receiptIds: ["receipt-connector-gmail-thread-001"],
    },
    {
      id: "connector-binding-calendar-launch-window",
      connectorId: "google-calendar",
      connectorName: "Google Calendar",
      status: "authorized",
      dataClasses: ["calendar.events"],
      allowedActions: ["search", "list", "read"],
      commandIds: ["cmd-connector-calendar-launch-window"],
      scopeRef: "tenant-valkyr-demo/principal-valhalla-operator",
      receiptIds: ["receipt-connector-calendar-launch-001"],
    },
    {
      id: "connector-binding-tasks-launch-checklist",
      connectorId: "google-tasks",
      connectorName: "Google Tasks",
      status: "authorized",
      dataClasses: ["task.list"],
      allowedActions: ["search", "list", "read"],
      commandIds: ["cmd-connector-task-checklist"],
      scopeRef: "tenant-valkyr-demo/principal-valhalla-operator",
      receiptIds: ["receipt-connector-tasks-launch-001"],
    },
  ],
  workflowMcpBindings: [
    {
      id: "workflow-mcp-dpp-fulfillment",
      execModuleId: "execmodule-digital-product-fulfillment",
      serverName: "private-valkyr-workflows",
      toolName: "digitalProduct.fulfillPurchase",
      workflowRef: "workflow:digital-product-fulfillment",
      inputContractRef: "schemas/digitalProduct.fulfillPurchase.input.json",
      approvalRequired: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
  ],
  scheduledAutomations: [
    {
      id: "automation-nightly-fulfillment-check",
      label: "Nightly fulfillment smoke check",
      schedule: "0 7 * * *",
      workflowRef: "workflow:digital-product-fulfillment",
      commandRef: "cmd-workflow-workflow-mcp-dpp-fulfillment",
      providerRoute: "valkyr-credits",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      approvalRequired: true,
      status: "draft",
      nextRunAt: "2026-06-22T07:00:00.000Z",
      receiptIds: [],
    },
  ],
  capabilities: [
    {
      id: "filesystem.read",
      label: "Inspect workspace files",
      kind: "filesystem",
      enabled: true,
      requiresApproval: false,
      risk: "low",
      localOnly: true,
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "filesystem.write",
      label: "Apply non-generated code changes",
      kind: "filesystem",
      enabled: true,
      requiresApproval: true,
      risk: "high",
      localOnly: true,
      receiptIds: ["receipt-generation-dpp-001"],
    },
    {
      id: "psr.edit",
      label: "Precision edit tools",
      kind: "psr",
      enabled: true,
      requiresApproval: true,
      risk: "medium",
      localOnly: true,
      receiptIds: ["receipt-generation-dpp-001"],
    },
    {
      id: "terminal.execute",
      label: "Run shell commands",
      kind: "terminal",
      enabled: true,
      requiresApproval: true,
      risk: "high",
      localOnly: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "browser.automation",
      label: "Browser verification",
      kind: "browser",
      enabled: true,
      requiresApproval: true,
      risk: "medium",
      localOnly: true,
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "mcp.tool",
      label: "Run MCP tools",
      kind: "mcp",
      enabled: true,
      requiresApproval: true,
      risk: "medium",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "workflow.execute",
      label: "Run ValkyrAI workflows",
      kind: "workflow",
      enabled: true,
      requiresApproval: true,
      risk: "high",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "automation.schedule",
      label: "Schedule guarded automations",
      kind: "automation",
      enabled: true,
      requiresApproval: true,
      risk: "medium",
      localOnly: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "checkpoint.manage",
      label: "Create and restore checkpoints",
      kind: "checkpoint",
      enabled: true,
      requiresApproval: true,
      risk: "medium",
      localOnly: true,
      receiptIds: [
        "receipt-checkpoint-dpp-001",
        "build-command-receipt-checkpoint-create",
      ],
    },
    {
      id: "connector.read",
      label: "Read authorized connector data",
      kind: "connector",
      enabled: true,
      requiresApproval: true,
      risk: "medium",
      receiptIds: [
        "receipt-connector-gmail-thread-001",
        "receipt-connector-calendar-launch-001",
        "receipt-connector-tasks-launch-001",
      ],
    },
    {
      id: "graymatter.memory",
      label: "Compile GrayMatter context",
      kind: "graymatter",
      enabled: true,
      requiresApproval: false,
      risk: "medium",
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "thorapi.rest",
      label: "Use ThorAPI generated clients",
      kind: "thorapi",
      enabled: true,
      requiresApproval: false,
      risk: "medium",
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "swarm.command",
      label: "Coordinate swarm roles",
      kind: "swarm",
      enabled: true,
      requiresApproval: true,
      risk: "high",
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
    },
  ],
  guardrails: [
    {
      id: "guardrail-generated-thorapi",
      label: "Generated ThorAPI code",
      enforcement: "hard-block",
      receiptIds: ["graymatter-preflight-dpp-001"],
      summary:
        "Generated ThorAPI clients and models are inspected, not hand-edited.",
    },
    {
      id: "guardrail-destructive-ops",
      label: "Destructive or production operations",
      enforcement: "approval-required",
      receiptIds: ["receipt-workflow-dpp-001"],
      summary:
        "Deploys, destructive commands, billing mutations, email sends, and public MCP publication require explicit operator approval.",
    },
    {
      id: "guardrail-secrets",
      label: "Credential isolation",
      enforcement: "hard-block",
      receiptIds: ["graymatter-preflight-dpp-001"],
      summary:
        "Provider keys remain credential references and never appear in prompts, logs, receipts, storage, or generated frontend code.",
    },
    {
      id: "guardrail-receipts",
      label: "Receipts for proof",
      enforcement: "receipt-required",
      receiptIds: ["receipt-context-dpp-001"],
      summary:
        "File writes, shell commands, connector reads, workflow runs, browser checks, and credit usage produce auditable receipts.",
    },
    {
      id: "guardrail-checkpoints",
      label: "Rollback checkpoints",
      enforcement: "approval-required",
      receiptIds: ["receipt-checkpoint-dpp-001"],
      summary:
        "Create checkpoints before code changes and require explicit approval before restoring workspace state.",
    },
  ],
  toolPermissions: [
    {
      id: "tool-permission-filesystem-read",
      capabilityId: "filesystem.read",
      label: "Workspace read inspection",
      decision: "allow",
      approvalThreshold: "none",
      reason:
        "Read-only workspace inspection is allowed inside the scoped project root.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: false,
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "tool-permission-filesystem-write",
      capabilityId: "filesystem.write",
      label: "Guarded file writes",
      decision: "approval-required",
      approvalThreshold: "operator",
      reason:
        "Non-generated file writes require operator approval and a receipt.",
      scopeRefs: [
        "policy:valhalla-build-mode",
        "policy:generated-thorapi-readonly",
      ],
      receiptRequired: true,
      receiptIds: ["receipt-generation-dpp-001"],
    },
    {
      id: "tool-permission-psr-edit",
      capabilityId: "psr.edit",
      label: "Precision edit tools",
      decision: "approval-required",
      approvalThreshold: "operator",
      reason:
        "Precision edits require operator approval and must avoid generated ThorAPI artifacts.",
      scopeRefs: [
        "policy:valhalla-build-mode",
        "policy:generated-thorapi-readonly",
      ],
      receiptRequired: true,
      receiptIds: ["receipt-generation-dpp-001"],
    },
    {
      id: "tool-permission-terminal",
      capabilityId: "terminal.execute",
      label: "Command runner",
      decision: "approval-required",
      approvalThreshold: "operator",
      reason:
        "Shell commands require operator approval unless covered by a local allow policy.",
      scopeRefs: ["policy:approval-required-destructive"],
      receiptRequired: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "tool-permission-browser",
      capabilityId: "browser.automation",
      label: "Browser verification",
      decision: "approval-required",
      approvalThreshold: "operator",
      reason:
        "Browser checks can open previews and capture artifacts, so operator approval is required.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "tool-permission-mcp",
      capabilityId: "mcp.tool",
      label: "Private MCP tools",
      decision: "approval-required",
      approvalThreshold: "owner",
      reason:
        "Private MCP tools require owner approval before mutating tenant state.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "tool-permission-workflow",
      capabilityId: "workflow.execute",
      label: "ValkyrAI workflow execution",
      decision: "approval-required",
      approvalThreshold: "owner",
      reason:
        "ValkyrAI workflow executions require owner approval and workflow receipts before mutating tenant state.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "tool-permission-connector-read",
      capabilityId: "connector.read",
      label: "Authorized connector reads",
      decision: "approval-required",
      approvalThreshold: "owner",
      reason:
        "Connector reads require owner approval and must store only receipt metadata, not private message bodies.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: [
        "receipt-connector-gmail-thread-001",
        "receipt-connector-calendar-launch-001",
        "receipt-connector-tasks-launch-001",
      ],
    },
    {
      id: "tool-permission-automation",
      capabilityId: "automation.schedule",
      label: "Scheduled automations",
      decision: "approval-required",
      approvalThreshold: "owner",
      reason:
        "Recurring automations require owner approval before schedule creation.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "tool-permission-checkpoint",
      capabilityId: "checkpoint.manage",
      label: "Checkpoint manager",
      decision: "approval-required",
      approvalThreshold: "operator",
      reason:
        "Checkpoint creation and rollback produce rollback receipts and require operator approval.",
      scopeRefs: ["policy:approval-required-destructive"],
      receiptRequired: true,
      receiptIds: ["receipt-checkpoint-dpp-001"],
    },
    {
      id: "tool-permission-graymatter",
      capabilityId: "graymatter.memory",
      label: "GrayMatter context compile",
      decision: "allow",
      approvalThreshold: "none",
      reason:
        "GrayMatter retrieval is allowed for scoped context packs with retrieval receipts.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "tool-permission-thorapi",
      capabilityId: "thorapi.rest",
      label: "ThorAPI generated clients",
      decision: "allow",
      approvalThreshold: "none",
      reason:
        "Generated ThorAPI clients are allowed for read/use and blocked for direct edits.",
      scopeRefs: ["policy:generated-thorapi-readonly"],
      receiptRequired: true,
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "tool-permission-swarm",
      capabilityId: "swarm.command",
      label: "Swarm role coordination",
      decision: "approval-required",
      approvalThreshold: "owner",
      reason:
        "Swarm role handoffs require owner approval when they can trigger external tools.",
      scopeRefs: ["policy:valhalla-build-mode"],
      receiptRequired: true,
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
    },
  ],
  commandPolicyRules: [
    {
      id: "command-policy-local-build-loop",
      label: "Local build loop allow list",
      effect: "allow",
      pattern:
        "^(npm run (test|build)|./vaix generate thorapi|open preview|mcp:|connector:|swarm:|schedule:|checkpoint:(create|rollback)|file-read:|app-bundle-diff:|psr:|file-write:|valkyr deploy|graymatter:|report:publish)",
      reason:
        "Only local tests, builds, VAIX ThorAPI generation, browser verification, scoped file inspection, MCP workflow calls, authorized connector reads, swarm handoffs, scheduled automation drafts, checkpoint operations, safe edit tools, and approval-gated deploy drafts can enter the Build Mode command lane.",
      enabled: true,
      commandKinds: [
        "test",
        "build",
        "inspect",
        "deploy",
        "edit",
        "verify",
        "connector",
        "mcp",
        "workflow",
        "automation",
        "checkpoint",
        "swarm",
      ],
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
    },
    {
      id: "command-policy-remote-shell-bootstrap",
      label: "Remote shell bootstrap",
      effect: "deny",
      pattern: "\\b(curl|wget)\\b.*\\|\\s*(bash|sh)",
      reason: "Remote shell bootstrap commands are blocked.",
      enabled: true,
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "command-policy-valkyr-deploy",
      label: "Valkyr deploy routes",
      effect: "approval-required",
      pattern: "\\bvalkyr\\s+deploy\\b|\\bdeploy\\b",
      reason: "Valkyr deploy routes require operator approval.",
      enabled: true,
      commandKinds: ["deploy"],
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "command-policy-checkpoint-rollback",
      label: "Checkpoint rollback",
      effect: "approval-required",
      pattern: "^checkpoint:rollback",
      reason: "Checkpoint rollback requires operator approval.",
      enabled: true,
      commandKinds: ["checkpoint"],
      receiptIds: ["receipt-checkpoint-dpp-001"],
    },
  ],
  safeEditPlans: [
    {
      id: "safe-edit-checkout-copy",
      label: "Checkout copy refinement",
      summary:
        "Apply a precision edit to the editable checkout page after the pre-edit checkpoint is available.",
      tool: "psr.edit",
      status: "approval-required",
      commandId: "cmd-safe-edit-checkout-copy",
      targetPaths: ["apps/digital-product-pro/src/pages/Checkout.tsx"],
      protectedPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
      ],
      receiptIds: ["build-command-receipt-safe-edit-policy"],
    },
  ],
  checkpoints: [
    {
      id: "checkpoint-pre-edit-dpp",
      label: "Pre-edit checkpoint",
      status: "rollback-ready",
      createdAt: "2026-06-21T20:18:00.000Z",
      hash: "shadowgit:dpp-pre-edit",
      summary:
        "Workspace baseline before applying non-generated Build Mode edits.",
      commandId: "cmd-checkpoint-create",
      rollbackCommandId: "cmd-checkpoint-rollback",
      receiptIds: [
        "receipt-checkpoint-dpp-001",
        "build-command-receipt-checkpoint-create",
      ],
    },
  ],
  swarmRoles: [
    {
      role: "Supervisor",
      status: "assigned",
      owner: "ValorIDE",
      currentFocus: "Keep Train -> Generate -> Ship execution aligned.",
    },
    {
      role: "Spec Architect",
      status: "assigned",
      owner: "ValorIDE",
      currentFocus: "Validate app bundle intent and component boundaries.",
    },
    {
      role: "ThorAPI Generator",
      status: "assigned",
      owner: "ValorIDE",
      currentFocus: "Inspect generated ThorAPI surfaces and invoke VAIX launchers only.",
    },
    {
      role: "Workflow Engineer",
      status: "assigned",
      owner: "ValorIDE",
      currentFocus: "Bind private fulfillment workflow to MCP.",
    },
    {
      role: "Aurora UI Engineer",
      status: "assigned",
      owner: "ValorIDE",
      currentFocus: "Apply non-generated Aurora UI adapter changes through safe edit tools.",
    },
    {
      role: "Security Auditor",
      status: "assigned",
      owner: "ValorIDE",
      currentFocus: "Check RBAC, approval thresholds, and secret isolation.",
    },
    {
      role: "Test Runner",
      status: "idle",
      owner: "ValorIDE",
      currentFocus: "Run test/build commands after code changes.",
    },
    {
      role: "Browser Verifier",
      status: "idle",
      owner: "ValorIDE",
      currentFocus: "Open preview and collect verification evidence.",
    },
    {
      role: "Deploy Operator",
      status: "blocked",
      owner: "Human approval",
      currentFocus: "Production and public deployment remain gated.",
    },
  ],
  agentLoop: [
    {
      id: "loop-compile-context",
      label: "Compile GrayMatter context",
      status: "complete",
      capabilityIds: ["graymatter.memory"],
      receiptIds: ["receipt-context-dpp-001"],
    },
    {
      id: "loop-thorapi-vaix",
      label: "Inspect ThorAPI and VAIX surfaces",
      status: "ready",
      capabilityIds: ["thorapi.rest"],
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "loop-inspect-bundle",
      label: "Inspect app and component bundles",
      status: "complete",
      capabilityIds: ["filesystem.read", "thorapi.rest"],
      receiptIds: ["build-command-receipt-file-read-bundle"],
    },
    {
      id: "loop-checkpoint",
      label: "Create rollback checkpoint",
      status: "complete",
      capabilityIds: ["checkpoint.manage"],
      receiptIds: [
        "receipt-checkpoint-dpp-001",
        "build-command-receipt-checkpoint-create",
      ],
    },
    {
      id: "loop-edit",
      label: "Apply non-generated edits",
      status: "pending",
      capabilityIds: ["filesystem.write", "psr.edit"],
      receiptIds: [],
    },
    {
      id: "loop-run-tests",
      label: "Run tests and builds",
      status: "pending",
      capabilityIds: ["terminal.execute"],
      receiptIds: [],
    },
    {
      id: "loop-browser-verify",
      label: "Browser verify generated preview",
      status: "pending",
      capabilityIds: ["browser.automation"],
      receiptIds: [],
    },
    {
      id: "loop-run-workflow",
      label: "Run MCP workflow tool",
      status: "pending",
      capabilityIds: ["connector.read", "mcp.tool", "workflow.execute"],
      receiptIds: ["build-command-receipt-mcp-server-inspect"],
    },
    {
      id: "loop-swarm-coordinate",
      label: "Coordinate swarm role handoff",
      status: "pending",
      capabilityIds: ["swarm.command"],
      receiptIds: [],
    },
    {
      id: "loop-schedule-automation",
      label: "Schedule guarded automation",
      status: "pending",
      capabilityIds: ["automation.schedule"],
      receiptIds: [],
    },
    {
      id: "loop-draft-deploy",
      label: "Run approval-gated draft deploy",
      status: "pending",
      capabilityIds: ["terminal.execute"],
      receiptIds: [],
    },
    {
      id: "loop-final-report",
      label: "Publish final report",
      status: "pending",
      capabilityIds: ["graymatter.memory"],
      receiptIds: [],
    },
  ],
  agentRuntimes: [
    {
      id: "runtime-codex-build-operator",
      runtime: "Codex",
      label: "Codex local build operator",
      status: "selected",
      ownerRole: "Supervisor",
      promptProfileId: "prompt-profile-valhalla",
      providerRoute: "bring-your-own-key",
      loopPhaseIds: [
        "loop-inspect-bundle",
        "loop-checkpoint",
        "loop-run-tests",
      ],
      handoffPolicy: "operator-approved",
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
    },
    {
      id: "runtime-thorapi-vaix-generator",
      runtime: "ValorIDE",
      label: "ValorIDE ThorAPI and VAIX generator",
      status: "available",
      ownerRole: "ThorAPI Generator",
      promptProfileId: "prompt-profile-valhalla",
      providerRoute: "valkyr-credits",
      loopPhaseIds: ["loop-thorapi-vaix"],
      handoffPolicy: "operator-approved",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "runtime-aurora-ui-engineer",
      runtime: "Codex",
      label: "Codex Aurora UI engineer",
      status: "available",
      ownerRole: "Aurora UI Engineer",
      promptProfileId: "prompt-profile-valhalla",
      providerRoute: "bring-your-own-key",
      loopPhaseIds: ["loop-edit"],
      handoffPolicy: "operator-approved",
      receiptIds: ["receipt-prompt-bundle-dpp-001"],
    },
    {
      id: "runtime-openclaw-workflow-operator",
      runtime: "OpenClaw",
      label: "OpenClaw workflow executor",
      status: "available",
      ownerRole: "Workflow Engineer",
      promptProfileId: "prompt-profile-valhalla",
      providerRoute: "valkyr-credits",
      loopPhaseIds: [
        "loop-run-workflow",
        "loop-swarm-coordinate",
        "loop-schedule-automation",
      ],
      handoffPolicy: "supervised",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "runtime-valoride-verifier",
      runtime: "ValorIDE",
      label: "ValorIDE browser and report verifier",
      status: "available",
      ownerRole: "Browser Verifier",
      promptProfileId: "prompt-profile-security-auditor",
      providerRoute: "local-model",
      loopPhaseIds: ["loop-browser-verify", "loop-final-report"],
      handoffPolicy: "autonomous-local",
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
    {
      id: "runtime-valkyr-deploy-operator",
      runtime: "ValorIDE",
      label: "ValorIDE deploy operator",
      status: "available",
      ownerRole: "Deploy Operator",
      promptProfileId: "prompt-profile-security-auditor",
      providerRoute: "valkyr-credits",
      loopPhaseIds: ["loop-draft-deploy"],
      handoffPolicy: "operator-approved",
      receiptIds: [],
    },
  ],
  localModelRuntimes: [
    {
      id: "local-model-runtime-valoride-verifier",
      label: "Local browser/report verifier model",
      runtimeId: "runtime-valoride-verifier",
      providerCredentialId: "credential-ref-local",
      modelRef: "local://valoride-verifier/default",
      endpointRef: "workspace-local:valoride-verifier",
      status: "available",
      executionMode: "workspace-local",
      capabilityIds: ["browser.automation", "graymatter.memory"],
      healthCheckCommandId: "cmd-browser-verify",
      receiptIds: ["graymatter-preflight-dpp-001"],
    },
  ],
  thorApiVaixBindings: [
    {
      id: "thorapi-digital-product-service",
      surface: "ThorAPI",
      serviceName: "DigitalProductService",
      clientRef: "thorapi/redux/ProductService.tsx",
      operationRefs: ["getDigitalProduct", "createPurchase", "fulfillPurchase"],
      generatedPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
        "apps/digital-product-pro/thorapi/model/DigitalProduct.ts",
      ],
      editableAdapterPaths: [
        "apps/digital-product-pro/src/pages/Checkout.tsx",
        "apps/digital-product-pro/src/pages/AdminFulfillment.tsx",
      ],
      policy: "readonly-generated",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
    {
      id: "vaix-fulfillment-execution",
      surface: "VAIX",
      serviceName: "digitalProduct.fulfillPurchase",
      clientRef: "workflow:digital-product-fulfillment",
      operationRefs: [
        "validatePaidPurchase",
        "issuePrivateDownloadEntitlement",
      ],
      generatedPaths: [
        "apps/digital-product-pro/thorapi/model/DigitalProduct.ts",
      ],
      editableAdapterPaths: [
        "apps/digital-product-pro/src/pages/AdminFulfillment.tsx",
      ],
      policy: "approval-required",
      receiptIds: ["receipt-workflow-dpp-001"],
    },
  ],
  autonomyPolicy: {
    id: "autonomy-policy-valhalla-local",
    label: "Valhalla approval-gated local autonomy",
    mode: "approval-gated",
    maxConsecutiveCommands: 4,
    maxEstimatedCredits: 50,
    allowedCapabilityIds: [
      "filesystem.read",
      "thorapi.rest",
      "graymatter.memory",
      "terminal.execute",
      "browser.automation",
      "checkpoint.manage",
      "psr.edit",
      "connector.read",
      "mcp.tool",
      "workflow.execute",
      "swarm.command",
      "automation.schedule",
    ],
    approvalRequiredCapabilityIds: [
      "filesystem.write",
      "terminal.execute",
      "browser.automation",
      "checkpoint.manage",
      "psr.edit",
      "connector.read",
      "mcp.tool",
      "workflow.execute",
      "swarm.command",
      "automation.schedule",
    ],
    stopConditions: [
      "Stop when a command is rejected, fails, or requests approval.",
      "Stop before editing generated ThorAPI artifacts.",
      "Stop before production deploys, billing mutations, email sends, or public MCP publication.",
      "Stop when estimated credits exceed the configured cap.",
    ],
    escalationRefs: [
      "owner:principal-valhalla-operator",
      "policy:approval-required-destructive",
    ],
    receiptRequired: true,
    receiptIds: [
      "receipt-prompt-bundle-dpp-001",
      "graymatter-preflight-dpp-001",
    ],
  },
  autonomyDecision: {
    status: "approval-required",
    summary:
      "Operator approval is required before running Apply checkout copy edit.",
    nextStepId: "plan-safe-edits",
    nextCommandId: "cmd-safe-edit-checkout-copy",
    capabilityId: "psr.edit",
    requiredApprovalThreshold: "operator",
    commandSlotsRemaining: 4,
    estimatedCreditsRemaining: 8,
    blockingGateIds: [],
    blockingReceiptIds: [],
    reasonCodes: [
      "mode:approval-gated",
      "slots-remaining:4",
      "estimated-credits-remaining:8",
      "next-command:cmd-safe-edit-checkout-copy",
    ],
    escalationRefs: [
      "owner:principal-valhalla-operator",
      "policy:approval-required-destructive",
    ],
    updatedAt: "2026-06-21T20:20:00.000Z",
  },
  readinessGates: [
    {
      id: "gate-context-compiled",
      label: "Context compiled",
      status: "passed",
      summary:
        "GrayMatter context pack, retrieval receipt, invariant preflight, and prompt bundle are loaded.",
      requiredCapabilityIds: ["graymatter.memory"],
      requiredReceiptIds: [
        "receipt-context-dpp-001",
        "graymatter-preflight-dpp-001",
        "receipt-prompt-bundle-dpp-001",
        "build-command-receipt-context-compile",
      ],
      evidenceArtifactIds: ["artifact-graymatter-context-dpp-001"],
      commandIds: ["cmd-compile-graymatter-context"],
      blocksRun: true,
    },
    {
      id: "gate-checkpoint-ready",
      label: "Rollback checkpoint ready",
      status: "passed",
      summary: "Pre-edit checkpoint exists before mutable code work.",
      requiredCapabilityIds: ["checkpoint.manage"],
      requiredReceiptIds: ["build-command-receipt-checkpoint-create"],
      evidenceArtifactIds: ["artifact-checkpoint-dpp-001"],
      commandIds: ["cmd-checkpoint-create"],
      blocksRun: true,
    },
    {
      id: "gate-safe-edits",
      label: "Safe edits applied",
      status: "pending",
      summary:
        "Editable adapter changes must be applied through guarded edit tools.",
      requiredCapabilityIds: ["psr.edit", "filesystem.write"],
      requiredReceiptIds: [],
      evidenceArtifactIds: [],
      commandIds: ["cmd-safe-edit-checkout-copy"],
      blocksRun: true,
    },
    {
      id: "gate-thorapi-generated",
      label: "ThorAPI generated through VAIX",
      status: "pending",
      summary:
        "OpenAPI spec changes and ThorAPI regeneration must run through guarded safe edit plus ./vaix.",
      requiredCapabilityIds: ["psr.edit", "terminal.execute", "thorapi.rest"],
      requiredReceiptIds: [],
      evidenceArtifactIds: [],
      commandIds: ["cmd-openapi-update-spec", "cmd-vaix-generate-thorapi"],
      blocksRun: true,
    },
    {
      id: "gate-tests-green",
      label: "Tests and build green",
      status: "pending",
      summary: "Unit tests and build commands need successful receipts.",
      requiredCapabilityIds: ["terminal.execute"],
      requiredReceiptIds: [],
      evidenceArtifactIds: [],
      commandIds: ["cmd-test", "cmd-build"],
      blocksRun: true,
    },
    {
      id: "gate-browser-evidence",
      label: "Browser evidence captured",
      status: "pending",
      summary:
        "Generated preview must open before verification captures screenshot and console evidence.",
      requiredCapabilityIds: ["browser.automation"],
      requiredReceiptIds: [],
      evidenceArtifactIds: [],
      commandIds: ["cmd-open-generated-preview", "cmd-browser-verify"],
      blocksRun: true,
    },
    {
      id: "gate-draft-deploy-ready",
      label: "Draft deploy ready",
      status: "pending",
      summary:
        "Draft deploy requires owner approval plus test/build and browser evidence receipts.",
      requiredCapabilityIds: ["terminal.execute"],
      requiredReceiptIds: [],
      evidenceArtifactIds: [],
      commandIds: ["cmd-deploy"],
      blocksRun: true,
    },
    {
      id: "gate-workflow-ready",
      label: "Workflow binding ready",
      status: "passed",
      summary: "Private fulfillment workflow binding is available.",
      requiredCapabilityIds: ["mcp.tool", "workflow.execute"],
      requiredReceiptIds: [
        "receipt-workflow-dpp-001",
        "build-command-receipt-mcp-server-inspect",
      ],
      evidenceArtifactIds: ["artifact-mcp-server-inspect-dpp-001"],
      commandIds: ["cmd-mcp-private-workflow-server-inspect"],
      blocksRun: false,
    },
    {
      id: "gate-final-report-ready",
      label: "Final report ready",
      status: "pending",
      summary: "Final report becomes ready after gates pass with receipts.",
      requiredCapabilityIds: ["graymatter.memory"],
      requiredReceiptIds: [],
      evidenceArtifactIds: [],
      commandIds: [],
      blocksRun: false,
    },
  ],
  executionPlan: [
    {
      id: "plan-context",
      label: "Compile context and prompts",
      summary:
        "Load GrayMatter context, prompt bundles, and app intent before tool execution.",
      status: "complete",
      runtimeId: "runtime-codex-build-operator",
      commandIds: ["cmd-compile-graymatter-context"],
      readinessGateIds: ["gate-context-compiled"],
      dependencyStepIds: [],
      receiptIds: [
        "receipt-context-dpp-001",
        "receipt-prompt-bundle-dpp-001",
        "build-command-receipt-context-compile",
      ],
      nextAction: "Inspect app bundle artifacts before checkpoint validation.",
    },
    {
      id: "plan-inspect-bundle",
      label: "Inspect app bundle manifest",
      summary:
        "Read the generated app bundle manifest and inspect generated ThorAPI output as read-only evidence.",
      status: "complete",
      runtimeId: "runtime-codex-build-operator",
      commandIds: [
        "cmd-inspect-app-bundle",
        "cmd-inspect-generated-artifact",
        "cmd-generate-app-bundle-diff",
      ],
      readinessGateIds: [],
      dependencyStepIds: ["plan-context"],
      receiptIds: [
        "build-command-receipt-file-read-bundle",
        "build-command-receipt-generated-artifact-read",
        "build-command-receipt-app-bundle-diff",
      ],
      nextAction: "Proceed to checkpoint validation.",
    },
    {
      id: "plan-checkpoint",
      label: "Create rollback checkpoint",
      summary:
        "Capture rollback state before editable app adapter changes begin.",
      status: "complete",
      runtimeId: "runtime-codex-build-operator",
      commandIds: ["cmd-checkpoint-create"],
      readinessGateIds: ["gate-checkpoint-ready"],
      dependencyStepIds: ["plan-inspect-bundle"],
      receiptIds: ["build-command-receipt-checkpoint-create"],
      nextAction: "Apply safe edits after operator approval.",
    },
    {
      id: "plan-safe-edits",
      label: "Apply safe editable changes",
      summary:
        "Use precision edit tooling for non-generated checkout copy changes.",
      status: "approval-required",
      runtimeId: "runtime-aurora-ui-engineer",
      commandIds: ["cmd-safe-edit-checkout-copy"],
      readinessGateIds: ["gate-safe-edits"],
      dependencyStepIds: ["plan-checkpoint"],
      receiptIds: [],
      nextAction: "Run the checkout copy edit command.",
    },
    {
      id: "plan-thorapi-vaix",
      label: "Update OpenAPI and generate ThorAPI",
      summary:
        "Patch the editable OpenAPI spec, then invoke ./vaix generate thorapi so generated clients are never hand-edited.",
      status: "approval-required",
      runtimeId: "runtime-thorapi-vaix-generator",
      commandIds: ["cmd-openapi-update-spec", "cmd-vaix-generate-thorapi"],
      readinessGateIds: ["gate-thorapi-generated"],
      dependencyStepIds: ["plan-context"],
      receiptIds: [],
      nextAction: "Approve the OpenAPI spec update before VAIX generation.",
    },
    {
      id: "plan-tests",
      label: "Run tests and build",
      summary:
        "Run focused tests and webview build after editable changes land.",
      status: "pending",
      runtimeId: "runtime-codex-build-operator",
      commandIds: ["cmd-test", "cmd-build"],
      readinessGateIds: ["gate-tests-green"],
      dependencyStepIds: ["plan-safe-edits", "plan-thorapi-vaix"],
      receiptIds: [],
      nextAction: "Run unit tests, then build.",
    },
    {
      id: "plan-browser",
      label: "Verify in browser",
      summary:
        "Open the generated preview, then collect screenshot and console evidence.",
      status: "pending",
      runtimeId: "runtime-valoride-verifier",
      commandIds: ["cmd-open-generated-preview", "cmd-browser-verify"],
      readinessGateIds: ["gate-browser-evidence"],
      dependencyStepIds: ["plan-tests"],
      receiptIds: [],
      nextAction: "Open generated preview, then run browser verification.",
    },
    {
      id: "plan-workflow",
      label: "Run workflow and schedule automation",
      summary:
        "Validate private fulfillment workflow and draft its scheduled smoke check.",
      status: "ready",
      runtimeId: "runtime-openclaw-workflow-operator",
      commandIds: [
        "cmd-mcp-private-workflow-server-inspect",
        "cmd-workflow-workflow-mcp-dpp-fulfillment",
        "cmd-automation-automation-nightly-fulfillment-check",
      ],
      readinessGateIds: ["gate-workflow-ready"],
      dependencyStepIds: ["plan-context"],
      receiptIds: [
        "receipt-workflow-dpp-001",
        "build-command-receipt-mcp-server-inspect",
      ],
      nextAction: "Run workflow tool after owner approval.",
    },
    {
      id: "plan-deploy",
      label: "Ship draft deploy",
      summary:
        "Run the approval-gated Valkyr draft deploy after tests, browser evidence, and workflow checks are available.",
      status: "pending",
      runtimeId: "runtime-valkyr-deploy-operator",
      commandIds: ["cmd-deploy"],
      readinessGateIds: ["gate-draft-deploy-ready"],
      dependencyStepIds: ["plan-browser", "plan-workflow"],
      receiptIds: [],
      nextAction: "Approve and run the draft deploy command.",
    },
    {
      id: "plan-final-report",
      label: "Publish final report",
      summary:
        "Summarize receipts, gates, files, tests, browser evidence, and handoff gaps.",
      status: "pending",
      runtimeId: "runtime-valoride-verifier",
      commandIds: ["cmd-final-report"],
      readinessGateIds: ["gate-final-report-ready"],
      dependencyStepIds: ["plan-deploy"],
      receiptIds: [],
      nextAction: "Publish once blocking readiness gates pass.",
    },
  ],
  commands: [
    {
      id: "cmd-compile-graymatter-context",
      kind: "inspect",
      label: "Compile GrayMatter context",
      command: "graymatter:compile-context pack:gm-context-pack-dpp-001",
      capabilityId: "graymatter.memory",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Supervisor",
      executionPlanStepId: "plan-context",
      requiresApproval: false,
      status: "succeeded",
      receiptId: "build-command-receipt-context-compile",
    },
    {
      id: "cmd-inspect-app-bundle",
      kind: "inspect",
      label: "Inspect app bundle manifest",
      command: "file-read:apps/digital-product-pro/app-bundle.json",
      capabilityId: "filesystem.read",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Supervisor",
      executionPlanStepId: "plan-inspect-bundle",
      requiresApproval: false,
      status: "succeeded",
      receiptId: "build-command-receipt-file-read-bundle",
      targetPaths: ["apps/digital-product-pro/app-bundle.json"],
    },
    {
      id: "cmd-inspect-generated-artifact",
      kind: "inspect",
      label: "Inspect generated ThorAPI artifact",
      command: "file-read:apps/digital-product-pro/thorapi/redux/ProductService.tsx",
      capabilityId: "filesystem.read",
      assignedRuntimeId: "runtime-thorapi-vaix-generator",
      assignedSwarmRole: "ThorAPI Generator",
      executionPlanStepId: "plan-inspect-bundle",
      requiresApproval: false,
      status: "succeeded",
      receiptId: "build-command-receipt-generated-artifact-read",
      targetPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
      ],
      protectedPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
      ],
    },
    {
      id: "cmd-generate-app-bundle-diff",
      kind: "inspect",
      label: "Generate app bundle diff",
      command: "app-bundle-diff:app-bundle-digital-product-pro",
      capabilityId: "filesystem.read",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Spec Architect",
      executionPlanStepId: "plan-inspect-bundle",
      requiresApproval: false,
      status: "succeeded",
      receiptId: "build-command-receipt-app-bundle-diff",
      targetPaths: ["apps/digital-product-pro/app-bundle.json"],
    },
    {
      id: "cmd-test",
      kind: "test",
      label: "Unit tests",
      command: "npm run test --workspace webview-ui",
      capabilityId: "terminal.execute",
      requiresApproval: false,
      status: "queued",
    },
    {
      id: "cmd-build",
      kind: "build",
      label: "Webview build",
      command: "npm run build --workspace webview-ui",
      capabilityId: "terminal.execute",
      requiresApproval: false,
      status: "queued",
    },
    {
      id: "cmd-checkpoint-create",
      kind: "checkpoint",
      label: "Create checkpoint",
      command: "checkpoint:create pre-edit digital-product-pro",
      capabilityId: "checkpoint.manage",
      requiresApproval: false,
      status: "queued",
    },
    {
      id: "cmd-checkpoint-rollback",
      kind: "checkpoint",
      label: "Rollback to pre-edit checkpoint",
      command: "checkpoint:rollback checkpoint-pre-edit-dpp",
      capabilityId: "checkpoint.manage",
      requiresApproval: true,
      status: "approval-required",
    },
    {
      id: "cmd-safe-edit-checkout-copy",
      kind: "edit",
      label: "Apply checkout copy edit",
      command:
        'psr:apps/digital-product-pro/src/pages/Checkout.tsx replace:"Download instantly" with:"Private download delivered instantly"',
      capabilityId: "psr.edit",
      requiresApproval: true,
      status: "approval-required",
      targetPaths: ["apps/digital-product-pro/src/pages/Checkout.tsx"],
      protectedPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
      ],
    },
    {
      id: "cmd-openapi-update-spec",
      kind: "edit",
      label: "Update OpenAPI purchase spec",
      command:
        'psr:apps/digital-product-pro/openapi/digital-product.yaml replace:"fulfillPurchase:" with:"fulfillPurchase:\\n  x-valkyr-workflow: workflow:digital-product-fulfillment"',
      capabilityId: "psr.edit",
      assignedRuntimeId: "runtime-thorapi-vaix-generator",
      assignedSwarmRole: "ThorAPI Generator",
      requiresApproval: true,
      status: "approval-required",
      targetPaths: ["apps/digital-product-pro/openapi/digital-product.yaml"],
      protectedPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
        "apps/digital-product-pro/thorapi/model/DigitalProduct.ts",
      ],
    },
    {
      id: "cmd-vaix-generate-thorapi",
      kind: "build",
      label: "Generate ThorAPI through VAIX",
      command: "./vaix generate thorapi --app digital-product-pro",
      capabilityId: "terminal.execute",
      assignedRuntimeId: "runtime-thorapi-vaix-generator",
      assignedSwarmRole: "ThorAPI Generator",
      requiresApproval: true,
      status: "approval-required",
      targetPaths: [
        "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
        "apps/digital-product-pro/thorapi/model/DigitalProduct.ts",
      ],
    },
    {
      id: "cmd-deploy",
      kind: "deploy",
      label: "Draft deploy",
      command: "valkyr deploy --app digital-product-pro --draft",
      capabilityId: "terminal.execute",
      requiresApproval: true,
      status: "approval-required",
    },
    {
      id: "cmd-open-generated-preview",
      kind: "verify",
      label: "Open generated preview",
      command: "open generated preview",
      capabilityId: "browser.automation",
      assignedRuntimeId: "runtime-valoride-verifier",
      assignedSwarmRole: "Browser Verifier",
      executionPlanStepId: "plan-browser",
      requiresApproval: false,
      status: "queued",
    },
    {
      id: "cmd-browser-verify",
      kind: "verify",
      label: "Browser verification",
      command: "open preview and verify checkout flow",
      capabilityId: "browser.automation",
      requiresApproval: true,
      status: "approval-required",
    },
    {
      id: "cmd-mcp-private-workflow-server-inspect",
      kind: "mcp",
      label: "Inspect private workflow MCP server",
      command:
        "mcp:private-valkyr-workflows.listTools server:private-valkyr-workflows",
      capabilityId: "mcp.tool",
      assignedRuntimeId: "runtime-openclaw-workflow-operator",
      assignedSwarmRole: "Workflow Engineer",
      executionPlanStepId: "plan-workflow",
      requiresApproval: true,
      status: "succeeded",
      receiptId: "build-command-receipt-mcp-server-inspect",
    },
    {
      id: "cmd-connector-gmail-thread",
      kind: "connector",
      label: "Read order-support Gmail thread",
      command:
        "connector:gmail.read data:email.thread query:gmail:thread:digital-product-order",
      capabilityId: "connector.read",
      assignedRuntimeId: "runtime-openclaw-workflow-operator",
      assignedSwarmRole: "Security Auditor",
      requiresApproval: true,
      status: "approval-required",
      receiptId: "receipt-connector-gmail-thread-001",
    },
    {
      id: "cmd-connector-calendar-launch-window",
      kind: "connector",
      label: "Read launch-window Calendar events",
      command:
        "connector:google-calendar.search data:calendar.events query:google-calendar:events:digital-product-launch-window",
      capabilityId: "connector.read",
      assignedRuntimeId: "runtime-openclaw-workflow-operator",
      assignedSwarmRole: "Security Auditor",
      requiresApproval: true,
      status: "approval-required",
      receiptId: "receipt-connector-calendar-launch-001",
    },
    {
      id: "cmd-connector-task-checklist",
      kind: "connector",
      label: "Read launch task checklist",
      command:
        "connector:google-tasks.search data:task.list query:google-tasks:list:digital-product-launch",
      capabilityId: "connector.read",
      assignedRuntimeId: "runtime-openclaw-workflow-operator",
      assignedSwarmRole: "Security Auditor",
      requiresApproval: true,
      status: "approval-required",
      receiptId: "receipt-connector-tasks-launch-001",
    },
    {
      id: "cmd-swarm-security-handoff",
      kind: "swarm",
      label: "Handoff to Security Auditor",
      command:
        "swarm:handoff role:Security_Auditor runtime:runtime-openclaw-workflow-operator task:rbac-secret-review",
      capabilityId: "swarm.command",
      assignedRuntimeId: "runtime-openclaw-workflow-operator",
      assignedSwarmRole: "Security Auditor",
      requiresApproval: true,
      status: "approval-required",
    },
    {
      id: "cmd-final-report",
      kind: "report",
      label: "Publish final report",
      command: "report:publish build-mode-final-report",
      capabilityId: "graymatter.memory",
      requiresApproval: false,
      status: "queued",
    },
  ],
  commandReceipts: [
    {
      id: "build-command-receipt-context-compile",
      commandId: "cmd-compile-graymatter-context",
      capabilityId: "graymatter.memory",
      status: "succeeded",
      approved: true,
      requiresApproval: false,
      summary:
        "Compile GrayMatter context compiled gm-context-pack-dpp-001 with retrieval and invariant proof.",
      createdAt: "2026-06-21T20:17:30.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "continue",
      operatorActionSummary:
        "Continue after GrayMatter context compile proof is attached to the runbook.",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Supervisor",
      executionPlanStepId: "plan-context",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-graymatter-context-dpp-001",
          kind: "graymatter_context",
          title: "GrayMatter context compile receipt",
          uri: "valoride://build-mode/commands/cmd-compile-graymatter-context/graymatter_context",
          commandId: "cmd-compile-graymatter-context",
          receiptId: "build-command-receipt-context-compile",
          summary:
            "Context pack gm-context-pack-dpp-001 compiled with retrieval receipt and invariant preflight proof.",
          metadata: {
            answerPolicy: "answer-confidently",
            byteSize: 1536,
            contentHash:
              "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
            contextPackId: "gm-context-pack-dpp-001",
            invariantPreflightStatus: "passed",
            memoryEntryCount: 2,
            preflightReceiptId: "graymatter-preflight-dpp-001",
            retrievalReceiptCount: 1,
            retrievalStatus: "ready",
            retrievalTraceId: "gm-trace-dpp-context-001",
          },
          createdAt: "2026-06-21T20:17:30.000Z",
        },
      ],
    },
    {
      id: "build-command-receipt-file-read-bundle",
      commandId: "cmd-inspect-app-bundle",
      capabilityId: "filesystem.read",
      status: "succeeded",
      approved: true,
      requiresApproval: false,
      summary:
        "Inspect app bundle manifest read apps/digital-product-pro/app-bundle.json (2048 bytes).",
      createdAt: "2026-06-21T20:18:30.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "continue",
      operatorActionSummary:
        "Continue after scoped workspace file inspection receipt.",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Supervisor",
      executionPlanStepId: "plan-inspect-bundle",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-file-read-app-bundle",
          kind: "command_stdout",
          title: "File read receipt",
          uri: "valoride://build-mode/artifacts/valor-task-digital-product-pro-001/cmd-inspect-app-bundle/file-read-command_stdout.json",
          commandId: "cmd-inspect-app-bundle",
          receiptId: "build-command-receipt-file-read-bundle",
          summary:
            "Inspect app bundle manifest read apps/digital-product-pro/app-bundle.json (2048 bytes).",
          metadata: {
            byteSize: 2048,
            contentHash:
              "sha256:0a1b2c3d4e5f67890123456789abcdef0a1b2c3d4e5f67890123456789abcdef",
            filePath: "apps/digital-product-pro/app-bundle.json",
            lineCount: 42,
            truncated: false,
          },
          createdAt: "2026-06-21T20:18:30.000Z",
        },
      ],
    },
    {
      id: "build-command-receipt-generated-artifact-read",
      commandId: "cmd-inspect-generated-artifact",
      capabilityId: "filesystem.read",
      status: "succeeded",
      approved: true,
      requiresApproval: false,
      summary:
        "Inspect generated ThorAPI artifact read apps/digital-product-pro/thorapi/redux/ProductService.tsx as protected generated output (4096 bytes).",
      createdAt: "2026-06-21T20:18:40.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "continue",
      operatorActionSummary:
        "Continue after read-only generated artifact inspection proof.",
      assignedRuntimeId: "runtime-thorapi-vaix-generator",
      assignedSwarmRole: "ThorAPI Generator",
      executionPlanStepId: "plan-inspect-bundle",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-generated-thorapi-read-dpp-001",
          kind: "command_stdout",
          title: "Generated ThorAPI artifact inspection",
          uri: "valoride://build-mode/artifacts/valor-task-digital-product-pro-001/cmd-inspect-generated-artifact/file-read-command_stdout.json",
          commandId: "cmd-inspect-generated-artifact",
          receiptId: "build-command-receipt-generated-artifact-read",
          summary:
            "Read-only inspection of protected generated ThorAPI output.",
          metadata: {
            byteSize: 4096,
            contentHash:
              "sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
            filePath:
              "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
            generated: true,
            lineCount: 128,
            protected: true,
            truncated: false,
          },
          createdAt: "2026-06-21T20:18:40.000Z",
        },
      ],
    },
    {
      id: "build-command-receipt-app-bundle-diff",
      commandId: "cmd-generate-app-bundle-diff",
      capabilityId: "filesystem.read",
      status: "succeeded",
      approved: true,
      requiresApproval: false,
      summary:
        "Generate app bundle diff generated app-bundle-diff-dpp-001 with manifest and generated artifact evidence.",
      createdAt: "2026-06-21T20:18:50.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "continue",
      operatorActionSummary:
        "Continue after app bundle diff evidence is attached to the runbook.",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Spec Architect",
      executionPlanStepId: "plan-inspect-bundle",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-app-bundle-diff-stdout-dpp-001",
          kind: "command_stdout",
          title: "App bundle diff generation stdout",
          uri: "valoride://build-mode/commands/cmd-generate-app-bundle-diff/app-bundle-diff-read",
          commandId: "cmd-generate-app-bundle-diff",
          receiptId: "build-command-receipt-app-bundle-diff",
          summary:
            "Generated app bundle diff from the Digital Product Pro app bundle manifest.",
          metadata: {
            byteSize: 640,
            contentHash:
              "sha256:fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
            filePath: "apps/digital-product-pro/app-bundle.json",
            truncated: false,
          },
          createdAt: "2026-06-21T20:18:50.000Z",
        },
        {
          id: "artifact-app-bundle-diff-dpp-001",
          kind: "app_bundle_diff",
          title: "App bundle diff receipt",
          uri: "valoride://build-mode/commands/cmd-generate-app-bundle-diff/app_bundle_diff",
          commandId: "cmd-generate-app-bundle-diff",
          receiptId: "build-command-receipt-app-bundle-diff",
          summary:
            "App bundle diff generated from manifest intent, editable adapters, and generated ThorAPI artifacts.",
          metadata: {
            addedArtifactCount: 2,
            appBundleId: "app-bundle-digital-product-pro",
            byteSize: 640,
            changedArtifactCount: 1,
            contentHash:
              "sha256:fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
            diffId: "app-bundle-diff-dpp-001",
            generatedAt: "2026-06-21T20:18:20.000Z",
            removedArtifactCount: 0,
          },
          createdAt: "2026-06-21T20:18:50.000Z",
        },
      ],
    },
    {
      id: "build-command-receipt-checkpoint-create",
      commandId: "cmd-checkpoint-create",
      capabilityId: "checkpoint.manage",
      status: "succeeded",
      approved: true,
      requiresApproval: false,
      summary: "Pre-edit rollback checkpoint created.",
      createdAt: "2026-06-21T20:18:00.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "continue",
      operatorActionSummary:
        "Continue after the rollback checkpoint proof is attached to the runbook.",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Supervisor",
      executionPlanStepId: "plan-checkpoint",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-checkpoint-dpp-001",
          kind: "checkpoint",
          title: "Pre-edit checkpoint proof",
          uri: "valoride://build-mode/checkpoints/checkpoint-pre-edit-dpp",
          commandId: "cmd-checkpoint-create",
          receiptId: "build-command-receipt-checkpoint-create",
          summary: "Shadow-git checkpoint reference for rollback.",
          metadata: {
            checkpointAction: "create",
            checkpointHash: "shadowgit:dpp-pre-edit",
            checkpointRef: "checkpoint-pre-edit-dpp",
            workspaceRoot: "/workspace/apps/digital-product-pro",
          },
          createdAt: "2026-06-21T20:18:00.000Z",
        },
      ],
    },
    {
      id: "build-command-receipt-fixture-context",
      commandId: "cmd-test",
      capabilityId: "terminal.execute",
      status: "queued",
      approved: true,
      requiresApproval: false,
      summary: "Command runner ready; no shell command has executed yet.",
      createdAt: "2026-06-21T20:19:00.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "monitor",
      operatorActionSummary:
        "Monitor the dispatched capability and merge the completion receipt before advancing the runbook.",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Supervisor",
      executionPlanStepId: "plan-tests",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-command-stdout-dpp-001",
          kind: "command_stdout",
          title: "Unit test command stdout",
          uri: "valoride://build-mode/commands/cmd-test/command_stdout",
          commandId: "cmd-test",
          receiptId: "build-command-receipt-fixture-context",
          summary:
            "Command dispatch recorded; terminal stdout proof is pending execution.",
          metadata: {
            completed: false,
          },
          createdAt: "2026-06-21T20:19:00.000Z",
        },
      ],
      scope: {
        tenantId: "tenant-valkyr-demo",
        principalId: "principal-valhalla-operator",
        projectId: "project-digital-product-pro",
        workspaceRoot: "/workspace/apps/digital-product-pro",
        roles: ["Owner", "BuildOperator", "WorkflowEngineer"],
        policyRefs: [
          "policy:valhalla-build-mode",
          "policy:generated-thorapi-readonly",
          "policy:approval-required-destructive",
        ],
      },
    },
    {
      id: "build-command-receipt-safe-edit-policy",
      commandId: "cmd-safe-edit-checkout-copy",
      capabilityId: "psr.edit",
      status: "approval-required",
      approved: false,
      requiresApproval: true,
      summary: "Checkout copy safe edit is waiting for operator approval.",
      createdAt: "2026-06-21T20:19:30.000Z",
      executionMode: "approval-gate",
      nextOperatorAction: "approve",
      operatorActionSummary:
        "Review and approve the precision edit before applying editable code changes.",
      assignedRuntimeId: "runtime-codex-build-operator",
      assignedSwarmRole: "Aurora UI Engineer",
      executionPlanStepId: "plan-safe-edits",
      policyDecision: "approval-required",
      policyReasons: ["Command declares approval required."],
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
    },
    {
      id: "build-command-receipt-open-preview-queued",
      commandId: "cmd-open-generated-preview",
      capabilityId: "browser.automation",
      status: "queued",
      approved: true,
      requiresApproval: false,
      summary: "Generated preview open command is queued for the local browser.",
      createdAt: "2026-06-21T20:19:55.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "monitor",
      operatorActionSummary:
        "Open the generated preview and merge screenshot/console artifacts when the browser reports back.",
      assignedRuntimeId: "runtime-valoride-verifier",
      assignedSwarmRole: "Browser Verifier",
      executionPlanStepId: "plan-browser",
      policyDecision: "allow",
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
    },
    {
      id: "build-command-receipt-browser-policy",
      commandId: "cmd-browser-verify",
      capabilityId: "browser.automation",
      status: "approval-required",
      approved: false,
      requiresApproval: true,
      summary: "Browser verification is waiting for local approval.",
      createdAt: "2026-06-21T20:20:00.000Z",
      executionMode: "approval-gate",
      nextOperatorAction: "approve",
      operatorActionSummary:
        "Review and approve this command with the required threshold before dispatch.",
      assignedRuntimeId: "runtime-valoride-verifier",
      assignedSwarmRole: "Browser Verifier",
      executionPlanStepId: "plan-browser",
      policyDecision: "approval-required",
      policyReasons: ["Command declares approval required."],
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
    },
    {
      id: "build-command-receipt-mcp-server-inspect",
      commandId: "cmd-mcp-private-workflow-server-inspect",
      capabilityId: "mcp.tool",
      status: "succeeded",
      approved: true,
      requiresApproval: true,
      summary:
        "Private Valkyr workflows MCP server inspected; fulfillment tool is available.",
      createdAt: "2026-06-21T20:18:55.000Z",
      executionMode: "agentic-command-bus",
      nextOperatorAction: "continue",
      operatorActionSummary:
        "Continue after private MCP server/tool availability is proved.",
      assignedRuntimeId: "runtime-openclaw-workflow-operator",
      assignedSwarmRole: "Workflow Engineer",
      executionPlanStepId: "plan-workflow",
      policyDecision: "allow",
      requiredApprovalThreshold: "owner",
      approval: {
        approved: true,
        approverPrincipalId: "principal-valhalla-operator",
        approverRoles: ["Owner", "BuildOperator", "WorkflowEngineer"],
        createdAt: "2026-06-21T20:18:50.000Z",
        reason: "Approved private MCP server inspection for workflow readiness.",
        threshold: "owner",
      },
      promptContext: {
        promptProfileId: "prompt-profile-valhalla",
        promptProfileName: "Valhalla Build Operator",
        promptBundleId: "prompt-bundle-valhalla-001",
        promptBundleVersion: "2026.06.21",
        promptBundlePolicy: "locked",
        promptBundleReceiptIds: ["receipt-prompt-bundle-dpp-001"],
      },
      grayMatterContextProof: {
        contextPackId: "gm-context-pack-dpp-001",
        answerPolicy: "answer-confidently",
        invariantPreflightStatus: "passed",
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptIds: ["retrieval-receipt-dpp-001"],
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      artifacts: [
        {
          id: "artifact-mcp-server-inspect-dpp-001",
          kind: "mcp_result",
          title: "Private workflow MCP server inspection",
          uri: "valoride://build-mode/artifacts/valor-task-digital-product-pro-001/cmd-mcp-private-workflow-server-inspect/mcp-result.json",
          commandId: "cmd-mcp-private-workflow-server-inspect",
          receiptId: "build-command-receipt-mcp-server-inspect",
          summary:
            "private-valkyr-workflows exposed digitalProduct.fulfillPurchase as a private MCP tool.",
          metadata: {
            executionId: "mcp-exec-dpp-server-inspect-001",
            resourceCount: 1,
            serverName: "private-valkyr-workflows",
            status: "succeeded",
            toolName: "listTools",
            traceId: "mcp-trace-dpp-server-inspect-001",
          },
          createdAt: "2026-06-21T20:18:55.000Z",
        },
      ],
    },
  ],
  evidenceArtifacts: [
    {
      id: "artifact-graymatter-context-dpp-001",
      kind: "graymatter_context",
      title: "GrayMatter context compile receipt",
      uri: "valoride://build-mode/commands/cmd-compile-graymatter-context/graymatter_context",
      commandId: "cmd-compile-graymatter-context",
      receiptId: "build-command-receipt-context-compile",
      summary:
        "Context pack gm-context-pack-dpp-001 compiled with retrieval receipt and invariant preflight proof.",
      metadata: {
        answerPolicy: "answer-confidently",
        byteSize: 1536,
        contentHash:
          "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
        contextPackId: "gm-context-pack-dpp-001",
        invariantPreflightStatus: "passed",
        memoryEntryCount: 2,
        preflightReceiptId: "graymatter-preflight-dpp-001",
        retrievalReceiptCount: 1,
        retrievalStatus: "ready",
        retrievalTraceId: "gm-trace-dpp-context-001",
      },
      createdAt: "2026-06-21T20:17:30.000Z",
    },
    {
      id: "artifact-file-read-app-bundle",
      kind: "command_stdout",
      title: "App bundle manifest inspection",
      uri: "valoride://build-mode/artifacts/valor-task-digital-product-pro-001/cmd-inspect-app-bundle/file-read-command_stdout.json",
      commandId: "cmd-inspect-app-bundle",
      receiptId: "build-command-receipt-file-read-bundle",
      summary:
        "Inspect app bundle manifest read apps/digital-product-pro/app-bundle.json (2048 bytes).",
      metadata: {
        byteSize: 2048,
        contentHash:
          "sha256:0a1b2c3d4e5f67890123456789abcdef0a1b2c3d4e5f67890123456789abcdef",
        filePath: "apps/digital-product-pro/app-bundle.json",
        lineCount: 42,
        truncated: false,
      },
      createdAt: "2026-06-21T20:18:30.000Z",
    },
    {
      id: "artifact-generated-thorapi-read-dpp-001",
      kind: "command_stdout",
      title: "Generated ThorAPI artifact inspection",
      uri: "valoride://build-mode/artifacts/valor-task-digital-product-pro-001/cmd-inspect-generated-artifact/file-read-command_stdout.json",
      commandId: "cmd-inspect-generated-artifact",
      receiptId: "build-command-receipt-generated-artifact-read",
      summary: "Read-only inspection of protected generated ThorAPI output.",
      metadata: {
        byteSize: 4096,
        contentHash:
          "sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
        filePath: "apps/digital-product-pro/thorapi/redux/ProductService.tsx",
        generated: true,
        lineCount: 128,
        protected: true,
        truncated: false,
      },
      createdAt: "2026-06-21T20:18:40.000Z",
    },
    {
      id: "artifact-app-bundle-diff-dpp-001",
      kind: "app_bundle_diff",
      title: "App bundle diff receipt",
      uri: "valoride://build-mode/commands/cmd-generate-app-bundle-diff/app_bundle_diff",
      commandId: "cmd-generate-app-bundle-diff",
      receiptId: "build-command-receipt-app-bundle-diff",
      summary:
        "App bundle diff generated from manifest intent, editable adapters, and generated ThorAPI artifacts.",
      metadata: {
        addedArtifactCount: 2,
        appBundleId: "app-bundle-digital-product-pro",
        byteSize: 640,
        changedArtifactCount: 1,
        contentHash:
          "sha256:fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
        diffId: "app-bundle-diff-dpp-001",
        generatedAt: "2026-06-21T20:18:20.000Z",
        removedArtifactCount: 0,
      },
      createdAt: "2026-06-21T20:18:50.000Z",
    },
    {
      id: "artifact-mcp-server-inspect-dpp-001",
      kind: "mcp_result",
      title: "Private workflow MCP server inspection",
      uri: "valoride://build-mode/artifacts/valor-task-digital-product-pro-001/cmd-mcp-private-workflow-server-inspect/mcp-result.json",
      commandId: "cmd-mcp-private-workflow-server-inspect",
      receiptId: "build-command-receipt-mcp-server-inspect",
      summary:
        "private-valkyr-workflows exposed digitalProduct.fulfillPurchase as a private MCP tool.",
      metadata: {
        executionId: "mcp-exec-dpp-server-inspect-001",
        resourceCount: 1,
        serverName: "private-valkyr-workflows",
        status: "succeeded",
        toolName: "listTools",
        traceId: "mcp-trace-dpp-server-inspect-001",
      },
      createdAt: "2026-06-21T20:18:55.000Z",
    },
    {
      id: "artifact-command-stdout-dpp-001",
      kind: "command_stdout",
      title: "Unit test command stdout",
      uri: "valoride://build-mode/commands/cmd-test/command_stdout",
      commandId: "cmd-test",
      receiptId: "build-command-receipt-fixture-context",
      summary:
        "Command dispatch recorded; terminal stdout proof is pending execution.",
      metadata: {
        completed: false,
      },
      createdAt: "2026-06-21T20:19:00.000Z",
    },
    {
      id: "artifact-checkpoint-dpp-001",
      kind: "checkpoint",
      title: "Pre-edit checkpoint proof",
      uri: "valoride://build-mode/checkpoints/checkpoint-pre-edit-dpp",
      commandId: "cmd-checkpoint-create",
      receiptId: "build-command-receipt-checkpoint-create",
      summary: "Shadow-git checkpoint reference for rollback.",
      metadata: {
        checkpointAction: "create",
        checkpointHash: "shadowgit:dpp-pre-edit",
        checkpointRef: "checkpoint-pre-edit-dpp",
        workspaceRoot: "/workspace/apps/digital-product-pro",
      },
      createdAt: "2026-06-21T20:18:00.000Z",
    },
    {
      id: "artifact-connector-gmail-thread-001",
      kind: "connector_data",
      title: "Authorized Gmail connector read",
      uri: "valoride://build-mode/connectors/gmail/thread/digital-product-order",
      receiptId: "receipt-connector-gmail-thread-001",
      summary:
        "Connector read proved order-support context without storing message bodies.",
      metadata: {
        connectorId: "gmail",
        connectorName: "Gmail",
        dataClass: "email.thread",
        queryRef: "gmail:thread:digital-product-order",
        receiptRef: "connector_receipt:gmail-thread-dpp-001",
        recordCount: 2,
        resourceUri: "gmail://thread/digital-product-order",
        status: "authorized",
        traceId: "connector-trace-gmail-dpp-001",
      },
      createdAt: "2026-06-21T20:18:45.000Z",
    },
    {
      id: "artifact-connector-calendar-launch-001",
      kind: "connector_data",
      title: "Authorized Calendar connector read",
      uri: "valoride://build-mode/connectors/google-calendar/events/digital-product-launch-window",
      receiptId: "receipt-connector-calendar-launch-001",
      summary:
        "Connector read proved launch-window availability context without storing event bodies.",
      metadata: {
        connectorId: "google-calendar",
        connectorName: "Google Calendar",
        dataClass: "calendar.events",
        queryRef: "google-calendar:events:digital-product-launch-window",
        receiptRef: "connector_receipt:calendar-launch-window-001",
        recordCount: 4,
        resourceUri: "google-calendar://events/digital-product-launch-window",
        status: "authorized",
        traceId: "connector-trace-calendar-launch-001",
      },
      createdAt: "2026-06-21T20:19:00.000Z",
    },
    {
      id: "artifact-connector-tasks-launch-001",
      kind: "connector_data",
      title: "Authorized Tasks connector read",
      uri: "valoride://build-mode/connectors/google-tasks/list/digital-product-launch",
      receiptId: "receipt-connector-tasks-launch-001",
      summary:
        "Connector read proved launch checklist context without storing task bodies.",
      metadata: {
        connectorId: "google-tasks",
        connectorName: "Google Tasks",
        dataClass: "task.list",
        queryRef: "google-tasks:list:digital-product-launch",
        receiptRef: "connector_receipt:tasks-launch-list-001",
        recordCount: 7,
        resourceUri: "google-tasks://list/digital-product-launch",
        status: "authorized",
        traceId: "connector-trace-tasks-launch-001",
      },
      createdAt: "2026-06-21T20:19:15.000Z",
    },
  ],
  browserVerification: {
    status: "not-started",
    previewUrl: "http://localhost:5173/apps/digital-product-pro",
    artifactIds: [],
    consoleErrorCount: 0,
  },
  finalReport: {
    title: "Digital Product Pro Build Mode Report",
    status: "draft",
    filesChanged: [],
    testsRun: ["pending"],
    gaps: ["Browser verification has not completed yet."],
    nextHandoff: [
      "Launch payload validated through the SageChat/App Gallery task bridge.",
      "Merge live command, GrayMatter, workflow, and automation receipts as they arrive.",
    ],
  },
  appBundleDiffs: [
    {
      id: "bundle-diff-dpp-001",
      title: "Initial app bundle diff",
      appBundleId: "app-bundle-digital-product-pro",
      generatedAt: "2026-06-21T20:18:20.000Z",
      addedArtifacts: [
        "apps/digital-product-pro/src/pages/Checkout.tsx",
        "apps/digital-product-pro/assets/cover.png",
      ],
      changedArtifacts: ["apps/digital-product-pro/app-bundle.json"],
      removedArtifacts: [],
      receiptIds: [
        "receipt-generation-dpp-001",
        "build-command-receipt-app-bundle-diff",
      ],
      evidenceArtifactIds: [
        "artifact-generated-thorapi-read-dpp-001",
        "artifact-app-bundle-diff-dpp-001",
      ],
    },
  ],
};
