/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelAction.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/

// defines the Redux Actions for OpenClawLightsailLaunchResponse

// OpenClawLightsailLaunchResponse

export const FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST = 'FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST';
export const FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS = 'FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS';
export const FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE = 'FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE';

export const ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST = 'ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST';
export const ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS = 'ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS';
export const ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE = 'ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE';

export const UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST = 'UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST';
export const UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS = 'UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS';
export const UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE = 'UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE';

export const DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST = 'DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST';
export const DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS = 'DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS';
export const DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE = 'DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE';

export const LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST = 'LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST';
export const LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS = 'LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS';
export const LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE = 'LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE';

export const addOpenClawLightsailLaunchResponseRequest = () => ({
    type: ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST,
});

export const addOpenClawLightsailLaunchResponseSuccess = (OpenClawLightsailLaunchResponses: any) => ({
    type: ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS,
    payload: OpenClawLightsailLaunchResponses,
});

export const addOpenClawLightsailLaunchResponseFailure = (error: Error) => ({
    type: ADD_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE,
    payload: error,
});


export const fetchOpenClawLightsailLaunchResponseRequest = () => ({
    type: FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST,
});

export const fetchOpenClawLightsailLaunchResponseSuccess = (OpenClawLightsailLaunchResponses: any) => ({
    type: FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS,
    payload: OpenClawLightsailLaunchResponses,
});

export const fetchOpenClawLightsailLaunchResponseFailure = (error: Error) => ({
    type: FETCH_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE,
    payload: error,
});

export const listOpenClawLightsailLaunchResponseRequest = () => ({
    type: LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST,
});

export const listOpenClawLightsailLaunchResponseSuccess = (OpenClawLightsailLaunchResponses: any) => ({
    type: LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS,
    payload: OpenClawLightsailLaunchResponses,
});

export const listOpenClawLightsailLaunchResponseFailure = (error: Error) => ({
    type: LIST_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE,
    payload: error,
});

export const updateOpenClawLightsailLaunchResponseRequest = (OpenClawLightsailLaunchResponse: any) => ({
    type: UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST,
    payload: OpenClawLightsailLaunchResponse,
});

export const updateOpenClawLightsailLaunchResponseSuccess = (OpenClawLightsailLaunchResponse: any) => ({
    type: UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS,
    payload: OpenClawLightsailLaunchResponse,
});

export const updateOpenClawLightsailLaunchResponseFailure = (error: Error) => ({
    type: UPDATE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE,
    payload: error,
});

export const deleteOpenClawLightsailLaunchResponseRequest = (OpenClawLightsailLaunchResponse: any) => ({
    type: DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_REQUEST,
    payload: OpenClawLightsailLaunchResponse,
});

export const deleteOpenClawLightsailLaunchResponseSuccess = (OpenClawLightsailLaunchResponse: any) => ({
    type: DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_SUCCESS,
    payload: OpenClawLightsailLaunchResponse,
});

export const deleteOpenClawLightsailLaunchResponseFailure = (error: Error) => ({
    type: DELETE_OPENCLAWLIGHTSAILLAUNCHRESPONSE_FAILURE,
    payload: error,
});
