/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelAction.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
// defines the Redux Actions for IdempotencyKey
// IdempotencyKey
export const FETCH_IDEMPOTENCYKEY_REQUEST = "FETCH_IDEMPOTENCYKEY_REQUEST";
export const FETCH_IDEMPOTENCYKEY_SUCCESS = "FETCH_IDEMPOTENCYKEY_SUCCESS";
export const FETCH_IDEMPOTENCYKEY_FAILURE = "FETCH_IDEMPOTENCYKEY_FAILURE";
export const ADD_IDEMPOTENCYKEY_REQUEST = "ADD_IDEMPOTENCYKEY_REQUEST";
export const ADD_IDEMPOTENCYKEY_SUCCESS = "ADD_IDEMPOTENCYKEY_SUCCESS";
export const ADD_IDEMPOTENCYKEY_FAILURE = "ADD_IDEMPOTENCYKEY_FAILURE";
export const UPDATE_IDEMPOTENCYKEY_REQUEST = "UPDATE_IDEMPOTENCYKEY_REQUEST";
export const UPDATE_IDEMPOTENCYKEY_SUCCESS = "UPDATE_IDEMPOTENCYKEY_SUCCESS";
export const UPDATE_IDEMPOTENCYKEY_FAILURE = "UPDATE_IDEMPOTENCYKEY_FAILURE";
export const DELETE_IDEMPOTENCYKEY_REQUEST = "DELETE_IDEMPOTENCYKEY_REQUEST";
export const DELETE_IDEMPOTENCYKEY_SUCCESS = "DELETE_IDEMPOTENCYKEY_SUCCESS";
export const DELETE_IDEMPOTENCYKEY_FAILURE = "DELETE_IDEMPOTENCYKEY_FAILURE";
export const LIST_IDEMPOTENCYKEY_REQUEST = "LIST_IDEMPOTENCYKEY_REQUEST";
export const LIST_IDEMPOTENCYKEY_SUCCESS = "LIST_IDEMPOTENCYKEY_SUCCESS";
export const LIST_IDEMPOTENCYKEY_FAILURE = "LIST_IDEMPOTENCYKEY_FAILURE";
export const addIdempotencyKeyRequest = () => ({
    type: ADD_IDEMPOTENCYKEY_REQUEST,
});
export const addIdempotencyKeySuccess = (IdempotencyKeys) => ({
    type: ADD_IDEMPOTENCYKEY_SUCCESS,
    payload: IdempotencyKeys,
});
export const addIdempotencyKeyFailure = (error) => ({
    type: ADD_IDEMPOTENCYKEY_FAILURE,
    payload: error,
});
export const fetchIdempotencyKeyRequest = () => ({
    type: FETCH_IDEMPOTENCYKEY_REQUEST,
});
export const fetchIdempotencyKeySuccess = (IdempotencyKeys) => ({
    type: FETCH_IDEMPOTENCYKEY_SUCCESS,
    payload: IdempotencyKeys,
});
export const fetchIdempotencyKeyFailure = (error) => ({
    type: FETCH_IDEMPOTENCYKEY_FAILURE,
    payload: error,
});
export const listIdempotencyKeyRequest = () => ({
    type: LIST_IDEMPOTENCYKEY_REQUEST,
});
export const listIdempotencyKeySuccess = (IdempotencyKeys) => ({
    type: LIST_IDEMPOTENCYKEY_SUCCESS,
    payload: IdempotencyKeys,
});
export const listIdempotencyKeyFailure = (error) => ({
    type: LIST_IDEMPOTENCYKEY_FAILURE,
    payload: error,
});
export const updateIdempotencyKeyRequest = (IdempotencyKey) => ({
    type: UPDATE_IDEMPOTENCYKEY_REQUEST,
    payload: IdempotencyKey,
});
export const updateIdempotencyKeySuccess = (IdempotencyKey) => ({
    type: UPDATE_IDEMPOTENCYKEY_SUCCESS,
    payload: IdempotencyKey,
});
export const updateIdempotencyKeyFailure = (error) => ({
    type: UPDATE_IDEMPOTENCYKEY_FAILURE,
    payload: error,
});
export const deleteIdempotencyKeyRequest = (IdempotencyKey) => ({
    type: DELETE_IDEMPOTENCYKEY_REQUEST,
    payload: IdempotencyKey,
});
export const deleteIdempotencyKeySuccess = (IdempotencyKey) => ({
    type: DELETE_IDEMPOTENCYKEY_SUCCESS,
    payload: IdempotencyKey,
});
export const deleteIdempotencyKeyFailure = (error) => ({
    type: DELETE_IDEMPOTENCYKEY_FAILURE,
    payload: error,
});
//# sourceMappingURL=IdempotencyKeyApiAction.js.map