"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppObjectModelStatusEnum = void 0;
exports.AppObjectModelFromJSON = AppObjectModelFromJSON;
exports.AppObjectModelToJSON = AppObjectModelToJSON;
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
const runtime_1 = require("../src/runtime");
const DataObject_1 = require("./DataObject");
function AppObjectModelFromJSON(json) {
    return {
        ...(0, DataObject_1.DataObjectFromJSON)(json),
        'objectModelRef': json['objectModelRef'],
        'specDraftRef': json['specDraftRef'],
        'tenantId': json['tenantId'],
        'traceId': json['traceId'],
        'status': json['status'],
        'requestRef': !(0, runtime_1.exists)(json, 'requestRef') ? undefined : json['requestRef'],
        'accountId': !(0, runtime_1.exists)(json, 'accountId') ? undefined : json['accountId'],
        'applicationId': !(0, runtime_1.exists)(json, 'applicationId') ? undefined : json['applicationId'],
        'objectCount': !(0, runtime_1.exists)(json, 'objectCount') ? undefined : json['objectCount'],
        'modelJson': !(0, runtime_1.exists)(json, 'modelJson') ? undefined : json['modelJson'],
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : new Date(json['createdAt']),
        'errorMessage': !(0, runtime_1.exists)(json, 'errorMessage') ? undefined : json['errorMessage'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'ownerId': !(0, runtime_1.exists)(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !(0, runtime_1.exists)(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !(0, runtime_1.exists)(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !(0, runtime_1.exists)(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !(0, runtime_1.exists)(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !(0, runtime_1.exists)(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !(0, runtime_1.exists)(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
        'trashed': !(0, runtime_1.exists)(json, 'trashed') ? undefined : json['trashed'],
    };
}
function AppObjectModelToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...(0, DataObject_1.DataObjectToJSON)(value),
        'objectModelRef': value.objectModelRef,
        'specDraftRef': value.specDraftRef,
        'tenantId': value.tenantId,
        'traceId': value.traceId,
        'status': value.status,
        'requestRef': value.requestRef,
        'accountId': value.accountId,
        'applicationId': value.applicationId,
        'objectCount': value.objectCount,
        'modelJson': value.modelJson,
        'createdAt': value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
        'errorMessage': value.errorMessage,
        'trashed': value.trashed,
    };
}
/**
* @export
* @enum {string}
*/
var AppObjectModelStatusEnum;
(function (AppObjectModelStatusEnum) {
    AppObjectModelStatusEnum["DRAFT"] = "draft";
    AppObjectModelStatusEnum["GENERATED"] = "generated";
    AppObjectModelStatusEnum["ACCEPTED"] = "accepted";
    AppObjectModelStatusEnum["FAILED"] = "failed";
})(AppObjectModelStatusEnum || (exports.AppObjectModelStatusEnum = AppObjectModelStatusEnum = {}));
//# sourceMappingURL=AppObjectModel.js.map