"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GenerateTrustKeyResponseFromJSON = GenerateTrustKeyResponseFromJSON;
exports.GenerateTrustKeyResponseToJSON = GenerateTrustKeyResponseToJSON;
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
const runtime_1 = require("../src/runtime");
const DataObject_1 = require("./DataObject");
const _1 = require("./");
function GenerateTrustKeyResponseFromJSON(json) {
    return {
        ...(0, DataObject_1.DataObjectFromJSON)(json),
        'trustKey': !(0, runtime_1.exists)(json, 'trustKey') ? undefined : (0, _1.TrustKeyFromJSON)(json['trustKey']),
        'activeVersion': !(0, runtime_1.exists)(json, 'activeVersion') ? undefined : (0, _1.TrustKeyVersionFromJSON)(json['activeVersion']),
        'ownerId': !(0, runtime_1.exists)(json, 'ownerId') ? undefined : json['ownerId'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'createdDate': !(0, runtime_1.exists)(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !(0, runtime_1.exists)(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !(0, runtime_1.exists)(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !(0, runtime_1.exists)(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !(0, runtime_1.exists)(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !(0, runtime_1.exists)(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
        'trashed': !(0, runtime_1.exists)(json, 'trashed') ? undefined : json['trashed'],
    };
}
function GenerateTrustKeyResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...(0, DataObject_1.DataObjectToJSON)(value),
        'trustKey': (0, _1.TrustKeyToJSON)(value.trustKey),
        'activeVersion': (0, _1.TrustKeyVersionToJSON)(value.activeVersion),
        'ownerId': value.ownerId,
        'trashed': value.trashed,
    };
}
//# sourceMappingURL=GenerateTrustKeyResponse.js.map