"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.McpMarketplaceItemFromJSON = McpMarketplaceItemFromJSON;
exports.McpMarketplaceItemToJSON = McpMarketplaceItemToJSON;
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-09T22:07:20.612811-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
const runtime_1 = require("../src/runtime");
const DataObject_1 = require("./DataObject");
const _1 = require("./");
function McpMarketplaceItemFromJSON(json) {
    return {
        ...(0, DataObject_1.DataObjectFromJSON)(json),
        'githubUrl': json['githubUrl'],
        'name': json['name'],
        'author': json['author'],
        'description': json['description'],
        'mcpMarketplaceCatalogId': !(0, runtime_1.exists)(json, 'mcpMarketplaceCatalogId') ? undefined : json['mcpMarketplaceCatalogId'],
        'mcpServerId': !(0, runtime_1.exists)(json, 'mcpServerId') ? undefined : json['mcpServerId'],
        'icon': !(0, runtime_1.exists)(json, 'icon') ? undefined : json['icon'],
        'logoUrl': !(0, runtime_1.exists)(json, 'logoUrl') ? undefined : json['logoUrl'],
        'category': !(0, runtime_1.exists)(json, 'category') ? undefined : json['category'],
        'tags': !(0, runtime_1.exists)(json, 'tags') ? undefined : json['tags'].map(_1.McpMarketplaceItemTagFromJSON),
        'requiresApiKey': !(0, runtime_1.exists)(json, 'requiresApiKey') ? undefined : json['requiresApiKey'],
        'readmeContent': !(0, runtime_1.exists)(json, 'readmeContent') ? undefined : json['readmeContent'],
        'llmsInstallationContent': !(0, runtime_1.exists)(json, 'llmsInstallationContent') ? undefined : json['llmsInstallationContent'],
        'isRecommended': !(0, runtime_1.exists)(json, 'isRecommended') ? undefined : json['isRecommended'],
        'githubStars': !(0, runtime_1.exists)(json, 'githubStars') ? undefined : json['githubStars'],
        'downloadCount': !(0, runtime_1.exists)(json, 'downloadCount') ? undefined : json['downloadCount'],
        'createdAt': !(0, runtime_1.exists)(json, 'createdAt') ? undefined : new Date(json['createdAt']),
        'updatedAt': !(0, runtime_1.exists)(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
        'lastGithubSync': !(0, runtime_1.exists)(json, 'lastGithubSync') ? undefined : new Date(json['lastGithubSync']),
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'ownerId': !(0, runtime_1.exists)(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !(0, runtime_1.exists)(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !(0, runtime_1.exists)(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !(0, runtime_1.exists)(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !(0, runtime_1.exists)(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !(0, runtime_1.exists)(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !(0, runtime_1.exists)(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
        'trashed': !(0, runtime_1.exists)(json, 'trashed') ? undefined : json['trashed'],
    };
}
function McpMarketplaceItemToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...(0, DataObject_1.DataObjectToJSON)(value),
        'githubUrl': value.githubUrl,
        'name': value.name,
        'author': value.author,
        'description': value.description,
        'mcpMarketplaceCatalogId': value.mcpMarketplaceCatalogId,
        'mcpServerId': value.mcpServerId,
        'icon': value.icon,
        'logoUrl': value.logoUrl,
        'category': value.category,
        'tags': value.tags === undefined ? undefined : value.tags.map(_1.McpMarketplaceItemTagToJSON),
        'requiresApiKey': value.requiresApiKey,
        'readmeContent': value.readmeContent,
        'llmsInstallationContent': value.llmsInstallationContent,
        'isRecommended': value.isRecommended,
        'githubStars': value.githubStars,
        'downloadCount': value.downloadCount,
        'createdAt': value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
        'updatedAt': value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
        'lastGithubSync': value.lastGithubSync === undefined ? undefined : value.lastGithubSync.toISOString(),
        'trashed': value.trashed,
    };
}
//# sourceMappingURL=McpMarketplaceItem.js.map