// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Policy governing when answers can be provided.
 * @export
 * @enum {string}
 */
export enum RetrievalAnswerPolicy {
    AllowAnswer = 'ALLOW_ANSWER',
    AllowWithCaveat = 'ALLOW_WITH_CAVEAT',
    DoNotAnswerConfidently = 'DO_NOT_ANSWER_CONFIDENTLY',
    RequireRetry = 'REQUIRE_RETRY',
    RequireClarification = 'REQUIRE_CLARIFICATION',
    Deny = 'DENY'
}

export function RetrievalAnswerPolicyFromJSON(json: any): RetrievalAnswerPolicy {
    return json as RetrievalAnswerPolicy;
}

export function RetrievalAnswerPolicyToJSON(value?: RetrievalAnswerPolicy): any {
    return value as any;
}

