"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrustKeyKeyStatusEnum = exports.TrustKeyKeyPurposeEnum = void 0;
exports.TrustKeyFromJSON = TrustKeyFromJSON;
exports.TrustKeyToJSON = TrustKeyToJSON;
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
const runtime_1 = require("../src/runtime");
const DataObject_1 = require("./DataObject");
const _1 = require("./");
function TrustKeyFromJSON(json) {
    return {
        ...(0, DataObject_1.DataObjectFromJSON)(json),
        name: !(0, runtime_1.exists)(json, "name") ? undefined : json["name"],
        keyPurpose: !(0, runtime_1.exists)(json, "keyPurpose") ? undefined : json["keyPurpose"],
        keyStatus: !(0, runtime_1.exists)(json, "keyStatus") ? undefined : json["keyStatus"],
        provider: !(0, runtime_1.exists)(json, "provider")
            ? undefined
            : (0, _1.TrustKeyProviderFromJSON)(json["provider"]),
        activeVersion: !(0, runtime_1.exists)(json, "activeVersion")
            ? undefined
            : (0, _1.TrustKeyVersionFromJSON)(json["activeVersion"]),
        rotationPeriodDays: !(0, runtime_1.exists)(json, "rotationPeriodDays")
            ? undefined
            : json["rotationPeriodDays"],
        tenantId: !(0, runtime_1.exists)(json, "tenantId") ? undefined : json["tenantId"],
        ownerId: !(0, runtime_1.exists)(json, "ownerId") ? undefined : json["ownerId"],
        id: !(0, runtime_1.exists)(json, "id") ? undefined : json["id"],
        createdDate: !(0, runtime_1.exists)(json, "createdDate")
            ? undefined
            : new Date(json["createdDate"]),
        keyHash: !(0, runtime_1.exists)(json, "keyHash") ? undefined : json["keyHash"],
        lastAccessedById: !(0, runtime_1.exists)(json, "lastAccessedById")
            ? undefined
            : json["lastAccessedById"],
        lastAccessedDate: !(0, runtime_1.exists)(json, "lastAccessedDate")
            ? undefined
            : new Date(json["lastAccessedDate"]),
        lastModifiedById: !(0, runtime_1.exists)(json, "lastModifiedById")
            ? undefined
            : json["lastModifiedById"],
        lastModifiedDate: !(0, runtime_1.exists)(json, "lastModifiedDate")
            ? undefined
            : new Date(json["lastModifiedDate"]),
        trashed: !(0, runtime_1.exists)(json, "trashed") ? undefined : json["trashed"],
    };
}
function TrustKeyToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...(0, DataObject_1.DataObjectToJSON)(value),
        name: value.name,
        keyPurpose: value.keyPurpose,
        keyStatus: value.keyStatus,
        provider: (0, _1.TrustKeyProviderToJSON)(value.provider),
        activeVersion: (0, _1.TrustKeyVersionToJSON)(value.activeVersion),
        rotationPeriodDays: value.rotationPeriodDays,
        tenantId: value.tenantId,
        ownerId: value.ownerId,
        trashed: value.trashed,
    };
}
/**
 * @export
 * @enum {string}
 */
var TrustKeyKeyPurposeEnum;
(function (TrustKeyKeyPurposeEnum) {
    TrustKeyKeyPurposeEnum["FIELDENCRYPTION"] = "field_encryption";
    TrustKeyKeyPurposeEnum["EVENTSIGNING"] = "event_signing";
    TrustKeyKeyPurposeEnum["PROOFSIGNING"] = "proof_signing";
    TrustKeyKeyPurposeEnum["TOKENSIGNING"] = "token_signing";
    TrustKeyKeyPurposeEnum["ATTESTATIONSIGNING"] = "attestation_signing";
    TrustKeyKeyPurposeEnum["DEKWRAPPING"] = "dek_wrapping";
})(TrustKeyKeyPurposeEnum || (exports.TrustKeyKeyPurposeEnum = TrustKeyKeyPurposeEnum = {}));
/**
 * @export
 * @enum {string}
 */
var TrustKeyKeyStatusEnum;
(function (TrustKeyKeyStatusEnum) {
    TrustKeyKeyStatusEnum["PENDINGACTIVATION"] = "pending_activation";
    TrustKeyKeyStatusEnum["ACTIVE"] = "active";
    TrustKeyKeyStatusEnum["DECRYPTONLY"] = "decrypt_only";
    TrustKeyKeyStatusEnum["SUSPENDED"] = "suspended";
    TrustKeyKeyStatusEnum["RETIRED"] = "retired";
    TrustKeyKeyStatusEnum["DESTROYSCHEDULED"] = "destroy_scheduled";
    TrustKeyKeyStatusEnum["DESTROYED"] = "destroyed";
})(TrustKeyKeyStatusEnum || (exports.TrustKeyKeyStatusEnum = TrustKeyKeyStatusEnum = {}));
//# sourceMappingURL=TrustKey.js.map