"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkflowExecutionMode = void 0;
exports.WorkflowExecutionModeFromJSON = WorkflowExecutionModeFromJSON;
exports.WorkflowExecutionModeToJSON = WorkflowExecutionModeToJSON;
/**
 * Human-in-the-loop execution posture for a workflow step or task.
 * @export
 * @enum {string}
 */
var WorkflowExecutionMode;
(function (WorkflowExecutionMode) {
    WorkflowExecutionMode["Assist"] = "assist";
    WorkflowExecutionMode["Review"] = "review";
    WorkflowExecutionMode["Supervise"] = "supervise";
    WorkflowExecutionMode["Delegate"] = "delegate";
    WorkflowExecutionMode["Shadow"] = "shadow";
})(WorkflowExecutionMode || (exports.WorkflowExecutionMode = WorkflowExecutionMode = {}));
function WorkflowExecutionModeFromJSON(json) {
    return json;
}
function WorkflowExecutionModeToJSON(value) {
    return value;
}
//# sourceMappingURL=WorkflowExecutionMode.js.map