// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-09T22:07:20.612811-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelReducer.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createSlice } from "@reduxjs/toolkit";

import { ContentData } from '@thorapi/model/ContentData';

const ContentDataSlice = createSlice({
  name: "ContentDatas",
  initialState: [],

  reducers: {
    ContentDataAdded(state, action) {
      state.push(action.payload);
    },

    ContentDataValueToggled(state, action) {
      console.log("ContentData TOGGLE")
      console.warn(JSON.stringify(action))
      const ContentData:ContentData = state.find((ContentData) => ContentData.id === action.payload.ContentDataId);
      if (ContentData) {
        if (action.payload.target === "SOMETHING") {
          
        }
      }
    },
    
    ContentDatapropertySet(state, action) {
      const ContentData = state.find((ContentData) => ContentData.id === action.payload.ContentDataId);
      if (ContentData) {
      //  ContentData[action.property] = action.payload[action.property];
      }
    },
  },
});

export const {
  ContentDataAdded,
  ContentDataValueToggled,
  ContentDatapropertySet
} = ContentDataSlice.actions;
export default ContentDataSlice.reducer;
