// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelReducer.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createSlice } from "@reduxjs/toolkit";

import { GraphLink } from '@thorapi/model/GraphLink';

const GraphLinkSlice = createSlice({
  name: "GraphLinks",
  initialState: [],

  reducers: {
    GraphLinkAdded(state, action) {
      state.push(action.payload);
    },

    GraphLinkValueToggled(state, action) {
      console.log("GraphLink TOGGLE")
      console.warn(JSON.stringify(action))
      const GraphLink:GraphLink = state.find((GraphLink) => GraphLink.id === action.payload.GraphLinkId);
      if (GraphLink) {
        if (action.payload.target === "SOMETHING") {
          
        }
      }
    },
    
    GraphLinkpropertySet(state, action) {
      const GraphLink = state.find((GraphLink) => GraphLink.id === action.payload.GraphLinkId);
      if (GraphLink) {
      //  GraphLink[action.property] = action.payload[action.property];
      }
    },
  },
});

export const {
  GraphLinkAdded,
  GraphLinkValueToggled,
  GraphLinkpropertySet
} = GraphLinkSlice.actions;
export default GraphLinkSlice.reducer;
