export { parseAssistantMessage } from "./parse-assistant-message";
export const toolUseNames = [
    "execute_command",
    "read_file",
    "write_to_file",
    "replace_in_file",
    "precision_search_and_replace",
    "search_files",
    "list_files",
    "list_code_definition_names",
    "browser_action",
    "use_mcp_tool",
    "access_mcp_resource",
    "ask_followup_question",
    "plan_mode_respond",
    "load_mcp_documentation",
    "attempt_completion",
    "new_task",
    "condense",
    "send_ws_message",
];
export const toolParamNames = [
    "command",
    "requires_approval",
    "path",
    "content",
    "diff",
    "edits",
    "regex",
    "file_pattern",
    "recursive",
    "action",
    "url",
    "coordinate",
    "text",
    "server_name",
    "tool_name",
    "arguments",
    "uri",
    "question",
    "options",
    "response",
    "result",
    "context",
    "to_handle",
    "message",
];
//# sourceMappingURL=index.js.map