// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-09T22:07:20.612811-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { ErrorMessage, Field, Formik, FormikHelpers, FormikValues } from 'formik';
import React, { useState } from 'react';
import {
  Form as BSForm,
  Accordion,
  Col,
  Row,
  Spinner,
  Alert
} from 'react-bootstrap';
import LoadingSpinner from '@valkyr/component-library/LoadingSpinner';
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from 'react-icons/fa';
import CoolButton from '@valkyr/component-library/CoolButton';
import * as Yup from 'yup';
import { SmartField } from '@valkyr/component-library/ForeignKey/SmartField';

import { PermissionDialog } from '@valkyr/component-library/PermissionDialog';
import { AclGrantRequest, PermissionType } from '@valkyr/component-library/PermissionDialog/types';


import {
  Border,
  BorderStyleEnum,
  BorderColorEnum,
} from '@thorapi/model';

import { useAddBorderMutation } from '../../services/BorderService';

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-09T22:07:20.612811-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
GridHeim Formatting Border
*/

/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */
const StyleValidation = () => {
  return [
    'None',
    'Thin',
    'Medium',
    'Dashed',
    'Dotted',
    'Thick',
    'Double',
    'Hair',
    'MediumDashed',
    'DashDot',
    'MediumDashDot',
    'DashDotDot',
    'MediumDashDotDot',
    'SlantedDashDot',
  ];
};
const ColorValidation = () => {
  return [
    'Black',
    'Red',
    'Blue',
    'Yellow',
    'Green',
    'Teal',
    'Gray50',
  ];
};

/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema: Yup.NumberSchema) =>
  schema.transform((val, orig) => (orig === '' || orig === null ? undefined : val));

const validationSchema = Yup.object().shape({
        formatId: Yup.string(),
      style: Yup.mixed()
        .oneOf(StyleValidation(), "Invalid value for style")
        ,
      color: Yup.mixed()
        .oneOf(ColorValidation(), "Invalid value for color")
        ,
        trashed: Yup.boolean(),
});

/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const BorderForm: React.FC = () => {
  const [addBorder, addBorderResult] = useAddBorderMutation();
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState<string | null>(null);

  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: 'current_user',
    permissions: {
      isOwner: true,
      isAdmin: true,
      canGrantPermissions: true,
      permissions: [PermissionType.READ, PermissionType.WRITE, PermissionType.CREATE, PermissionType.DELETE, PermissionType.ADMINISTRATION],
    },
  };

  /* -----------------------------------------------------
     INITIAL VALUES - only NON read-only fields
  -------------------------------------------------------- */
  const initialValues: Partial<Border> = {
          formatId: '',
        style: undefined,
        color: undefined,
          trashed: false,
  };

  // Permission Management Handlers
  const handleManagePermissions = (objectId: string) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };

  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };

  const handlePermissionsSave = (grants: AclGrantRequest[]) => {
    console.log('Permissions saved for new Border:', grants);
  };

  /* SUBMIT HANDLER */
  const handleSubmit = async (values: FormikValues, { setSubmitting }: FormikHelpers<Border>) => {
    try {
      setSuccessMessage(null);
      setErrorMessage(null);
      console.log("Border form values:", values);

      // NOTE: depending on your generated endpoint, you may need { body: values }
      const result = await addBorder(values as any).unwrap();

      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `Border created successfully! Would you like to set permissions for this object?`
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      setSuccessMessage("Saved successfully.");
    } catch (error) {
      console.error('Failed to create Border:', error);
      setErrorMessage('Failed to save. Please try again.');
    }
    setSubmitting(false);
  };

  return (
    <div>
      <Formik
        validateOnBlur={true}
        initialValues={initialValues as Border}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({
          isSubmitting,
          isValid,
          errors,
          values,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit
        }) => {
          const isSaving = isSubmitting || addBorderResult.isLoading;
          return (
          <form onSubmit={handleSubmit} className="form">
            <Accordion defaultActiveKey="1">
              
              {/* Editable Fields (NON read-only) */}
              <Accordion.Item eventKey="1">
                <Accordion.Header>
                  <FaRegPlusSquare size={28} /> &nbsp; Add New Border
                </Accordion.Header>
                <Accordion.Body>
                    <label htmlFor="formatId" className="nice-form-control">
                      <b>
                        Format Id:
                        {touched.formatId &&
                         !errors.formatId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="formatId"
                            value={values?.formatId}
                            placeholder="Format Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="formatId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="style" className="nice-form-control">
                      <b>
                        Style:
                        {touched.style &&
                         !errors.style && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>

                        {/* ENUM DROPDOWN */}
                        <BSForm.Select
                          name="style"
                          value={values.style || ''}
                          className={
                            errors.style
                              ? 'form-control field-error'
                              : 'nice-form-control form-control'
                          }
                          onChange={(e) => {
                            setFieldTouched('style', true);
                            setFieldValue('style', e.target.value || undefined);
                          }}
                        >
                          <option value="" label="Select Style" />
                          <StyleLookup />
                        </BSForm.Select>


                      <ErrorMessage
                        className="error"
                        name="style"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="color" className="nice-form-control">
                      <b>
                        Color:
                        {touched.color &&
                         !errors.color && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>

                        {/* ENUM DROPDOWN */}
                        <BSForm.Select
                          name="color"
                          value={values.color || ''}
                          className={
                            errors.color
                              ? 'form-control field-error'
                              : 'nice-form-control form-control'
                          }
                          onChange={(e) => {
                            setFieldTouched('color', true);
                            setFieldValue('color', e.target.value || undefined);
                          }}
                        >
                          <option value="" label="Select Color" />
                          <ColorLookup />
                        </BSForm.Select>


                      <ErrorMessage
                        className="error"
                        name="color"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="trashed" className="nice-form-control">
                      <b>
                        Trashed:
                        {touched.trashed &&
                         !errors.trashed && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>


                          {/* CHECKBOX FIELD */}
                          <BSForm.Check
                            id="trashed"
                            name="trashed"
                            checked={values.trashed || false}
                            onChange={(e) => {
                              setFieldTouched('trashed', true);
                              setFieldValue('trashed', e.target.checked);
                            }}
                            isInvalid={!!errors.trashed}
                            className={errors.trashed ? 'error' : ''}
                          />








                      <ErrorMessage
                        className="error"
                        name="trashed"
                        component="span"
                      />
                    </label>
                    <br />

                  {/* SUBMIT BUTTON */}
                  <CoolButton
                    variant={isValid ? (isSaving ? 'disabled' : 'success') : 'warning'}
                    type="submit"
                    disabled={!isValid || isSaving}
                  >
                    {isSaving && (<span style={ { float: 'left', minHeight: 0 } }><LoadingSpinner label="" size={18} /></span>)}
                    <FaCheckCircle size={28} /> Create New Border
                  </CoolButton>

                  {(addBorderResult.isError || errorMessage) && (
                    <Alert variant="danger" className="mt-3">
                      {errorMessage ||
                        JSON.stringify('data' in (addBorderResult as any).error ? (addBorderResult as any).error.data : (addBorderResult as any).error)}
                    </Alert>
                  )}

                  {(addBorderResult.isSuccess || successMessage) && (
                    <Alert variant="success" className="mt-3">
                      {successMessage || 'Saved successfully.'}
                    </Alert>
                  )}
                </Accordion.Body>
              </Accordion.Item>

            {/* Debug/Dev Accordion */}
              <Accordion.Item eventKey="0">
                <Accordion.Header>
                  <FaCogs size={28} /> &nbsp;Server Messages
                </Accordion.Header>
                <Accordion.Body>
                  errors: {JSON.stringify(errors)}
                  <br />
                  addBorderResult: {JSON.stringify(addBorderResult)}
                </Accordion.Body>
              </Accordion.Item>

            </Accordion>
          </form>
          );
        }}
      </Formik>

      {/* Permission Management Dialog */}
      {createdObjectId && (
        <PermissionDialog
          objectType="com.valkyrlabs.model.Border"
          objectId={createdObjectId}
          isVisible={showPermissionDialog}
          onClose={handlePermissionDialogClose}
          onSave={handlePermissionsSave}
          currentUser={currentUser}
        />
      )}
    </div>
  );
};

/*
lowercase stylelookup
uppercase STYLELOOKUP
snakecase style_lookup
pascalcase StyleLookup
camelcase styleLookup
kebabcase style-lookup
*/

const StyleLookup = () => {
  return (
    <>
      <option value='None' label="Border None" />
      <option value='Thin' label="Border Thin" />
      <option value='Medium' label="Border Medium" />
      <option value='Dashed' label="Border Dashed" />
      <option value='Dotted' label="Border Dotted" />
      <option value='Thick' label="Border Thick" />
      <option value='Double' label="Border Double" />
      <option value='Hair' label="Border Hair" />
      <option value='MediumDashed' label="Border Medium Dashed" />
      <option value='DashDot' label="Border Dash Dot" />
      <option value='MediumDashDot' label="Border Medium Dash Dot" />
      <option value='DashDotDot' label="Border Dash Dot Dot" />
      <option value='MediumDashDotDot' label="Border Medium Dash Dot Dot" />
      <option value='SlantedDashDot' label="Border Slanted Dash Dot" />
    </>
  );
};

/*
lowercase colorlookup
uppercase COLORLOOKUP
snakecase color_lookup
pascalcase ColorLookup
camelcase colorLookup
kebabcase color-lookup
*/

const ColorLookup = () => {
  return (
    <>
      <option value='Black' label="Color Black" />
      <option value='Red' label="Color Red" />
      <option value='Blue' label="Color Blue" />
      <option value='Yellow' label="Color Yellow" />
      <option value='Green' label="Color Green" />
      <option value='Teal' label="Color Teal" />
      <option value='Gray50' label="Color Gray 50" />
    </>
  );
};



/* Export the generated form */
export default BorderForm;

