// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-09T22:07:20.612811-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { ErrorMessage, Field, Formik, FormikHelpers, FormikValues } from 'formik';
import React, { useState } from 'react';
import {
  Form as BSForm,
  Accordion,
  Col,
  Row,
  Spinner,
  Alert
} from 'react-bootstrap';
import LoadingSpinner from '@valkyr/component-library/LoadingSpinner';
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from 'react-icons/fa';
import CoolButton from '@valkyr/component-library/CoolButton';
import * as Yup from 'yup';
import { SmartField } from '@valkyr/component-library/ForeignKey/SmartField';

import { PermissionDialog } from '@valkyr/component-library/PermissionDialog';
import { AclGrantRequest, PermissionType } from '@valkyr/component-library/PermissionDialog/types';


import {
  LineItem,
  LineItemTypeEnum,
} from '@thorapi/model';

import { useAddLineItemMutation } from '../../services/LineItemService';

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-09T22:07:20.612811-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
Represents an order lineitem in a customer order.
*/

/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */
const TypeValidation = () => {
  return [
    'product',
    'service',
    'discount',
    'adjustment',
    'other',
  ];
};

/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema: Yup.NumberSchema) =>
  schema.transform((val, orig) => (orig === '' || orig === null ? undefined : val));

const validationSchema = Yup.object().shape({
        salesOrderId: Yup.string(),
        lineItemAmount: asNumber(Yup.number().typeError("lineItemAmount must be a number")),
        taxRate: asNumber(Yup.number().typeError("taxRate must be a number")),
        quantity: asNumber(Yup.number().integer().typeError("quantity must be a number")),
      type: Yup.mixed()
        .oneOf(TypeValidation(), "Invalid value for type")
        ,
        trashed: Yup.boolean(),
});

/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const LineItemForm: React.FC = () => {
  const [addLineItem, addLineItemResult] = useAddLineItemMutation();
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState<string | null>(null);

  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: 'current_user',
    permissions: {
      isOwner: true,
      isAdmin: true,
      canGrantPermissions: true,
      permissions: [PermissionType.READ, PermissionType.WRITE, PermissionType.CREATE, PermissionType.DELETE, PermissionType.ADMINISTRATION],
    },
  };

  /* -----------------------------------------------------
     INITIAL VALUES - only NON read-only fields
  -------------------------------------------------------- */
  const initialValues: Partial<LineItem> = {
          salesOrderId: '',
          lineItemAmount: 0,
          taxRate: 0,
          quantity: 0,
        type: undefined,
          trashed: false,
  };

  // Permission Management Handlers
  const handleManagePermissions = (objectId: string) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };

  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };

  const handlePermissionsSave = (grants: AclGrantRequest[]) => {
    console.log('Permissions saved for new LineItem:', grants);
  };

  /* SUBMIT HANDLER */
  const handleSubmit = async (values: FormikValues, { setSubmitting }: FormikHelpers<LineItem>) => {
    try {
      setSuccessMessage(null);
      setErrorMessage(null);
      console.log("LineItem form values:", values);

      // NOTE: depending on your generated endpoint, you may need { body: values }
      const result = await addLineItem(values as any).unwrap();

      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `LineItem created successfully! Would you like to set permissions for this object?`
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      setSuccessMessage("Saved successfully.");
    } catch (error) {
      console.error('Failed to create LineItem:', error);
      setErrorMessage('Failed to save. Please try again.');
    }
    setSubmitting(false);
  };

  return (
    <div>
      <Formik
        validateOnBlur={true}
        initialValues={initialValues as LineItem}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({
          isSubmitting,
          isValid,
          errors,
          values,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit
        }) => {
          const isSaving = isSubmitting || addLineItemResult.isLoading;
          return (
          <form onSubmit={handleSubmit} className="form">
            <Accordion defaultActiveKey="1">
              
              {/* Editable Fields (NON read-only) */}
              <Accordion.Item eventKey="1">
                <Accordion.Header>
                  <FaRegPlusSquare size={28} /> &nbsp; Add New LineItem
                </Accordion.Header>
                <Accordion.Body>
                    <label htmlFor="salesOrderId" className="nice-form-control">
                      <b>
                        Sales Order Id:
                        {touched.salesOrderId &&
                         !errors.salesOrderId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="salesOrderId"
                            value={values?.salesOrderId}
                            placeholder="Sales Order Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="salesOrderId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="lineItemAmount" className="nice-form-control">
                      <b>
                        Line Item Amount:
                        {touched.lineItemAmount &&
                         !errors.lineItemAmount && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>






                          {/* DOUBLE FIELD */}
                          <Field
                            name="lineItemAmount"
                            type="number"
                            step="any"
                            value={values.lineItemAmount || ''}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                              setFieldTouched('lineItemAmount', true);
                              const v = e.target.value;
                              setFieldValue('lineItemAmount', v === '' ? undefined : Number(v));
                            }}
                            className={
                              errors.lineItemAmount
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />




                      <ErrorMessage
                        className="error"
                        name="lineItemAmount"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="taxRate" className="nice-form-control">
                      <b>
                        Tax Rate:
                        {touched.taxRate &&
                         !errors.taxRate && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>






                          {/* DOUBLE FIELD */}
                          <Field
                            name="taxRate"
                            type="number"
                            step="any"
                            value={values.taxRate || ''}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                              setFieldTouched('taxRate', true);
                              const v = e.target.value;
                              setFieldValue('taxRate', v === '' ? undefined : Number(v));
                            }}
                            className={
                              errors.taxRate
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />




                      <ErrorMessage
                        className="error"
                        name="taxRate"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="quantity" className="nice-form-control">
                      <b>
                        Quantity:
                        {touched.quantity &&
                         !errors.quantity && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>




                          {/* INTEGER FIELD */}
                          <Field
                            name="quantity"
                            type="number"
                            value={values.quantity || ''}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                              setFieldTouched('quantity', true);
                              const v = e.target.value;
                              setFieldValue('quantity', v === '' ? undefined : Number(v));
                            }}
                            className={
                              errors.quantity
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />






                      <ErrorMessage
                        className="error"
                        name="quantity"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="type" className="nice-form-control">
                      <b>
                        Type:
                        {touched.type &&
                         !errors.type && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>

                        {/* ENUM DROPDOWN */}
                        <BSForm.Select
                          name="type"
                          value={values.type || ''}
                          className={
                            errors.type
                              ? 'form-control field-error'
                              : 'nice-form-control form-control'
                          }
                          onChange={(e) => {
                            setFieldTouched('type', true);
                            setFieldValue('type', e.target.value || undefined);
                          }}
                        >
                          <option value="" label="Select Type" />
                          <TypeLookup />
                        </BSForm.Select>


                      <ErrorMessage
                        className="error"
                        name="type"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="trashed" className="nice-form-control">
                      <b>
                        Trashed:
                        {touched.trashed &&
                         !errors.trashed && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>


                          {/* CHECKBOX FIELD */}
                          <BSForm.Check
                            id="trashed"
                            name="trashed"
                            checked={values.trashed || false}
                            onChange={(e) => {
                              setFieldTouched('trashed', true);
                              setFieldValue('trashed', e.target.checked);
                            }}
                            isInvalid={!!errors.trashed}
                            className={errors.trashed ? 'error' : ''}
                          />








                      <ErrorMessage
                        className="error"
                        name="trashed"
                        component="span"
                      />
                    </label>
                    <br />

                  {/* SUBMIT BUTTON */}
                  <CoolButton
                    variant={isValid ? (isSaving ? 'disabled' : 'success') : 'warning'}
                    type="submit"
                    disabled={!isValid || isSaving}
                  >
                    {isSaving && (<span style={ { float: 'left', minHeight: 0 } }><LoadingSpinner label="" size={18} /></span>)}
                    <FaCheckCircle size={28} /> Create New LineItem
                  </CoolButton>

                  {(addLineItemResult.isError || errorMessage) && (
                    <Alert variant="danger" className="mt-3">
                      {errorMessage ||
                        JSON.stringify('data' in (addLineItemResult as any).error ? (addLineItemResult as any).error.data : (addLineItemResult as any).error)}
                    </Alert>
                  )}

                  {(addLineItemResult.isSuccess || successMessage) && (
                    <Alert variant="success" className="mt-3">
                      {successMessage || 'Saved successfully.'}
                    </Alert>
                  )}
                </Accordion.Body>
              </Accordion.Item>

            {/* Debug/Dev Accordion */}
              <Accordion.Item eventKey="0">
                <Accordion.Header>
                  <FaCogs size={28} /> &nbsp;Server Messages
                </Accordion.Header>
                <Accordion.Body>
                  errors: {JSON.stringify(errors)}
                  <br />
                  addLineItemResult: {JSON.stringify(addLineItemResult)}
                </Accordion.Body>
              </Accordion.Item>

            </Accordion>
          </form>
          );
        }}
      </Formik>

      {/* Permission Management Dialog */}
      {createdObjectId && (
        <PermissionDialog
          objectType="com.valkyrlabs.model.LineItem"
          objectId={createdObjectId}
          isVisible={showPermissionDialog}
          onClose={handlePermissionDialogClose}
          onSave={handlePermissionsSave}
          currentUser={currentUser}
        />
      )}
    </div>
  );
};

/*
lowercase typelookup
uppercase TYPELOOKUP
snakecase type_lookup
pascalcase TypeLookup
camelcase typeLookup
kebabcase type-lookup
*/

const TypeLookup = () => {
  return (
    <>
      <option value='product' label="Product" />
      <option value='service' label="Service" />
      <option value='discount' label="Discount" />
      <option value='adjustment' label="Adjustment" />
      <option value='other' label="Other" />
    </>
  );
};



/* Export the generated form */
export default LineItemForm;

