// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { ErrorMessage, Field, Formik, FormikHelpers, FormikValues } from 'formik';
import React, { useState } from 'react';
import {
  Form as BSForm,
  Accordion,
  Col,
  Row,
  Spinner,
  Alert
} from 'react-bootstrap';
import LoadingSpinner from '@valkyr/component-library/LoadingSpinner';
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from 'react-icons/fa';
import CoolButton from '@valkyr/component-library/CoolButton';
import * as Yup from 'yup';
import { SmartField } from '@valkyr/component-library/ForeignKey/SmartField';

import { PermissionDialog } from '@valkyr/component-library/PermissionDialog';
import { AclGrantRequest, PermissionType } from '@valkyr/component-library/PermissionDialog/types';


import {
  ThorApiSpecRevision,
  ThorApiSpecRevisionStatusEnum,
} from '@thorapi/model';

import { useAddThorApiSpecRevisionMutation } from '../../services/ThorApiSpecRevisionService';

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
ThorAPI/OpenAPI specification revision produced or selected for one tenant app generation run.
*/

/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */
const StatusValidation = () => {
  return [
    'draft',
    'generated',
    'applied',
    'failed',
    'superseded',
  ];
};

/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema: Yup.NumberSchema) =>
  schema.transform((val, orig) => (orig === '' || orig === null ? undefined : val));

const validationSchema = Yup.object().shape({
        specRevisionRef: Yup.string().required("specRevisionRef is required."),
        specDraftRef: Yup.string().required("specDraftRef is required."),
        tenantId: Yup.string().required("tenantId is required."),
        traceId: Yup.string().required("traceId is required."),
      status: Yup.mixed()
        .oneOf(StatusValidation(), "Invalid value for status")
        .required("status is required."),
        objectModelRef: Yup.string(),
        requestRef: Yup.string(),
        generationRunRef: Yup.string(),
        accountId: Yup.string(),
        applicationId: Yup.string(),
        openApiSpecId: Yup.string(),
        specChecksum: Yup.string(),
        specJson: Yup.string(),
        createdAt: Yup.date()
          .transform((value, originalValue) => {
            if (!originalValue) {
              return value;
            }
            const parsed = new Date(originalValue);
            return Number.isNaN(parsed.getTime()) ? value : parsed;
          }).typeError("createdAt must be a valid date"),
        errorMessage: Yup.string(),
        trashed: Yup.boolean(),
});

/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const ThorApiSpecRevisionForm: React.FC = () => {
  const [addThorApiSpecRevision, addThorApiSpecRevisionResult] = useAddThorApiSpecRevisionMutation();
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState<string | null>(null);

  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: 'current_user',
    permissions: {
      isOwner: true,
      isAdmin: true,
      canGrantPermissions: true,
      permissions: [PermissionType.READ, PermissionType.WRITE, PermissionType.CREATE, PermissionType.DELETE, PermissionType.ADMINISTRATION],
    },
  };

  /* -----------------------------------------------------
     INITIAL VALUES - only NON read-only fields
  -------------------------------------------------------- */
  const initialValues: Partial<ThorApiSpecRevision> = {
          specRevisionRef: '',
          specDraftRef: '',
          tenantId: '',
          traceId: '',
        status: undefined,
          objectModelRef: '',
          requestRef: '',
          generationRunRef: '',
          accountId: '',
          applicationId: '',
          openApiSpecId: '',
          specChecksum: '',
          specJson: '',
          createdAt: new Date(),
          errorMessage: '',
          trashed: false,
  };

  // Permission Management Handlers
  const handleManagePermissions = (objectId: string) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };

  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };

  const handlePermissionsSave = (grants: AclGrantRequest[]) => {
    console.log('Permissions saved for new ThorApiSpecRevision:', grants);
  };

  /* SUBMIT HANDLER */
  const handleSubmit = async (values: FormikValues, { setSubmitting }: FormikHelpers<ThorApiSpecRevision>) => {
    try {
      setSuccessMessage(null);
      setErrorMessage(null);
      console.log("ThorApiSpecRevision form values:", values);

      // NOTE: depending on your generated endpoint, you may need { body: values }
      const result = await addThorApiSpecRevision(values as any).unwrap();

      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `ThorApiSpecRevision created successfully! Would you like to set permissions for this object?`
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      setSuccessMessage("Saved successfully.");
    } catch (error) {
      console.error('Failed to create ThorApiSpecRevision:', error);
      setErrorMessage('Failed to save. Please try again.');
    }
    setSubmitting(false);
  };

  return (
    <div>
      <Formik
        validateOnBlur={true}
        initialValues={initialValues as ThorApiSpecRevision}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({
          isSubmitting,
          isValid,
          errors,
          values,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit
        }) => {
          const isSaving = isSubmitting || addThorApiSpecRevisionResult.isLoading;
          return (
          <form onSubmit={handleSubmit} className="form">
            <Accordion defaultActiveKey="1">
              
              {/* Editable Fields (NON read-only) */}
              <Accordion.Item eventKey="1">
                <Accordion.Header>
                  <FaRegPlusSquare size={28} /> &nbsp; Add New ThorApiSpecRevision
                </Accordion.Header>
                <Accordion.Body>
                    <label htmlFor="specRevisionRef" className="nice-form-control">
                      <b>
                        Spec Revision Ref:
                        {touched.specRevisionRef &&
                         !errors.specRevisionRef && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="specRevisionRef"
                            value={values?.specRevisionRef}
                            placeholder="Spec Revision Ref"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="specRevisionRef"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="specDraftRef" className="nice-form-control">
                      <b>
                        Spec Draft Ref:
                        {touched.specDraftRef &&
                         !errors.specDraftRef && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="specDraftRef"
                            value={values?.specDraftRef}
                            placeholder="Spec Draft Ref"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="specDraftRef"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="tenantId" className="nice-form-control">
                      <b>
                        Tenant Id:
                        {touched.tenantId &&
                         !errors.tenantId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="tenantId"
                            value={values?.tenantId}
                            placeholder="Tenant Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="tenantId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="traceId" className="nice-form-control">
                      <b>
                        Trace Id:
                        {touched.traceId &&
                         !errors.traceId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="traceId"
                            value={values?.traceId}
                            placeholder="Trace Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="traceId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="status" className="nice-form-control">
                      <b>
                        Status:
                        {touched.status &&
                         !errors.status && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>

                        {/* ENUM DROPDOWN */}
                        <BSForm.Select
                          name="status"
                          value={values.status || ''}
                          className={
                            errors.status
                              ? 'form-control field-error'
                              : 'nice-form-control form-control'
                          }
                          onChange={(e) => {
                            setFieldTouched('status', true);
                            setFieldValue('status', e.target.value || undefined);
                          }}
                        >
                          <option value="" label="Select Status" />
                          <StatusLookup />
                        </BSForm.Select>


                      <ErrorMessage
                        className="error"
                        name="status"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="objectModelRef" className="nice-form-control">
                      <b>
                        Object Model Ref:
                        {touched.objectModelRef &&
                         !errors.objectModelRef && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="objectModelRef"
                            value={values?.objectModelRef}
                            placeholder="Object Model Ref"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="objectModelRef"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="requestRef" className="nice-form-control">
                      <b>
                        Request Ref:
                        {touched.requestRef &&
                         !errors.requestRef && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="requestRef"
                            value={values?.requestRef}
                            placeholder="Request Ref"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="requestRef"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="generationRunRef" className="nice-form-control">
                      <b>
                        Generation Run Ref:
                        {touched.generationRunRef &&
                         !errors.generationRunRef && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="generationRunRef"
                            value={values?.generationRunRef}
                            placeholder="Generation Run Ref"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="generationRunRef"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="accountId" className="nice-form-control">
                      <b>
                        Account Id:
                        {touched.accountId &&
                         !errors.accountId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="accountId"
                            value={values?.accountId}
                            placeholder="Account Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="accountId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="applicationId" className="nice-form-control">
                      <b>
                        Application Id:
                        {touched.applicationId &&
                         !errors.applicationId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="applicationId"
                            value={values?.applicationId}
                            placeholder="Application Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="applicationId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="openApiSpecId" className="nice-form-control">
                      <b>
                        Open Api Spec Id:
                        {touched.openApiSpecId &&
                         !errors.openApiSpecId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="openApiSpecId"
                            value={values?.openApiSpecId}
                            placeholder="Open Api Spec Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="openApiSpecId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="specChecksum" className="nice-form-control">
                      <b>
                        Spec Checksum:
                        {touched.specChecksum &&
                         !errors.specChecksum && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="specChecksum"
                            value={values?.specChecksum}
                            placeholder="Spec Checksum"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="specChecksum"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="specJson" className="nice-form-control">
                      <b>
                        Spec Json:
                        {touched.specJson &&
                         !errors.specJson && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="specJson"
                            value={values?.specJson}
                            placeholder="Spec Json"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="specJson"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="createdAt" className="nice-form-control">
                      <b>
                        Created At:
                        {touched.createdAt &&
                         !errors.createdAt && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>









                          {/* DATETIME FIELD */}
                          <Field
                            name="createdAt"
                            type="datetime-local"
                            value={values.createdAt ? 
                              new Date(values.createdAt).toISOString().slice(0, 16) : 
                              ''}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                              setFieldTouched('createdAt', true);
                              const v = e.target.value;
                              setFieldValue('createdAt', v ? new Date(v).toISOString() : '');
                            }}
                            className={
                              errors.createdAt
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />

                      <ErrorMessage
                        className="error"
                        name="createdAt"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="errorMessage" className="nice-form-control">
                      <b>
                        Error Message:
                        {touched.errorMessage &&
                         !errors.errorMessage && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="errorMessage"
                            value={values?.errorMessage}
                            placeholder="Error Message"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="errorMessage"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="trashed" className="nice-form-control">
                      <b>
                        Trashed:
                        {touched.trashed &&
                         !errors.trashed && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>


                          {/* CHECKBOX FIELD */}
                          <BSForm.Check
                            id="trashed"
                            name="trashed"
                            checked={values.trashed || false}
                            onChange={(e) => {
                              setFieldTouched('trashed', true);
                              setFieldValue('trashed', e.target.checked);
                            }}
                            isInvalid={!!errors.trashed}
                            className={errors.trashed ? 'error' : ''}
                          />








                      <ErrorMessage
                        className="error"
                        name="trashed"
                        component="span"
                      />
                    </label>
                    <br />

                  {/* SUBMIT BUTTON */}
                  <CoolButton
                    variant={isValid ? (isSaving ? 'disabled' : 'success') : 'warning'}
                    type="submit"
                    disabled={!isValid || isSaving}
                  >
                    {isSaving && (<span style={ { float: 'left', minHeight: 0 } }><LoadingSpinner label="" size={18} /></span>)}
                    <FaCheckCircle size={28} /> Create New ThorApiSpecRevision
                  </CoolButton>

                  {(addThorApiSpecRevisionResult.isError || errorMessage) && (
                    <Alert variant="danger" className="mt-3">
                      {errorMessage ||
                        JSON.stringify('data' in (addThorApiSpecRevisionResult as any).error ? (addThorApiSpecRevisionResult as any).error.data : (addThorApiSpecRevisionResult as any).error)}
                    </Alert>
                  )}

                  {(addThorApiSpecRevisionResult.isSuccess || successMessage) && (
                    <Alert variant="success" className="mt-3">
                      {successMessage || 'Saved successfully.'}
                    </Alert>
                  )}
                </Accordion.Body>
              </Accordion.Item>

            {/* Debug/Dev Accordion */}
              <Accordion.Item eventKey="0">
                <Accordion.Header>
                  <FaCogs size={28} /> &nbsp;Server Messages
                </Accordion.Header>
                <Accordion.Body>
                  errors: {JSON.stringify(errors)}
                  <br />
                  addThorApiSpecRevisionResult: {JSON.stringify(addThorApiSpecRevisionResult)}
                </Accordion.Body>
              </Accordion.Item>

            </Accordion>
          </form>
          );
        }}
      </Formik>

      {/* Permission Management Dialog */}
      {createdObjectId && (
        <PermissionDialog
          objectType="com.valkyrlabs.model.ThorApiSpecRevision"
          objectId={createdObjectId}
          isVisible={showPermissionDialog}
          onClose={handlePermissionDialogClose}
          onSave={handlePermissionsSave}
          currentUser={currentUser}
        />
      )}
    </div>
  );
};

/*
lowercase statuslookup
uppercase STATUSLOOKUP
snakecase status_lookup
pascalcase StatusLookup
camelcase statusLookup
kebabcase status-lookup
*/

const StatusLookup = () => {
  return (
    <>
      <option value='draft' label="Draft" />
      <option value='generated' label="Generated" />
      <option value='applied' label="Applied" />
      <option value='failed' label="Failed" />
      <option value='superseded' label="Superseded" />
    </>
  );
};



/* Export the generated form */
export default ThorApiSpecRevisionForm;

