// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { ErrorMessage, Field, Formik, FormikHelpers, FormikValues } from 'formik';
import React, { useState } from 'react';
import {
  Form as BSForm,
  Accordion,
  Col,
  Row,
  Spinner,
  Alert
} from 'react-bootstrap';
import LoadingSpinner from '@valkyr/component-library/LoadingSpinner';
import { FaCheckCircle, FaCogs, FaRegPlusSquare } from 'react-icons/fa';
import CoolButton from '@valkyr/component-library/CoolButton';
import * as Yup from 'yup';
import { SmartField } from '@valkyr/component-library/ForeignKey/SmartField';

import { PermissionDialog } from '@valkyr/component-library/PermissionDialog';
import { AclGrantRequest, PermissionType } from '@valkyr/component-library/PermissionDialog/types';


import {
  TicketComment,
} from '@thorapi/model';

import { useAddTicketCommentMutation } from '../../services/TicketCommentService';

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelForm.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description:
Represents a comment or update on a support ticket.
*/

/* -----------------------------------------------------
   ENUM VALIDATION ARRAYS (Yup oneOf checks), if any
-------------------------------------------------------- */

/* -----------------------------------------------------
   YUP VALIDATION SCHEMA (skip read-only fields)
-------------------------------------------------------- */
const asNumber = (schema: Yup.NumberSchema) =>
  schema.transform((val, orig) => (orig === '' || orig === null ? undefined : val));

const validationSchema = Yup.object().shape({
        ticketId: Yup.string().required("ticketId is required."),
        author: Yup.string().required("author is required."),
        content: Yup.string().required("content is required."),
        isInternal: Yup.boolean().required("isInternal is required."),
        commentDate: Yup.date()
          .transform((value, originalValue) => {
            if (!originalValue) {
              return value;
            }
            const parsed = new Date(originalValue);
            return Number.isNaN(parsed.getTime()) ? value : parsed;
          }).typeError("commentDate must be a valid date"),
        trashed: Yup.boolean(),
});

/* -----------------------------------------------------
   COMPONENT
-------------------------------------------------------- */
const TicketCommentForm: React.FC = () => {
  const [addTicketComment, addTicketCommentResult] = useAddTicketCommentMutation();
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Permission Management State
  const [showPermissionDialog, setShowPermissionDialog] = useState(false);
  const [createdObjectId, setCreatedObjectId] = useState<string | null>(null);

  // Mock current user - in real implementation, this would come from auth context
  const currentUser = {
    username: 'current_user',
    permissions: {
      isOwner: true,
      isAdmin: true,
      canGrantPermissions: true,
      permissions: [PermissionType.READ, PermissionType.WRITE, PermissionType.CREATE, PermissionType.DELETE, PermissionType.ADMINISTRATION],
    },
  };

  /* -----------------------------------------------------
     INITIAL VALUES - only NON read-only fields
  -------------------------------------------------------- */
  const initialValues: Partial<TicketComment> = {
          ticketId: '',
          author: '',
          content: '',
          isInternal: false,
          commentDate: new Date(),
          trashed: false,
  };

  // Permission Management Handlers
  const handleManagePermissions = (objectId: string) => {
    setCreatedObjectId(objectId);
    setShowPermissionDialog(true);
  };

  const handlePermissionDialogClose = () => {
    setShowPermissionDialog(false);
    setCreatedObjectId(null);
  };

  const handlePermissionsSave = (grants: AclGrantRequest[]) => {
    console.log('Permissions saved for new TicketComment:', grants);
  };

  /* SUBMIT HANDLER */
  const handleSubmit = async (values: FormikValues, { setSubmitting }: FormikHelpers<TicketComment>) => {
    try {
      setSuccessMessage(null);
      setErrorMessage(null);
      console.log("TicketComment form values:", values);

      // NOTE: depending on your generated endpoint, you may need { body: values }
      const result = await addTicketComment(values as any).unwrap();

      if (result && result.id && currentUser.permissions.canGrantPermissions) {
        const shouldSetPermissions = window.confirm(
          `TicketComment created successfully! Would you like to set permissions for this object?`
        );
        if (shouldSetPermissions) {
          handleManagePermissions(result.id);
        }
      }
      setSuccessMessage("Saved successfully.");
    } catch (error) {
      console.error('Failed to create TicketComment:', error);
      setErrorMessage('Failed to save. Please try again.');
    }
    setSubmitting(false);
  };

  return (
    <div>
      <Formik
        validateOnBlur={true}
        initialValues={initialValues as TicketComment}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({
          isSubmitting,
          isValid,
          errors,
          values,
          setFieldValue,
          touched,
          setFieldTouched,
          handleSubmit
        }) => {
          const isSaving = isSubmitting || addTicketCommentResult.isLoading;
          return (
          <form onSubmit={handleSubmit} className="form">
            <Accordion defaultActiveKey="1">
              
              {/* Editable Fields (NON read-only) */}
              <Accordion.Item eventKey="1">
                <Accordion.Header>
                  <FaRegPlusSquare size={28} /> &nbsp; Add New TicketComment
                </Accordion.Header>
                <Accordion.Body>
                    <label htmlFor="ticketId" className="nice-form-control">
                      <b>
                        Ticket Id:
                        {touched.ticketId &&
                         !errors.ticketId && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="ticketId"
                            value={values?.ticketId}
                            placeholder="Ticket Id"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="ticketId"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="author" className="nice-form-control">
                      <b>
                        Author:
                        {touched.author &&
                         !errors.author && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="author"
                            value={values?.author}
                            placeholder="Author"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="author"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="content" className="nice-form-control">
                      <b>
                        Content:
                        {touched.content &&
                         !errors.content && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>



                          {/* SMART FIELD (UUID-aware picker for *Id), fallback text */}
                          <SmartField
                            name="content"
                            value={values?.content}
                            placeholder="Content"
                            setFieldValue={setFieldValue}
                            setFieldTouched={setFieldTouched}
                          />







                      <ErrorMessage
                        className="error"
                        name="content"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="isInternal" className="nice-form-control">
                      <b>
                        Is Internal:
                        {touched.isInternal &&
                         !errors.isInternal && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>


                          {/* CHECKBOX FIELD */}
                          <BSForm.Check
                            id="isInternal"
                            name="isInternal"
                            checked={values.isInternal || false}
                            onChange={(e) => {
                              setFieldTouched('isInternal', true);
                              setFieldValue('isInternal', e.target.checked);
                            }}
                            isInvalid={!!errors.isInternal}
                            className={errors.isInternal ? 'error' : ''}
                          />








                      <ErrorMessage
                        className="error"
                        name="isInternal"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="commentDate" className="nice-form-control">
                      <b>
                        Comment Date:
                        {touched.commentDate &&
                         !errors.commentDate && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>









                          {/* DATETIME FIELD */}
                          <Field
                            name="commentDate"
                            type="datetime-local"
                            value={values.commentDate ? 
                              new Date(values.commentDate).toISOString().slice(0, 16) : 
                              ''}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                              setFieldTouched('commentDate', true);
                              const v = e.target.value;
                              setFieldValue('commentDate', v ? new Date(v).toISOString() : '');
                            }}
                            className={
                              errors.commentDate
                                ? 'form-control field-error'
                                : 'nice-form-control form-control'
                            }
                          />

                      <ErrorMessage
                        className="error"
                        name="commentDate"
                        component="span"
                      />
                    </label>
                    <br />
                    <label htmlFor="trashed" className="nice-form-control">
                      <b>
                        Trashed:
                        {touched.trashed &&
                         !errors.trashed && (
                          <span className="okCheck"><FaCheckCircle /> looks good!</span>
                        )}
                      </b>


                          {/* CHECKBOX FIELD */}
                          <BSForm.Check
                            id="trashed"
                            name="trashed"
                            checked={values.trashed || false}
                            onChange={(e) => {
                              setFieldTouched('trashed', true);
                              setFieldValue('trashed', e.target.checked);
                            }}
                            isInvalid={!!errors.trashed}
                            className={errors.trashed ? 'error' : ''}
                          />








                      <ErrorMessage
                        className="error"
                        name="trashed"
                        component="span"
                      />
                    </label>
                    <br />

                  {/* SUBMIT BUTTON */}
                  <CoolButton
                    variant={isValid ? (isSaving ? 'disabled' : 'success') : 'warning'}
                    type="submit"
                    disabled={!isValid || isSaving}
                  >
                    {isSaving && (<span style={ { float: 'left', minHeight: 0 } }><LoadingSpinner label="" size={18} /></span>)}
                    <FaCheckCircle size={28} /> Create New TicketComment
                  </CoolButton>

                  {(addTicketCommentResult.isError || errorMessage) && (
                    <Alert variant="danger" className="mt-3">
                      {errorMessage ||
                        JSON.stringify('data' in (addTicketCommentResult as any).error ? (addTicketCommentResult as any).error.data : (addTicketCommentResult as any).error)}
                    </Alert>
                  )}

                  {(addTicketCommentResult.isSuccess || successMessage) && (
                    <Alert variant="success" className="mt-3">
                      {successMessage || 'Saved successfully.'}
                    </Alert>
                  )}
                </Accordion.Body>
              </Accordion.Item>

            {/* Debug/Dev Accordion */}
              <Accordion.Item eventKey="0">
                <Accordion.Header>
                  <FaCogs size={28} /> &nbsp;Server Messages
                </Accordion.Header>
                <Accordion.Body>
                  errors: {JSON.stringify(errors)}
                  <br />
                  addTicketCommentResult: {JSON.stringify(addTicketCommentResult)}
                </Accordion.Body>
              </Accordion.Item>

            </Accordion>
          </form>
          );
        }}
      </Formik>

      {/* Permission Management Dialog */}
      {createdObjectId && (
        <PermissionDialog
          objectType="com.valkyrlabs.model.TicketComment"
          objectId={createdObjectId}
          isVisible={showPermissionDialog}
          onClose={handlePermissionDialogClose}
          onSave={handlePermissionsSave}
          currentUser={currentUser}
        />
      )}
    </div>
  );
};



/* Export the generated form */
export default TicketCommentForm;

