"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GoalDependencyFromJSON = GoalDependencyFromJSON;
exports.GoalDependencyToJSON = GoalDependencyToJSON;
const runtime_1 = require("../src/runtime");
function GoalDependencyFromJSON(json) {
    return {
        'goalId': !(0, runtime_1.exists)(json, 'goalId') ? undefined : json['goalId'],
        'dependencyOrder': !(0, runtime_1.exists)(json, 'dependencyOrder') ? undefined : json['dependencyOrder'],
        'dependencyName': !(0, runtime_1.exists)(json, 'dependencyName') ? undefined : json['dependencyName'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'ownerId': !(0, runtime_1.exists)(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !(0, runtime_1.exists)(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !(0, runtime_1.exists)(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !(0, runtime_1.exists)(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !(0, runtime_1.exists)(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !(0, runtime_1.exists)(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !(0, runtime_1.exists)(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}
function GoalDependencyToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        'goalId': value.goalId,
        'dependencyOrder': value.dependencyOrder,
        'dependencyName': value.dependencyName,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}
//# sourceMappingURL=GoalDependency.js.map