// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelReducer.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createSlice } from "@reduxjs/toolkit";
const AclEntrySlice = createSlice({
    name: "AclEntrys",
    initialState: [],
    reducers: {
        AclEntryAdded(state, action) {
            state.push(action.payload);
        },
        AclEntryValueToggled(state, action) {
            console.log("AclEntry TOGGLE");
            console.warn(JSON.stringify(action));
            const AclEntry = state.find((AclEntry) => AclEntry.id === action.payload.AclEntryId);
            if (AclEntry) {
                if (action.payload.target === "SOMETHING") {
                }
            }
        },
        AclEntrypropertySet(state, action) {
            const AclEntry = state.find((AclEntry) => AclEntry.id === action.payload.AclEntryId);
            if (AclEntry) {
                //  AclEntry[action.property] = action.payload[action.property];
            }
        },
    },
});
export const { AclEntryAdded, AclEntryValueToggled, AclEntrypropertySet } = AclEntrySlice.actions;
export default AclEntrySlice.reducer;
//# sourceMappingURL=AclEntryReducer.js.map