// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelReducer.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createSlice } from "@reduxjs/toolkit";
const ApplicationSlice = createSlice({
    name: "Applications",
    initialState: [],
    reducers: {
        ApplicationAdded(state, action) {
            state.push(action.payload);
        },
        ApplicationValueToggled(state, action) {
            console.log("Application TOGGLE");
            console.warn(JSON.stringify(action));
            const Application = state.find((Application) => Application.id === action.payload.ApplicationId);
            if (Application) {
                if (action.payload.target === "SOMETHING") {
                }
            }
        },
        ApplicationpropertySet(state, action) {
            const Application = state.find((Application) => Application.id === action.payload.ApplicationId);
            if (Application) {
                //  Application[action.property] = action.payload[action.property];
            }
        },
    },
});
export const { ApplicationAdded, ApplicationValueToggled, ApplicationpropertySet, } = ApplicationSlice.actions;
export default ApplicationSlice.reducer;
//# sourceMappingURL=ApplicationReducer.js.map