// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelReducer.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { createSlice } from "@reduxjs/toolkit";
const BuildSlice = createSlice({
    name: "Builds",
    initialState: [],
    reducers: {
        BuildAdded(state, action) {
            state.push(action.payload);
        },
        BuildValueToggled(state, action) {
            console.log("Build TOGGLE");
            console.warn(JSON.stringify(action));
            const Build = state.find((Build) => Build.id === action.payload.BuildId);
            if (Build) {
                if (action.payload.target === "SOMETHING") {
                }
            }
        },
        BuildpropertySet(state, action) {
            const Build = state.find((Build) => Build.id === action.payload.BuildId);
            if (Build) {
                //  Build[action.property] = action.payload[action.property];
            }
        },
    },
});
export const { BuildAdded, BuildValueToggled, BuildpropertySet } = BuildSlice.actions;
export default BuildSlice.reducer;
//# sourceMappingURL=BuildReducer.js.map