/**
 * Service Monetization API Client
 *
 * Integrates with ThorAPI backend generated services.
 * All endpoints route through the ValkyrAI backend with automatic JWT token injection.
 */
import axios, { AxiosHeaders } from "axios";
import { getValkyraiBasePath } from "@utils/serverValkyraiHost";
let apiInstance = null;
let extensionContext = null;
/**
 * Creates axios instance configured for ThorAPI backend
 * Uses standard REST endpoints generated by ThorAPI
 */
function createApiInstance() {
  const baseURL = getValkyraiBasePath();
  const instance = axios.create({
    baseURL,
    timeout: 30000,
    headers: {
      "Content-Type": "application/json",
    },
  });
  // Add request interceptor to inject JWT token from VSCode secrets
  instance.interceptors.request.use(
    async (config) => {
      try {
        if (extensionContext) {
          const token = await extensionContext.secrets.get("jwtToken");
          if (token) {
            const headers = config.headers ?? new AxiosHeaders();
            headers.set("Authorization", `Bearer ${token}`);
            config.headers = headers;
          }
        }
      } catch (error) {
        console.warn(
          "Failed to retrieve auth token from extension context:",
          error,
        );
      }
      return config;
    },
    (error) => Promise.reject(error),
  );
  // Add response interceptor for error handling and logging
  instance.interceptors.response.use(
    (response) => response,
    (error) => {
      console.error(
        "ThorAPI Monetization Error:",
        error.response?.data || error.message,
      );
      return Promise.reject(error);
    },
  );
  return instance;
}
/**
 * Initialize the API client with extension context for secure token access
 */
export function initializeApi(context) {
  extensionContext = context;
  apiInstance = createApiInstance();
}
/**
 * Get or create the API instance
 */
export function getApi() {
  if (!apiInstance) {
    apiInstance = createApiInstance();
  }
  return apiInstance;
}
/**
 * Exported API object compatible with ServiceMonetizationService
 * Routes all requests through ThorAPI-generated endpoints
 */
export const api = {
  get: (url, config) => getApi().get(url, config),
  post: (url, data, config) => getApi().post(url, data, config),
  patch: (url, data, config) => getApi().patch(url, data, config),
  put: (url, data, config) => getApi().put(url, data, config),
  delete: (url, config) => getApi().delete(url, config),
};
//# sourceMappingURL=api.js.map
