// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { exists } from "../src/runtime";
import { DataObjectFromJSON, DataObjectToJSON } from "./DataObject";
export function McpServiceRegistryFromJSON(json) {
  return {
    ...DataObjectFromJSON(json),
    slug: json["slug"],
    displayName: json["displayName"],
    description: !exists(json, "description") ? undefined : json["description"],
    category: !exists(json, "category") ? undefined : json["category"],
    author: !exists(json, "author") ? undefined : json["author"],
    manifestUrl: !exists(json, "manifestUrl") ? undefined : json["manifestUrl"],
    apiBaseUrl: !exists(json, "apiBaseUrl") ? undefined : json["apiBaseUrl"],
    healthCheckUrl: !exists(json, "healthCheckUrl")
      ? undefined
      : json["healthCheckUrl"],
    version: !exists(json, "version") ? undefined : json["version"],
    isPublished: !exists(json, "isPublished") ? undefined : json["isPublished"],
    installCount: !exists(json, "installCount")
      ? undefined
      : json["installCount"],
    tags: !exists(json, "tags") ? undefined : json["tags"],
    publishedDate: !exists(json, "publishedDate")
      ? undefined
      : new Date(json["publishedDate"]),
    updatedDate: !exists(json, "updatedDate")
      ? undefined
      : new Date(json["updatedDate"]),
    mcpServerId: !exists(json, "mcpServerId") ? undefined : json["mcpServerId"],
    id: !exists(json, "id") ? undefined : json["id"],
    ownerId: !exists(json, "ownerId") ? undefined : json["ownerId"],
    createdDate: !exists(json, "createdDate")
      ? undefined
      : new Date(json["createdDate"]),
    keyHash: !exists(json, "keyHash") ? undefined : json["keyHash"],
    lastAccessedById: !exists(json, "lastAccessedById")
      ? undefined
      : json["lastAccessedById"],
    lastAccessedDate: !exists(json, "lastAccessedDate")
      ? undefined
      : new Date(json["lastAccessedDate"]),
    lastModifiedById: !exists(json, "lastModifiedById")
      ? undefined
      : json["lastModifiedById"],
    lastModifiedDate: !exists(json, "lastModifiedDate")
      ? undefined
      : new Date(json["lastModifiedDate"]),
    trashed: !exists(json, "trashed") ? undefined : json["trashed"],
  };
}
export function McpServiceRegistryToJSON(value) {
  if (value === undefined) {
    return undefined;
  }
  return {
    ...DataObjectToJSON(value),
    slug: value.slug,
    displayName: value.displayName,
    description: value.description,
    category: value.category,
    author: value.author,
    manifestUrl: value.manifestUrl,
    apiBaseUrl: value.apiBaseUrl,
    healthCheckUrl: value.healthCheckUrl,
    version: value.version,
    isPublished: value.isPublished,
    installCount: value.installCount,
    tags: value.tags,
    publishedDate:
      value.publishedDate === undefined
        ? undefined
        : value.publishedDate.toISOString(),
    updatedDate:
      value.updatedDate === undefined
        ? undefined
        : value.updatedDate.toISOString(),
    mcpServerId: value.mcpServerId,
    trashed: value.trashed,
  };
}
/**
 * @export
 * @enum {string}
 */
export var McpServiceRegistryCategoryEnum;
(function (McpServiceRegistryCategoryEnum) {
  McpServiceRegistryCategoryEnum["CODEGENERATION"] = "code_generation";
  McpServiceRegistryCategoryEnum["AUTOMATION"] = "automation";
  McpServiceRegistryCategoryEnum["OPTIMIZATION"] = "optimization";
  McpServiceRegistryCategoryEnum["INTEGRATION"] = "integration";
  McpServiceRegistryCategoryEnum["ANALYTICS"] = "analytics";
  McpServiceRegistryCategoryEnum["CUSTOM"] = "custom";
})(McpServiceRegistryCategoryEnum || (McpServiceRegistryCategoryEnum = {}));
//# sourceMappingURL=McpServiceRegistry.js.map
