"use strict";
// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OasParameterLocationEnum = void 0;
exports.OasParameterFromJSON = OasParameterFromJSON;
exports.OasParameterToJSON = OasParameterToJSON;
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-11-16T09:57:41.565555-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
const runtime_1 = require("../src/runtime");
const DataObject_1 = require("./DataObject");
const _1 = require("./");
function OasParameterFromJSON(json) {
    return {
        ...(0, DataObject_1.DataObjectFromJSON)(json),
        oasOperationId: !(0, runtime_1.exists)(json, "oasOperationId")
            ? undefined
            : json["oasOperationId"],
        name: !(0, runtime_1.exists)(json, "name") ? undefined : json["name"],
        location: !(0, runtime_1.exists)(json, "location") ? undefined : json["location"],
        description: !(0, runtime_1.exists)(json, "description") ? undefined : json["description"],
        required: !(0, runtime_1.exists)(json, "required") ? undefined : json["required"],
        schema: !(0, runtime_1.exists)(json, "schema")
            ? undefined
            : (0, _1.OasObjectSchemaFromJSON)(json["schema"]),
        id: !(0, runtime_1.exists)(json, "id") ? undefined : json["id"],
        ownerId: !(0, runtime_1.exists)(json, "ownerId") ? undefined : json["ownerId"],
        createdDate: !(0, runtime_1.exists)(json, "createdDate")
            ? undefined
            : new Date(json["createdDate"]),
        keyHash: !(0, runtime_1.exists)(json, "keyHash") ? undefined : json["keyHash"],
        lastAccessedById: !(0, runtime_1.exists)(json, "lastAccessedById")
            ? undefined
            : json["lastAccessedById"],
        lastAccessedDate: !(0, runtime_1.exists)(json, "lastAccessedDate")
            ? undefined
            : new Date(json["lastAccessedDate"]),
        lastModifiedById: !(0, runtime_1.exists)(json, "lastModifiedById")
            ? undefined
            : json["lastModifiedById"],
        lastModifiedDate: !(0, runtime_1.exists)(json, "lastModifiedDate")
            ? undefined
            : new Date(json["lastModifiedDate"]),
    };
}
function OasParameterToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...(0, DataObject_1.DataObjectToJSON)(value),
        oasOperationId: value.oasOperationId,
        name: value.name,
        location: value.location,
        description: value.description,
        required: value.required,
        schema: (0, _1.OasObjectSchemaToJSON)(value.schema),
        id: value.id,
        ownerId: value.ownerId,
        createdDate: value.createdDate === undefined
            ? undefined
            : value.createdDate.toISOString(),
        keyHash: value.keyHash,
        lastAccessedById: value.lastAccessedById,
        lastAccessedDate: value.lastAccessedDate === undefined
            ? undefined
            : value.lastAccessedDate.toISOString(),
        lastModifiedById: value.lastModifiedById,
        lastModifiedDate: value.lastModifiedDate === undefined
            ? undefined
            : value.lastModifiedDate.toISOString(),
    };
}
/**
 * @export
 * @enum {string}
 */
var OasParameterLocationEnum;
(function (OasParameterLocationEnum) {
    OasParameterLocationEnum["QUERY"] = "query";
    OasParameterLocationEnum["HEADER"] = "header";
    OasParameterLocationEnum["PATH"] = "path";
    OasParameterLocationEnum["COOKIE"] = "cookie";
})(OasParameterLocationEnum || (exports.OasParameterLocationEnum = OasParameterLocationEnum = {}));
//# sourceMappingURL=OasParameter.js.map