// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-12-07T16:29:11.456024-08:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { exists } from "../src/runtime";
import { DataObjectFromJSON, DataObjectToJSON } from "./DataObject";
import { CellFromJSON, CellToJSON } from "./";
export function SheetColumnFromJSON(json) {
    return {
        ...DataObjectFromJSON(json),
        sheetId: !exists(json, "sheetId") ? undefined : json["sheetId"],
        colIndex: !exists(json, "colIndex") ? undefined : json["colIndex"],
        hidden: !exists(json, "hidden") ? undefined : json["hidden"],
        collapsed: !exists(json, "collapsed") ? undefined : json["collapsed"],
        outlineLevel: !exists(json, "outlineLevel")
            ? undefined
            : json["outlineLevel"],
        cells: !exists(json, "cells")
            ? undefined
            : json["cells"].map(CellFromJSON),
        id: !exists(json, "id") ? undefined : json["id"],
        ownerId: !exists(json, "ownerId") ? undefined : json["ownerId"],
        createdDate: !exists(json, "createdDate")
            ? undefined
            : new Date(json["createdDate"]),
        keyHash: !exists(json, "keyHash") ? undefined : json["keyHash"],
        lastAccessedById: !exists(json, "lastAccessedById")
            ? undefined
            : json["lastAccessedById"],
        lastAccessedDate: !exists(json, "lastAccessedDate")
            ? undefined
            : new Date(json["lastAccessedDate"]),
        lastModifiedById: !exists(json, "lastModifiedById")
            ? undefined
            : json["lastModifiedById"],
        lastModifiedDate: !exists(json, "lastModifiedDate")
            ? undefined
            : new Date(json["lastModifiedDate"]),
        trashed: !exists(json, "trashed") ? undefined : json["trashed"],
    };
}
export function SheetColumnToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...DataObjectToJSON(value),
        sheetId: value.sheetId,
        colIndex: value.colIndex,
        hidden: value.hidden,
        collapsed: value.collapsed,
        outlineLevel: value.outlineLevel,
        cells: value.cells === undefined
            ? undefined
            : value.cells.map(CellToJSON),
        trashed: value.trashed,
    };
}
//# sourceMappingURL=SheetColumn.js.map