// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// tslint:disable
/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com/thorapi
Powered by Swagger Codegen: http://swagger.io

Generated Details:
**GENERATOR VERSION:** 7.5.0
**GENERATED DATE:** 2025-10-30T14:43:21.527935-07:00[America/Los_Angeles]
**GENERATOR CLASS:** org.openapitools.codegen.languages.TypeScriptReduxQueryClientCodegen

Template file: typescript-redux-query/modelGeneric.ts.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
*/
import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * Node describing an entity within the swarm network.
 * @export
 * @interface SwarmGraphNode
 */
export type SwarmGraphNode  = {
    /**
     * Classification for the entity represented in the graph.
     * @type {string}
     * @memberof SwarmGraphNode
     */
    type: string;
    /**
     * Human readable label rendered in dashboards.
     * @type {string}
     * @memberof SwarmGraphNode
     */
    label: string;
    /**
     * Operational status flag (online/offline).
     * @type {string}
     * @memberof SwarmGraphNode
     */
    status?: string;
    /**
     * Timestamp of the last heartbeat for this entity.
     * @type {Date}
     * @memberof SwarmGraphNode
     */
    lastSeen?: Date;
    /**
     * Arbitrary metadata shared by the entity.
     * @type {string}
     * @memberof SwarmGraphNode
     */
    metadata?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof SwarmGraphNode
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof SwarmGraphNode
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof SwarmGraphNode
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof SwarmGraphNode
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof SwarmGraphNode
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof SwarmGraphNode
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof SwarmGraphNode
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof SwarmGraphNode
     */
    lastModifiedDate?: Date;
}

export function SwarmGraphNodeFromJSON(json: any): SwarmGraphNode {
    return {
        'type': json['type'],
        'label': json['label'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'lastSeen': !exists(json, 'lastSeen') ? undefined : new Date(json['lastSeen']),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function SwarmGraphNodeToJSON(value?: SwarmGraphNode): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'type': value.type,
        'label': value.label,
        'status': value.status,
        'lastSeen': value.lastSeen === undefined ? undefined : value.lastSeen.toISOString(),
        'metadata': value.metadata,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}


